### PR TITLE
Fixed bug when using multiple variables of the same name with `for`. Fixes #266

### LINKED ISSUE #266: FOR: dublicate initialization with same name
Example of valid C code:
```c
#include<stdio.h>
int main(){
        int a = 0;
        for (int i=0;i<2;i++){
                printf("%d",a++);
        }
        for (int i=0;i<2;i++){
                printf("%d",a++);
        }
        return 0;
}
```
Result of `gcc`:
```
0123
```
After transpilation to Go code:
```golang
func main() {
        __init()
        var a int = 0
        var i int = 0
        for ; i < 2; func() int {
                i += 1
                return i
        }() {
                noarch.Printf([]byte("%d\x00"), func() int {
                        a += 1
                        return a
                }())
        }
        var i int = 0            // <----- REDECLARATION HERE
        for ; i < 2; func() int {
                i += 1
                return i
        }() {
                noarch.Printf([]byte("%d\x00"), func() int {
                        a += 1
                        return a
                }())
        }
        return
}
```
Error after `go run`:
```
./f.go:123: i redeclared in this block
	previous declaration at ./f.go:113
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #266

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/285)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-KxjRoiOlAKSF6ojgMy-:bqzwlt8) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
> ```Go
> 
> 	// for avoid dublication of init values for
> 	// case with 2 for`s
> ```

Rather than wrapping the whole `for` in a `BlockStmt` what about modifying the `Init` so that it more closely resembles what the Go code should look like?

---

*[transpiler/goto.go, line 16 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxhtfiXt-SC0WJQqcPB-r1-16:-KxjSAzB0gvg2DmuS3ie:baf3kp6) ([raw file](https://github.com/elliotchance/c2go/blob/670c9ab206101378899f0863e1df5239c2b2f856/transpiler/goto.go#L16)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Add test with Comma problem
</blockquote></details>

The `if` check is redundant because if the there are zero elements to the `for` will not run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-KxnhkejTPoIt5YKCCM1:bke9th3) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Rather than wrapping the whole `for` in a `BlockStmt` what about modifying the `Init` so that it more closely resembles what the Go code should look like?
</blockquote></details>

in C code:
```c
for(init;condition;iterator){
body
}
```
In according to your comment - you mean create a Go code like that? Please confirm.
```go
{
     init
}
for   ; condition; iterator {
    body
}
```
In my point of view, that Go code is not work.

---

*[transpiler/goto.go, line 16 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxhtfiXt-SC0WJQqcPB-r1-16:-KxnirHklMTisxlQIoXm:b5qua0o) ([raw file](https://github.com/elliotchance/c2go/blob/670c9ab206101378899f0863e1df5239c2b2f856/transpiler/goto.go#L16)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

The `if` check is redundant because if the there are zero elements to the `for` will not run.
</blockquote></details>

So, we can use only `for`. Good idea, thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-KxoP1DOez36OzleKzy3:b-88zp2d) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

in C code:
```c
for(init;condition;iterator){
body
}
```
In according to your comment - you mean create a Go code like that? Please confirm.
```go
{
     init
}
for   ; condition; iterator {
    body
}
```
In my point of view, that Go code is not work.


</blockquote></details>

Go has an initialiser just like C:

```c
for (int i = 0; i < 3; i++) {}
```

Should transpile to:

```go
for i := int(0); i < 3; i++ {}
```

You should not need to create scopes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-KxqAo03CbnmKpv4KFfx:bfaufwm) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Go has an initialiser just like C:

```c
for (int i = 0; i < 3; i++) {}
```

Should transpile to:

```go
for i := int(0); i < 3; i++ {}
```

You should not need to create scopes.
</blockquote></details>

If C code( 2 ):
```c
int k = 0;
for (int i = 0, j =0 ; i < 3; i++, k++) {}
for (int i = 0, j =0 ; i < 3; i++, k++) {}
```
After transpile, some like:
```go
int k = 0;
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
int i = 0; // Dublicate of var i
for (int j =0 ; i < 3; func(){i++, k++}()) {}
```
So, that PR solve that like that:
```go
int k = 0;
{ // Add BlockStmt
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
}
{ // Add BlockStmt
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[tests/goto.c, line 19 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/285#-Kxtn2MFzmBOPPuO6IN-:-Kxtn2MFzmBOPPuO6IN0:b-kbogb6) ([raw file](https://github.com/elliotchance/c2go/blob/c3e4633c55a6999afe1364818a2f38a8e933f35b/tests/goto.c#L19)):*
> ```C
>         fail("Parameter i = %d, but expect 1",i);
> 		return
>     }
> ```

Are you adding this as an extra safety feature or did it get in an infinite loop for you?

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-Kxtp6iCqAu1Dx-kLqN_:b7rxqkq) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

If C code( 2 ):
```c
int k = 0;
for (int i = 0, j =0 ; i < 3; i++, k++) {}
for (int i = 0, j =0 ; i < 3; i++, k++) {}
```
After transpile, some like:
```go
int k = 0;
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
int i = 0; // Dublicate of var i
for (int j =0 ; i < 3; func(){i++, k++}()) {}
```
So, that PR solve that like that:
```go
int k = 0;
{ // Add BlockStmt
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
}
{ // Add BlockStmt
int i = 0;
for (int j =0 ; i < 3; func(){i++, k++}()) {}
}
```

</blockquote></details>

It is possible to put multiple variable assignments without needing the scope: https://play.golang.org/p/eAd87PqV2K

I understand that this is more difficult. I'm happy to accept this solution for now if you open a ticket to improve it with the example above. Or just refactor this to put all the variables together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[tests/goto.c, line 19 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/285#-Kxtn2MFzmBOPPuO6IN-:-KxvUJee7Y7IX8kJ9Tj0:b-jwr9so) ([raw file](https://github.com/elliotchance/c2go/blob/c3e4633c55a6999afe1364818a2f38a8e933f35b/tests/goto.c#L19)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Are you adding this as an extra safety feature or did it get in an infinite loop for you?
</blockquote></details>

Yes, right.

---

*[transpiler/branch.go, line 290 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxjRoiOlAKSF6ojgMxz:-KxvUT_1d6Ba6PG1dk83:b-grcm1) ([raw file](https://github.com/elliotchance/c2go/blob/ec4011c69e27d9f107b710b6c4d0024626614ea6/transpiler/branch.go#L290)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It is possible to put multiple variable assignments without needing the scope: https://play.golang.org/p/eAd87PqV2K

I understand that this is more difficult. I'm happy to accept this solution for now if you open a ticket to improve it with the example above. Or just refactor this to put all the variables together.
</blockquote></details>

Yes, you are right. I will open the ticket with your solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxyqEUnSUMxPakKvkMU:-KxyqEUnSUMxPakKvkMV:bea1hww) (no related file):*
Please fix the build error so this can be merged in :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/if.c, line 13 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KyDQk6DE2R8r5QkGcJ9:-KyDQk6DE2R8r5QkGcJA:b-jzsvbg) ([raw file](https://github.com/elliotchance/c2go/blob/f2994ddfad06e8fe6951e47b3847fe77bc9da54a/tests/if.c#L13)):*
> ```C
>     if (x == 1){
>         pass("%s", "x is equal to one");
> 	}
> ```

We still need to check that the logic works when there is no `{}`. You can remove the `{}` or duplicate the existing `if` statements.

---

*[transpiler/transpiler.go, line 368 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KyDRQEYd-MWD0goOjNg:-KyDRQEYd-MWD0goOjNh:b-6tmhed) ([raw file](https://github.com/elliotchance/c2go/blob/f2994ddfad06e8fe6951e47b3847fe77bc9da54a/transpiler/transpiler.go#L368)):*
> ```Go
> 
> // Combine elements to slice
> func combine(stmt goast.Stmt, preStmts, postStmts []goast.Stmt) (stmts []goast.Stmt) {
> ```

This only works for slices of `goast.Stmt` so call it something more specific like `combineStmts`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KxyqEUnSUMxPakKvkMU:-KyFcMAFSMR2mbeBDvxY:b-896fix) (no related file):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please fix the build error so this can be merged in :)
</blockquote></details>

Done.

---

*[tests/if.c, line 13 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KyDQk6DE2R8r5QkGcJ9:-KyFbJlAqdp_l91OwhVe:b-i69yrv) ([raw file](https://github.com/elliotchance/c2go/blob/f2994ddfad06e8fe6951e47b3847fe77bc9da54a/tests/if.c#L13)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

We still need to check that the logic works when there is no `{}`. You can remove the `{}` or duplicate the existing `if` statements.
</blockquote></details>

Done. - add test with `{}`

---

*[transpiler/transpiler.go, line 368 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/285#-KyDRQEYd-MWD0goOjNg:-KyFcCJerywZbKw6iZR7:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f2994ddfad06e8fe6951e47b3847fe77bc9da54a/transpiler/transpiler.go#L368)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This only works for slices of `goast.Stmt` so call it something more specific like `combineStmts`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/285)*

**Pull request merged**
