### PR TITLE
Fixed char *[]. Fixes #263

### LINKED ISSUE #263: char *a[] should transpile to var a [][]byte
```
char *a[] = {"a", "bc", "def"};
```

currently transpiles to: `var arr []string`

should transpiles to: `var arr [][]byte = [][]byte{[]byte("a"), []byte("bc"), []byte("def")}`

test:
```
void test_stringarr_init()
{
    char *a[] = {"a", "bc", "def"};
    is_streq(a[0], "a");
    is_streq(a[1], "bc");
    is_streq(a[2], "def");
}
```

Quoting @elliotchance: "In previous versions I treated char * as a Go string until I realised that wasn't going to work. It looks like there is still one case left over where it is resolving to a string instead of []byte."

### PR DESCRIPTION
**Pull request by yulvil**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/300)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/300)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/300#-KxtiScFM3qQuEdBN1GN:-KxtiScFM3qQuEdBN1GO:beswvfq) (no related file):*
All good except for the merge conflict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/300)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/300)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/300#-Kxtlo8pDcJjX2_IoRxy:-Kxtlo8pDcJjX2_IoRxz:b-3x7mrw) (no related file):*
I resolved the merge conflicts on this branch and another branch but Github makes you resolve it twice, even for squash. In the future i'll only let person that raises the PR resolve the conflicts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/300)*

**Comment by yulvil** [comment]
@elliotchance Thanks for merging. I will resolve the conflicts next time.

**Pull request merged**
