### PR TITLE
Use pointers instead of interface/slice. Fixes #748

### LINKED ISSUE #748: Use of interface/slice instead of pointer interferes in low-level memory manipulation
The following code works as C:
```
#include <stdio.h>
#include <stdlib.h>
#include "tests.h"

typedef unsigned char pcre_uint8;
typedef unsigned int pcre_uint32;
typedef struct pcre_extra {
  unsigned long int flags;        /* Bits for which fields are set */
  void *study_data;               /* Opaque data from pcre_study() */
  unsigned long int match_limit;  /* Maximum number of calls to match() */
  void *callout_data;             /* Data passed back in callouts */
  const unsigned char *tables;    /* Pointer to character tables */
  unsigned long int match_limit_recursion; /* Max recursive calls to match() */
  unsigned char **mark;           /* For passing back a mark pointer */
  void *executable_jit;           /* Contains a pointer to a compiled jit code */
} pcre_extra;
typedef struct pcre_study_data {
  pcre_uint32 size;               /* Total that was malloced */
  pcre_uint32 flags;              /* Private flags */
  pcre_uint8 start_bits[32];      /* Starting char bits */
  pcre_uint32 minlength;          /* Minimum subject length */
} pcre_study_data;

void test_mark()
{
    pcre_extra *extra = NULL;
    pcre_study_data *study;
    pcre_uint8 *markptr;
    void * allocated = malloc(sizeof(pcre_extra) + sizeof(pcre_study_data));
    extra = (pcre_extra *)allocated;
    study = (pcre_study_data *)((char *)extra + sizeof(pcre_extra));
    memset(study->start_bits, 0, 32 * sizeof(pcre_uint8));
    extra->study_data = study;
    study->size = sizeof(pcre_study_data);
    extra->mark = &markptr;
    is_eq(study->size, 44);
    for (int i=0; i<32; i++)
        is_eq(study->start_bits[i], 0);
}

int main()
{
    plan(33);

    test_mark();

    done_testing();
}
```
As expected all `start_bits` are `0`, but when transpiled into Go many of the `start_bits` are `!= 0`.

I think, that since this is very low level manipulation of pointers and memory, that Go's internal representation of interfaces and slices is interfering here.

### PR DESCRIPTION
**Pull request by kamphaus**
Fixes #748

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/754)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 12 of 23 files at r1, 3 of 9 files at r3, 3 of 10 files at r4, 12 of 15 files at r5, 1 of 2 files at r6, 1 of 3 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed, 2 unresolved discussions (waiting on @kamphaus)

---

*[transpiler/binary.go, line 373 at r9](https://reviewable.io/reviews/elliotchance/c2go/754#-LFZngnpEUstD23LLZhY:-LFZngnpEUstD23LLZhZ:b-yjraat) ([raw file](https://github.com/elliotchance/c2go/blob/18316cfd8ee1f43b8ecd1d910168f05d528cbc84/transpiler/binary.go#L373)):*
> ```Go
> 					}
> 				}
> 			}*/
> ```

Did you mean to leave this commented out?

---

*[types/resolve.go, line 327 at r9](https://reviewable.io/reviews/elliotchance/c2go/754#-LFZovMv1uLjHKoUoZCV:-LFZovMv1uLjHKoUoZCW:b-yjraat) ([raw file](https://github.com/elliotchance/c2go/blob/18316cfd8ee1f43b8ecd1d910168f05d528cbc84/types/resolve.go#L327)):*
> ```Go
> 		//if !strings.Contains(t, "noarch.") {
> 		//	prefix = "[]"
> 		//}
> ```

Did you mean to leave this commented out?

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/754)*

**Comment by kamphaus** [comment]
*[transpiler/binary.go, line 373 at r9](https://reviewable.io/reviews/elliotchance/c2go/754#-LFZngnpEUstD23LLZhY:-LFaJyaVBX-ZzR2QpowU:b-eje6iu) ([raw file](https://github.com/elliotchance/c2go/blob/18316cfd8ee1f43b8ecd1d910168f05d528cbc84/transpiler/binary.go#L373)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Did you mean to leave this commented out?
</blockquote></details>

Commented code removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/754)*

**Comment by kamphaus** [comment]
*[types/resolve.go, line 327 at r9](https://reviewable.io/reviews/elliotchance/c2go/754#-LFZovMv1uLjHKoUoZCV:-LFaKD2V1bwD9lpL_cZF:b-eje6iu) ([raw file](https://github.com/elliotchance/c2go/blob/18316cfd8ee1f43b8ecd1d910168f05d528cbc84/types/resolve.go#L327)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Did you mean to leave this commented out?
</blockquote></details>

Commented code removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/754)*

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r10.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/754)*

**Pull request merged**
