### PR TITLE
Compound assign bit-operator with cast complement. Fixes #684 and #685

### LINKED ISSUE #684: Cast to unsigned of a complement overflows
Doing `unsigned int x = ~0x3c;` gives in the transpiled code the compile error `constant -61 overflows uint32`.

### PR DESCRIPTION
**Pull request by kamphaus**
Fixes #684, #685

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/686)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/686)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/elliotchance/c2go/686#-LAozlH66rQGSgjYh4G4:-LAozlH66rQGSgjYh4G5:btedjs3) (no related file):*
This is fine, but there are merge conflicts.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/686)*

**Comment by kamphaus** [comment]
@elliotchance 
Merge conflicts have been resolved.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/686)*

**Pull request merged**
