### PR TITLE
Debug perfomance: Clang

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #349

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/377)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Performance test.
```
 2017-11-29 10:07:40 ⌚  konstantin-VirtualBox in ~/go/bin/sqlite
○ → time c2go transpile sqlite3.c

real	0m5.110s
user	0m8.616s
sys	0m0.964s

 2017-11-29 10:08:07 ⌚  konstantin-VirtualBox in ~/go/bin/sqlite
○ → time c2go transpile sqlite3.c

real	0m3.951s
user	0m7.776s
sys	0m0.752s
```
Saved 20...30% of time

**Comment by Konstantin8105** [comment]
Before:
before
After:
after

**Comment by elliotchance** [comment]
Reviewed 2 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[main.go, line 216 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/377#-L-9ntca80_moZuA_D1A:-L-9ntca80_moZuA_D1B:bwlzmv0) ([raw file](https://github.com/elliotchance/c2go/blob/314be05134309884cc5cba52ce3709fe1f546490/main.go#L216)):*
> ```Go
> 		return fmt.Errorf("Cannot create temp folder: %v", err)
> 	}
> 	defer func() { _ = os.RemoveAll(dir) }() // clean up
> ```

Is this change different from the existing code?

---

*[preprocessor/utils.go, line 19 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/377#-L-9o_izQuYCIhFu4ZEz:-L-9o_izQuYCIhFu4ZF-:b-494bxm) ([raw file](https://github.com/elliotchance/c2go/blob/314be05134309884cc5cba52ce3709fe1f546490/preprocessor/utils.go#L19)):*
> ```Go
> 		return err
> 	}
> 	defer func() { _ = f.Close() }()
> ```

Is this the same as `defer f.Close()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/377)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 216 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/377#-L-9ntca80_moZuA_D1A:-L-BQxVDjdtfMPAD1Hn-:b-ywxhf6) ([raw file](https://github.com/elliotchance/c2go/blob/314be05134309884cc5cba52ce3709fe1f546490/main.go#L216)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this change different from the existing code?
</blockquote></details>

This is identical, but I modify like that for avoid "warning" from go tool - "errcheck".
It is mean - "Ignore error if remove is not success".

---

*[preprocessor/utils.go, line 19 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/377#-L-9o_izQuYCIhFu4ZEz:-L-BRRN3khq3VETGmkBN:b-ywxhf6) ([raw file](https://github.com/elliotchance/c2go/blob/314be05134309884cc5cba52ce3709fe1f546490/preprocessor/utils.go#L19)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this the same as `defer f.Close()`?
</blockquote></details>

This is identical, but I modify like that for avoid "warning" from go tool - "errcheck".
It is mean - "Ignore error if remove is not success".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/377)*

**Comment by Konstantin8105** [comment]
Hold that PR.

**Pull request closed without merging**
