### PR TITLE
Tests for ctype.c

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/318)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/ctype.c, line 70 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB30w6D9EmbQQhC5rV:-KyB30w6D9EmbQQhC5rW:bhzs8ni) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L70)):*
> ```C
>   is_eq(toupper(' '), ' ');
>   is_eq(toupper('\n'), '\n');
>   is_eq(toupper('z'), 'Z');
> ```

I know you didn't add these tests but they are redundant. Thy are duplicates of what the testing matrix above it doing.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyB2oDPeCGk-Spx0RB-:b-mbpvcp) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
> ```C
>   is_eq(counter,5);
>   if (isalnum('*')){ counter ++; }
>   is_eq(counter,5);
> ```

I don't understand why these tests are needed? Is there an issue that is not covered by the testing matrix at the top?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/ctype.c, line 70 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB30w6D9EmbQQhC5rV:-KyBIk_6zPOeMP6GX2F0:b-7gh4yl) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L70)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I know you didn't add these tests but they are redundant. Thy are duplicates of what the testing matrix above it doing.
</blockquote></details>

Yes, now I see that.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyBGHhsnx7Y2b-kcHDA:burajql) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I don't understand why these tests are needed? Is there an issue that is not covered by the testing matrix at the top?
</blockquote></details>

Generally, I want to see - how this function **looks** in output Go code and in my of view - it is not clear, but Ok:
```go
        // this is function isalnum
	if ((linux.CtypeLoc()[0])[('a')] & _ISalnum) != 0 {
```

Yes, you are right. That functions is checked in matrix. That PR can be  closed without merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyD0bQAXPd-0T5820yJ:b-kvwflx) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Generally, I want to see - how this function **looks** in output Go code and in my of view - it is not clear, but Ok:
```go
        // this is function isalnum
	if ((linux.CtypeLoc()[0])[('a')] & _ISalnum) != 0 {
```

Yes, you are right. That functions is checked in matrix. That PR can be  closed without merge.
</blockquote></details>

Since you have this PR you can clean up the tests so only the test matrix at the top remains.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyFescN4hTqKxF3aWtX:b-ow7pkg) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Since you have this PR you can clean up the tests so only the test matrix at the top remains.
</blockquote></details>

Like I understood, that test is clean before my PR. 
If you mean some issue for that test, then please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyIScixKj5a1ZDg5omp:b-8r8leu) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Like I understood, that test is clean before my PR. 
If you mean some issue for that test, then please clarify.
</blockquote></details>

This file only needs to contain the matrix tests (the rest can be removed):

```c
int main()
{
  plan(112);
 
  //              . Lower alpha (a)
  //              |  . Upper alpha (B)
  //              |  |  . Digit (0)
  //              |  |  |  . Punctuation (*)
  //              |  |  |  |  . NULL
  //              |  |  |  |  |  . Space
  //              |  |  |  |  |  |  . New line
  //              |  |  |  |  |  |  |  . Non-hex digit (z)
  //              v  v  v  v  v  v  v  v
  _CTYPE(isalnum, T, T, T, F, F, F, F, T);
  _CTYPE(isalpha, T, T, F, F, F, F, F, T);
  _CTYPE(iscntrl, F, F, F, F, T, F, T, F);
  _CTYPE(isdigit, F, F, T, F, F, F, F, F);
  _CTYPE(isgraph, T, T, T, T, F, F, F, T);
  _CTYPE(islower, T, F, F, F, F, F, F, T);
  _CTYPE(isprint, T, T, T, T, F, T, F, T);
  _CTYPE(ispunct, F, F, F, T, F, F, F, F);
  _CTYPE(isspace, F, F, F, F, F, T, T, F);
  _CTYPE(isupper, F, T, F, F, F, F, F, F);
  CTYPE(isxdigit, T, T, T, F, F, F, F, F);
 
  done_testing();
}
```

You will need to adjust the `plan()`.

Is there is a bug found with a value that is not covered in the above matrix we should add new columns and not new tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyL6l0X1bu3ATdmDCa9:bg2kdcg) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This file only needs to contain the matrix tests (the rest can be removed):

```c
int main()
{
  plan(112);
 
  //              . Lower alpha (a)
  //              |  . Upper alpha (B)
  //              |  |  . Digit (0)
  //              |  |  |  . Punctuation (*)
  //              |  |  |  |  . NULL
  //              |  |  |  |  |  . Space
  //              |  |  |  |  |  |  . New line
  //              |  |  |  |  |  |  |  . Non-hex digit (z)
  //              v  v  v  v  v  v  v  v
  _CTYPE(isalnum, T, T, T, F, F, F, F, T);
  _CTYPE(isalpha, T, T, F, F, F, F, F, T);
  _CTYPE(iscntrl, F, F, F, F, T, F, T, F);
  _CTYPE(isdigit, F, F, T, F, F, F, F, F);
  _CTYPE(isgraph, T, T, T, T, F, F, F, T);
  _CTYPE(islower, T, F, F, F, F, F, F, T);
  _CTYPE(isprint, T, T, T, T, F, T, F, T);
  _CTYPE(ispunct, F, F, F, T, F, F, F, F);
  _CTYPE(isspace, F, F, F, F, F, T, T, F);
  _CTYPE(isupper, F, T, F, F, F, F, F, F);
  CTYPE(isxdigit, T, T, T, F, F, F, F, F);
 
  done_testing();
}
```

You will need to adjust the `plan()`.

Is there is a bug found with a value that is not covered in the above matrix we should add new columns and not new tests.
</blockquote></details>

Like I understood functions `tolower` and `toupper` is not return `bool`. So, matrix is not used for that functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyNgFeWz2mnNEAkXGac:basnks1) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Like I understood functions `tolower` and `toupper` is not return `bool`. So, matrix is not used for that functions.
</blockquote></details>

`bool` does not exist in C. The `T` and `F` really just map to `1` and `0`. `toupper` returns the same int as all the other functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyUz7ILR6RrnNYaVxnq:bkzq8c8) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`bool` does not exist in C. The `T` and `F` really just map to `1` and `0`. `toupper` returns the same int as all the other functions.
</blockquote></details>

toupper('a') ---> return ----> 'A', not `1` or `0`. I don't understood.
Tests for `toupper` is look nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyXtvO3OCwxfPSSMKNJ:b-sp5u6c) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

toupper('a') ---> return ----> 'A', not `1` or `0`. I don't understood.
Tests for `toupper` is look nice.
</blockquote></details>

Ah yes sorry, You are right. The `toupper` and `tolower` tests must stay. However, I don't understand what these new tests provide?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ctype.c, line 94 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/318#-KyB2oDObV7ingvyuwR8:-KyZks9wtddQNIxoVGJu:b-nmmdi8) ([raw file](https://github.com/elliotchance/c2go/blob/b11ebfc451ab44dabf79bf01da0fa4f4d94e454e/tests/ctype.c#L94)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Ah yes sorry, You are right. The `toupper` and `tolower` tests must stay. However, I don't understand what these new tests provide?
</blockquote></details>

I am agree wih you. This is minor changes and don't test something new. I close that PR. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/318)*

**Pull request closed without merging**
