### PR TITLE
Cast bool to any int type. Fixes #352

### LINKED ISSUE #352: Create generic solution for casting bool to int*
main.c
```
int main() {
    char i1 = (1 == 2);
    short i2 = (1 == 2);
    int i3 = (1 == 2);
    long i4 = (1 == 2);
    long long i5 = (1 == 2);
    return (i1==0) && (i2==0) && (i3==0) && (i4==0) && (i5==0);
}
```

Current go output:
```
package main

import "os"
import "github.com/elliotchance/c2go/noarch"

type __int128_t int64
type __uint128_t uint64
type __builtin_ms_va_list []byte

func main() {
        __init()
        var i1 byte = noarch.BoolToByte((1 == 2))
        var i2 int16 = noarch.BoolToInt16((1 == 2))
        var i3 int = noarch.BoolToInt((1 == 2))
        var i4 int32 = noarch.BoolToInt32((1 == 2))
        var i5 int64 = noarch.BoolToInt64((1 == 2))
        os.Exit(noarch.BoolToInt((i1 == byte(0)) && (i2 == int16(0)) && (i3 == 0) && (i4 == int32(0)) && (i5 == int64(0))))
}
func __init() {
}
```

go build main.go
```
# command-line-arguments
./main.go:14:16: undefined: noarch.BoolToByte
./main.go:15:17: undefined: noarch.BoolToInt16
./main.go:17:17: undefined: noarch.BoolToInt32
./main.go:18:17: undefined: noarch.BoolToInt64
```

proposed go code
```
package main

import "os"

type __int128_t int64
type __uint128_t uint64
type __builtin_ms_va_list []byte

func main() {
        __init()
        var i1 byte = byte(map[bool]int{false: 0, true: 1}[(1 == 2)])
        var i2 int16 = int16(map[bool]int{false: 0, true: 1}[(1 == 2)])
        var i3 int = map[bool]int{false: 0, true: 1}[(1 == 2)]
        var i4 int32 = int32(map[bool]int{false: 0, true: 1}[(1 == 2)])
        var i5 int64 = int64(map[bool]int{false: 0, true: 1}[(1 == 2)])
        os.Exit(map[bool]int{false: 0, true: 1}[(i1 == byte(0)) && (i2 == int16(0)) && (i3 == 0) && (i4 == int32(0)) && (i5 == int64(0))])
}
func __init() {
}
```

### PR DESCRIPTION
**Pull request by yulvil**
For #352

This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/353)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 186 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/353#-Kz1G1K5RYdMSa2SKdK5:-Kz1G1K5RYdMSa2SKdK6:b-70wdw6) ([raw file](https://github.com/elliotchance/c2go/blob/22146cc277525aeecc8d3dfcad4f9f71e13f8365/types/cast.go#L186)):*
> ```Go
> 		}
> 		if fromType == "bool" && toType == v {
> 			e := util.NewGoExpr(`map[bool]int{false: 0, true: 1}[false]`)
> ```

This looks interesting. But I don't understand what it is doing here. To me it just looks like a dance way to write `0`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Comment by yulvil** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 186 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/353#-Kz1G1K5RYdMSa2SKdK5:-Kz1KV1iyjyPE9PRyYhV:b7ht18n) ([raw file](https://github.com/elliotchance/c2go/blob/22146cc277525aeecc8d3dfcad4f9f71e13f8365/types/cast.go#L186)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This looks interesting. But I don't understand what it is doing here. To me it just looks like a dance way to write `0`?
</blockquote></details>

I create the go AST tree using `[false]`, but the line right after I replace that `[false]` with `[expr]`

This way it will pick 0 or 1 based on the result of the boolean expression.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Comment by yulvil** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 186 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/353#-Kz1G1K5RYdMSa2SKdK5:-Kz1LQ3FPMHeG_kK3Bxc:bsqc4ds) ([raw file](https://github.com/elliotchance/c2go/blob/22146cc277525aeecc8d3dfcad4f9f71e13f8365/types/cast.go#L186)):*
<details><summary><i>Previously, yulvil wrote…</i></summary><blockquote>

I create the go AST tree using `[false]`, but the line right after I replace that `[false]` with `[expr]`

This way it will pick 0 or 1 based on the result of the boolean expression.
</blockquote></details>

We could put that map[bool]int as a global variable instead. Then we could reference it like `b2i[expr]`. Maybe as a second step?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 186 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/353#-Kz1G1K5RYdMSa2SKdK5:-Kz1yWeZCAGOMyhmjByP:b-pinbba) ([raw file](https://github.com/elliotchance/c2go/blob/22146cc277525aeecc8d3dfcad4f9f71e13f8365/types/cast.go#L186)):*
<details><summary><i>Previously, yulvil wrote…</i></summary><blockquote>

We could put that map[bool]int as a global variable instead. Then we could reference it like `b2i[expr]`. Maybe as a second step?
</blockquote></details>

I'm fine with the syntax, but I didn't realise the `false` gets replaced later. Please add a comment explaining that the `false` may not always remain so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Comment by yulvil** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 186 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/353#-Kz1G1K5RYdMSa2SKdK5:-Kz4CidaWSDmZFMML6on:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/22146cc277525aeecc8d3dfcad4f9f71e13f8365/types/cast.go#L186)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm fine with the syntax, but I didn't realise the `false` gets replaced later. Please add a comment explaining that the `false` may not always remain so.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/353)*

**Pull request merged**
