### PR TITLE
unistd implementation. Fixes #587

### LINKED ISSUE #587: unistd.h
Add functions:
* getopt
* optarg

Link with documentation:
- http://gel.sourceforge.net/examples/unistd_8h-source.php
- http://unix.superglobalmegacorp.com/Net2/newsrc/sys/unistd.h.html
- https://code.woboq.org/qt5/include/bits/getopt_core.h.html

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #587

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/588)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/588)*

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[noarch/unistd.go, line 40 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/588#-L3uuyNGRDWniP9BBZtZ:-L3uuyNHxJe8TY479APZ:bagcz5y) ([raw file](https://github.com/elliotchance/c2go/blob/e0333507978640c14214c953d0acb328698c3707/noarch/unistd.go#L40)):*
> ```Go
> // directly from the arguments received by main.
> func Getopt(argc int, argv [][]byte, options []byte) (out int) {
> 	// TODO: add algorithm
> ```

Please create a separate issue for this and put the URL in the comment.

---

*[program/variable_difinition.go, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/588#-L3uv3zLCDcv4eRmvib_:-L3uv3zLCDcv4eRmviba:bb2l6el) ([raw file](https://github.com/elliotchance/c2go/blob/e0333507978640c14214c953d0acb328698c3707/program/variable_difinition.go#L1)):*
> ```Go
> package program
> ```

Rename the file to `variable_definition.go`

---

*[program/variable_difinition.go, line 68 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/588#-L3uvPOfWwlnrMfytQb3:-L3uvPOfWwlnrMfytQb4:b7kpdn6) ([raw file](https://github.com/elliotchance/c2go/blob/e0333507978640c14214c953d0acb328698c3707/program/variable_difinition.go#L68)):*
> ```Go
> }
> 
> // GetBuiltInVariableDefinition - return true and var difinition if that
> ```

"definition"

---

*[tests/unistd.c, line 27 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/588#-L3uvhGKnSPVzpT1RohF:-L3uvhGKnSPVzpT1RohG:b-1lsddp) ([raw file](https://github.com/elliotchance/c2go/blob/e0333507978640c14214c953d0acb328698c3707/tests/unistd.c#L27)):*
> ```C
> 	done_testing();
> 
> 	// TODO : add algorithm https://github.com/elliotchance/c2go/issues/587 
> ```

Should we leave this PR until these tests are working, otherwise this PR does not bring new features.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/588)*

**Comment by elliotchance** [comment]
Please fix the merge conflicts, then I will review

---

Reviewed 2 of 9 files at r3.
Review status: 3 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/588#-:-L42wTkSxHfm5lvPc-i9:b-h1nhoy)*

**Pull request closed without merging**
