### PR TITLE
Add go format checking on travis

### PR DESCRIPTION
**Pull request by pravj**
This pull request add a source code format checking using `gofmt`.

It customises the build's `script` section and does a format check before running the test cases.

If the source code is not formatted according to the standard, it will fail the build suggesting the prospective changes.

```bash
Go code is not properly formatted. Use 'gofmt'.
diff main.go gofmt/main.go
--- /var/folders/kr/z6l_jmvs0916l5yhzzkgrysm0000gn/T/gofmt153062035	2017-04-21 12:37:03.000000000 +0530
+++ /var/folders/kr/z6l_jmvs0916l5yhzzkgrysm0000gn/T/gofmt346248406	2017-04-21 12:37:03.000000000 +0530
@@ -1,4 +1,4 @@
-package 	main
+package main
 
 import (
 	"flag"
```

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/52)

### CODE REVIEW

**Comment by pravj** [comment]
This will be a fix for #40 (Add "go fmt" to travis).

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/52)*

**Comment by elliotchance** [comment]
Awesome, thanks @pravj !

**Comment by sbinet** [comment]
apologies for coming late to the party.

instead of adding this to Travis-CI, I prefer to create a `TestGofmt(t *testing.T)` test (so people actually running tests will see it *before* bugging Travis).

see:
 https://github.com/go-hep/hep/commit/0b78c2931dc9c273128532e223b23b0cc4f093ad

**Comment by elliotchance** [comment]
@sbinet - I like that ides.

One thing that is bugging me is we are mixing integration and unit tests with `go test`. I know there is a `-run` condition, but I can't find an easy way to exclude or run only the tests that *don't* match a regex?

**Comment by sbinet** [comment]
a "simple" workaround is to prefix all unit tests with `Unit` and all integration tests with `Integ`.

ie: 
`TestUnitFoo(t *testing.T)`
`TestIntegFoo(t *testing.T)`

**Comment by bongo227** [comment]
The standard library makes unit tests use [short mode](https://golang.org/pkg/testing/#Short), so to run all unit tests use `go test -short`

**Pull request merged**
