### PR TITLE
Struct correction for InitArray

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/642)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Amount of warning is change from 18000 to 4500. Nice

**Comment by Konstantin8105** [comment]
Amount of warning is change from 4500 to 2500. Nice X2

**Comment by elliotchance** [comment]
That's awesome that so many of the warnings were reduced! Please fix the merge conflicts so I can finish review.

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/642#-:-L7MNqARm3nDiLeOdOXE:b-q2n543)*

**Comment by elliotchance** [comment]
There are merge conflicts and it looks like these changes are halve related to the previous PR, do you want to treat it as one larger change?

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/642#-:-L7vmgdcpdLhTFS1w-bu:b-1f2rvj)*

**Comment by Konstantin8105** [comment]
Move to branch01

**Pull request closed without merging**
