### PR TITLE
switch case order and fallthrough. Fixes #661

### LINKED ISSUE #211: Nested case statements
In the sqlite3 source there is at least one example where case statements are nested. I'm sure this is possible due to the correct chain of `goto`s. But it's also valid in C and not in Go.

Here is an example:

```c
case OP_ReopenIdx: {
  int nField;
  KeyInfo *pKeyInfo;
  int p2;
  int iDb;
  int wrFlag;
  Btree *pX;
  VdbeCursor *pCur;
  Db *pDb;

  assert( pOp->p5==0 || pOp->p5==OPFLAG_SEEKEQ );
  assert( pOp->p4type==P4_KEYINFO );
  pCur = p->apCsr[pOp->p1];
  if( pCur && pCur->pgnoRoot==(u32)pOp->p2 ){
    assert( pCur->iDb==pOp->p3 );      /* Guaranteed by the code generator */
    goto open_cursor_set_hints;
  }
  /* If the cursor is not currently open or is open on a different
  ** index, then fall through into OP_OpenRead to force a reopen */
case OP_OpenRead:
case OP_OpenWrite:

  assert( pOp->opcode==OP_OpenWrite || pOp->p5==0 || pOp->p5==OPFLAG_SEEKEQ );
  assert( p->bIsReader );
  assert( pOp->opcode==OP_OpenRead || pOp->opcode==OP_ReopenIdx
          || p->readOnly==0 );

  if( p->expired ){
    rc = SQLITE_ABORT_ROLLBACK;
    goto abort_due_to_error;
  }
```

### LINKED ISSUE #661: Switch empty case fallthrough is transpiled incorrectly
Transpiling empty switch cases with fallthrough, the resulting go code might be out of order and incorrect.

### PR DESCRIPTION
**Pull request by kamphaus**
Fixes #661 
Fixes #211

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/662)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/code_quality/for.expected.c, line 10 at r1](https://beta.reviewable.io/reviews/elliotchance/c2go/662#-L9Hzxod85lPA0-Kl7qi:-L9Hzxod85lPA0-Kl7qj:b1eearz) ([raw file](https://github.com/elliotchance/c2go/blob/3e1c1012910f0a145babfe207e00ed0280bbfef3/tests/code_quality/for.expected.c#L10)):*
> ```C
> package code_quality
> 
> // f1 - transpiled function from  /go/src/github.com/elliotchance/c2go/tests/code_quality/for.c:1
> ```

Why did you need to change these paths and version above for the four files? I thought @Konstantin8105 originally wrote the tests to be resilient against this...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/662)*

**Comment by kamphaus** [comment]
*[tests/code_quality/for.expected.c, line 10 at r1](https://beta.reviewable.io/reviews/elliotchance/c2go/662#-L9Hzxod85lPA0-Kl7qi:-L9JWm-s-fXuPxXmGsDX:b3khfqp) ([raw file](https://github.com/elliotchance/c2go/blob/3e1c1012910f0a145babfe207e00ed0280bbfef3/tests/code_quality/for.expected.c#L10)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why did you need to change these paths and version above for the four files? I thought @Konstantin8105 originally wrote the tests to be resilient against this...
</blockquote></details>

The `tests/code_quality/*.expected.c` files are the transpilation results for `tests/code_quality/*.c` and are generated by `tests/code_quality/generate.sh`.
I guess that the c2go version used to initially generate these (`v0.21.0 Zinc 2018-01-11`) output relative paths, while the newer version (`v0.21.16 Zinc 2018-04-02`) uses absolute paths.

Anyway the test for these files (`main_test.go:TestCodeQuality()`) strips all comments and whitespace before comparison, so it's fine.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/662)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/code_quality/for.expected.c, line 10 at r1](https://beta.reviewable.io/reviews/elliotchance/c2go/662#-L9Hzxod85lPA0-Kl7qi:-L9Ji3LtEnpcDVE-wgMt:b-y32ec9) ([raw file](https://github.com/elliotchance/c2go/blob/3e1c1012910f0a145babfe207e00ed0280bbfef3/tests/code_quality/for.expected.c#L10)):*
<details><summary><i>Previously, kamphaus wrote…</i></summary><blockquote>

The `tests/code_quality/*.expected.c` files are the transpilation results for `tests/code_quality/*.c` and are generated by `tests/code_quality/generate.sh`.
I guess that the c2go version used to initially generate these (`v0.21.0 Zinc 2018-01-11`) output relative paths, while the newer version (`v0.21.16 Zinc 2018-04-02`) uses absolute paths.

Anyway the test for these files (`main_test.go:TestCodeQuality()`) strips all comments and whitespace before comparison, so it's fine.
</blockquote></details>

If comments are stripped, can you please remove your changes so the next person doesn't get the idea that the changes are important for tests passing, or updates the comments again.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/662)*

**Comment by kamphaus** [comment]
*[tests/code_quality/for.expected.c, line 10 at r1](https://beta.reviewable.io/reviews/elliotchance/c2go/662#-L9Hzxod85lPA0-Kl7qi:-L9KPZq48ESWCpdsYx3l:b-wd1rns) ([raw file](https://github.com/elliotchance/c2go/blob/3e1c1012910f0a145babfe207e00ed0280bbfef3/tests/code_quality/for.expected.c#L10)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

If comments are stripped, can you please remove your changes so the next person doesn't get the idea that the changes are important for tests passing, or updates the comments again.
</blockquote></details>

I have changed the generation script to normalized the comments to `tests/code_quality/...`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/662)*

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/662)*

**Comment by kamphaus** [comment]
@elliotchance Did you make a typo when you renamed this PR?
It fixes #211, not #221.

**Comment by elliotchance** [comment]
Ah, yes sorry. I will fix that.

**Pull request merged**
