### PR TITLE
time.h: time() and ctime()

### PR DESCRIPTION
**Pull request by yulvil**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/253)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/time.c, line 18 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqksybS-8wPtHV6Rn2:-KwqksycOO48f_mUGqgS:b-fqwqmm) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L18)):*
> ```C
> 
>     now = time(&tloc);
>     is_true(now == tloc);
> ```

Please use `is_eq(now, tloc)` instead. This will show the value of both if it fails.

---

*[tests/time.c, line 20 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqlB9Y6xO8Eqm01BZk:-KwqlB9Y6xO8Eqm01BZl:b24b3xh) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L20)):*
> ```C
>     is_true(now == tloc);
> 
>     pass("%s", "time");
> ```

This is unesseary because there is an assertions above. However, it would be a good idea to also check: `is_not_eq(now, 0)`

---

*[tests/time.c, line 30 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqlgnQqtsTFsbwYxwS:-KwqlgnQqtsTFsbwYxwT:b-46oyjl) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L30)):*
> ```C
>     time_t now = 946684798;
>     s = ctime(&now);
>     printf("%s", s);
> ```

Avoid `printf` as it will break the TAP output. You can use `is_streq`: https://github.com/elliotchance/c2go/blob/master/tests/tests.h#L198

---

*[tests/time.c, line 32 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-Kwqlu2dA7B7eg_7X99X:-Kwqlu2dA7B7eg_7X99Y:bpuxii4) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L32)):*
> ```C
>     printf("%s", s);
> 
>     pass("%s", "ctime");
> ```

Like the previous `pass` this doesn't actually check anything and can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/253)*

**Comment by elliotchance** [comment]
Thanks for putting in the PR. I started to review it as you were still making changes :)

**Comment by yulvil** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/time.c, line 18 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqksybS-8wPtHV6Rn2:-Kwr9Hbt063xHwHutDvD:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L18)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please use `is_eq(now, tloc)` instead. This will show the value of both if it fails.
</blockquote></details>

Done.

---

*[tests/time.c, line 20 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqlB9Y6xO8Eqm01BZk:-Kwr9G9-rmGUocVgP80H:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L20)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is unesseary because there is an assertions above. However, it would be a good idea to also check: `is_not_eq(now, 0)`
</blockquote></details>

Done.

---

*[tests/time.c, line 30 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-KwqlgnQqtsTFsbwYxwS:-Kwr9N_g-z-SZEQ7lE4V:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L30)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Avoid `printf` as it will break the TAP output. You can use `is_streq`: https://github.com/elliotchance/c2go/blob/master/tests/tests.h#L198
</blockquote></details>

Done.

---

*[tests/time.c, line 32 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/253#-Kwqlu2dA7B7eg_7X99X:-Kwr9NooQBk4PBglIhQt:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/931470febdbee72c1f4baba7e84c01f2aa19b1b3/tests/time.c#L32)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Like the previous `pass` this doesn't actually check anything and can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/253)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/253)*

**Comment by yulvil** [comment]
@elliotchance Thank you for reviewing. I am having a hard time troubleshooting the OS X error; I do not have a machine at hand.

I tried to compile similar code in Travis. The build succeeded.
* https://github.com/yulvil/clang/
* https://travis-ci.org/yulvil/clang/builds/290531110

Is it possible to add debug for the Travis/OS X build? Any help appreciated.

**Comment by elliotchance** [comment]
When I run it on my Mac:

```
Elliots-MacBook-Pro-3:c2go elliot$ clang tests/time.c
Elliots-MacBook-Pro-3:c2go elliot$ ./a.out
1..6
# time
1 ok - now != 0
2 ok - now != 0
3 ok - now == tloc
# ctime
Segmentation fault: 11
```

It looks like `ctime` expects that the parameter not be `NULL`.

When I removed https://github.com/elliotchance/c2go/pull/253/files#diff-c3bb064a4d264cc6f2d46ab300725b61R25 I did not get the segfault.

Even the same compiler on different operating systems can give different results. You can remove line 25 and 26 and your build should pass.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/253)*

**Comment by elliotchance** [comment]
Awesome - thanks for the PR! 👍

**Comment by yulvil** [comment]
@elliotchance Thank you for merging!

**Pull request merged**
