### PR TITLE
Redesign of union implementation. Fix #533, #574, #580

### LINKED ISSUE #533: Struct inside union
Test:
```c

union STRS{
	double d;
	struct {
		double d;
	} T;
};

void struct_inside_union()
{
	union STRS s;
	s.T.d = 10.0;
	is_true(s.d != 0);
}
```

### LINKED ISSUE #574: Access to value inside array inside union inside struct
In C:
```c
typedef sqlite3_uint64 u64;


typedef struct SHA3Context SHA3Context;
struct SHA3Context {
  union {
    u64 s[25];                /* Keccak state. 5x5 lines of 64 bits each */
    unsigned char x[1600];    /* ... or 1600 bytes */
  } u;
  unsigned nRate;        /* Bytes of input accepted per Keccak iteration */
  unsigned nLoaded;      /* Input bytes loaded into u.x[] so far this cycle */
  unsigned ixMask;       /* Insert next input into u.x[nLoaded^ixMask]. */
};

/*
** A single step of the Keccak mixing function for a 1600-bit state
*/
static void KeccakF1600Step(SHA3Context *p){
  int i;
  u64 B0, B1, B2, B3, B4;
  u64 C0, C1, C2, C3, C4;
  u64 D0, D1, D2, D3, D4;
  static const u64 RC[] = {
    0x0000000000000001ULL,  0x0000000000008082ULL,
    0x800000000000808aULL,  0x8000000080008000ULL,
    0x000000000000808bULL,  0x0000000080000001ULL,
    0x8000000080008081ULL,  0x8000000000008009ULL,
    0x000000000000008aULL,  0x0000000000000088ULL,
    0x0000000080008009ULL,  0x000000008000000aULL,
    0x000000008000808bULL,  0x800000000000008bULL,
    0x8000000000008089ULL,  0x8000000000008003ULL,
    0x8000000000008002ULL,  0x8000000000000080ULL,
    0x000000000000800aULL,  0x800000008000000aULL,
    0x8000000080008081ULL,  0x8000000000008080ULL,
    0x0000000080000001ULL,  0x8000000080008008ULL
  };
# define A00 (p->u.s[0])
# define A01 (p->u.s[1])
# define A02 (p->u.s[2])
# define A03 (p->u.s[3])
# define A04 (p->u.s[4])
# define A10 (p->u.s[5])
# define A11 (p->u.s[6])
# define A12 (p->u.s[7])
# define A13 (p->u.s[8])
# define A14 (p->u.s[9])
# define A20 (p->u.s[10])
# define A21 (p->u.s[11])
# define A22 (p->u.s[12])
# define A23 (p->u.s[13])
# define A24 (p->u.s[14])
# define A30 (p->u.s[15])
# define A31 (p->u.s[16])
# define A32 (p->u.s[17])
# define A33 (p->u.s[18])
# define A34 (p->u.s[19])
# define A40 (p->u.s[20])
# define A41 (p->u.s[21])
# define A42 (p->u.s[22])
# define A43 (p->u.s[23])
# define A44 (p->u.s[24])
# define ROL64(a,x) ((a<<x)|(a>>(64-x)))

  for(i=0; i<24; i+=4){
    C0 = A00^A10^A20^A30^A40;
    C1 = A01^A11^A21^A31^A41; // << ----- HERE
```
In Go:
```go
func KeccakF1600Step(p []SHA3Context) {
	var i int
	var B0 uint64
	var B1 uint64
	var B2 uint64
	var B3 uint64
	var B4 uint64
	var C0 uint64
	var C1 uint64
	var C2 uint64
	var C3 uint64
	var C4 uint64
	var D0 uint64
	var D1 uint64
	var D2 uint64
	var D3 uint64
	var D4 uint64
	var RC []uint64 = []uint64{1, 32898, 9223372036854808714, 9223372039002292224, 32907, 2147483649, 9223372039002292353, 9223372036854808585, 138, 136, 2147516425, 2147483658, 2147516555, 9223372036854775947, 9223372036854808713, 9223372036854808579, 9223372036854808578, 9223372036854775936, 32778, 9223372039002259466, 9223372039002292353, 9223372036854808704, 2147483649, 9223372039002292232}
	{
		for i = 0; i < 24; i += 4 {
			C0 = (.GetS()[0])^(.GetS()[5])^(.GetS()[10])^(.GetS()[15])^(.GetS()[20])
			C1 = (.GetS()[1])^(.GetS()[6])^(.GetS()[11])^(.GetS()[16])^(.GetS()[21]) /// <<- WRONG .GetS() without variable
```

### LINKED ISSUE #580: New design of union implementation
See: https://stackoverflow.com/questions/31557539/golang-how-to-simulate-union-type-efficiently
```golang
func test3() (total int64) {
    type A struct {
        t int32
        u []byte
    }   

    a := [...]A{{1, make([]byte, 8)}, {2, make([]byte, 8)}}
    *(*int32)(unsafe.Pointer(&a[0].u)) = 100    // LOOK HERE
    *(*int16)(unsafe.Pointer(&a[1].u)) = 3    // LOOK HERE

    for i := 0; i < 5000000000; i++ {
        p := &a[i%2]
        switch p.t {
        case 1:
            total += int64(*(*int32)(unsafe.Pointer(&p.u)))   // LOOK HERE
        case 2:
            total += int64(*(*int16)(unsafe.Pointer(&p.u)))   // LOOK HERE
        }   
    }   
    return
}
```
Need specific implementation for union with pointer for avoid GC removing.

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #580 
Close #533
Close #574

This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/611)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
NOT READY FOR REVIEW.

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by elliotchance** [comment]
Reviewed 3 of 11 files at r1, 5 of 6 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[transpiler/call.go, line 46 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mVv_Y2hLdDkAZUU7N:-L4mVv_ZTwMe_3vKOGdY:b-urcuzr) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/call.go#L46)):*
> ```Go
> 	case *ast.MemberExpr:
> 		if isUnionMemberExpr(p, fc) {
> 			lhs, _, _, _, _ := transpileToExpr(fc, p, false)
> ```

What if this returns an error (it cannot transpile the left side)?

---

*[transpiler/call.go, line 50 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mW5pbeyJQFBUCMoBO:-L4mW5pbeyJQFBUCMoBP:bsg1i8) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/call.go#L50)):*
> ```Go
> 			err := printer.Fprint(&buf, token.NewFileSet(), lhs)
> 			if err != nil {
> 				panic(err)
> ```

Return the error instead. We want to always produce some output, even if it's incorrect.

---

*[transpiler/union.go, line 83 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mWc8cNP_Bx-gVbkmU:-L4mWc8cNP_Bx-gVbkmV:b-ksqwg4) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/union.go#L83)):*
> ```Go
> 	err = tmpl.Execute(&source, un)
> 	if err != nil {
> 		panic(err)
> ```

A panic seems appropriate here, but I'd still rather return an error. If someone finds a way to break the Go template code it would be better to output some broken Go code that they can raise an issue on than no output at all.

---

*[transpiler/union.go, line 90 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mWt-AqqdnzTVXj-2Q:-L4mWt-AqqdnzTVXj-2R:brhumzt) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/union.go#L90)):*
> ```Go
> 	f, err := parser.ParseFile(fset, "", source.String(), 0)
> 	if err != nil {
> 		panic(err)
> ```

Same here.

---

*[util/util.go, line 58 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mX6nQ1CmUXZnaAPLh:-L4mX6nQ1CmUXZnaAPLi:b75x6ft) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/util/util.go#L58)):*
> ```Go
> 
> 	// NotFunc(int)()
> 	field = strings.Replace(field, "(", "I", -1)
> ```

Why replace with `I`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[transpiler/call.go, line 46 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mVv_Y2hLdDkAZUU7N:-L4o9RMbYx8WwJirNpC0:b-h14qei) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/call.go#L46)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

What if this returns an error (it cannot transpile the left side)?
</blockquote></details>

Now, I add error handling.

---

*[transpiler/call.go, line 50 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mW5pbeyJQFBUCMoBO:-L4oBLuUrHyFz8fIYhCk:b-h14qei) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/call.go#L50)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Return the error instead. We want to always produce some output, even if it's incorrect.
</blockquote></details>

Now, I add error handling.

---

*[transpiler/union.go, line 83 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mWc8cNP_Bx-gVbkmU:-L4oE9tZKP6tW99PU1k_:b-330vz3) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/union.go#L83)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

A panic seems appropriate here, but I'd still rather return an error. If someone finds a way to break the Go template code it would be better to output some broken Go code that they can raise an issue on than no output at all.
</blockquote></details>

add error handling

---

*[transpiler/union.go, line 90 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mWt-AqqdnzTVXj-2Q:-L4oEH9JauVq-4k-gmYE:b-oknh87) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/transpiler/union.go#L90)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

add error handling

---

*[util/util.go, line 58 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mX6nQ1CmUXZnaAPLh:-L4oFawFTNMH_SRZeZEp:bnu3hw2) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/util/util.go#L58)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why replace with `I`?
</blockquote></details>

This is workaround now. If we remove that replace, then we have:
```
Transpiling shell.c...
Transpiling sqlite3.c...
panic: invalid identity: 'NotFunc(int)' [recovered]
	panic: bad type: 'noarch.NotFunc(int)()'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc42f5b78c0, 0x15)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x63be20, 0xc4307335b0)
	/home/konstantin/Program/go/src/runtime/panic.go:489 +0x2cf
github.com/elliotchance/c2go/util.NewIdent(0xc42f5b78c7, 0xc, 0xc42f5b78e0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:259 +0x260
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc42f5b78c0, 0x13, 0xc42f5b78c0, 0x15)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:84 +0xf60
github.com/elliotchance/c2go/util.typeToExpr(0xc42f5b78c0, 0x15, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.NewCallExpr(0xc42f5b78c0, 0x15, 0xc430733560, 0x1, 0x1, 0xc42f5b78c0)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Comment by Konstantin8105** [comment]
That PR change amount of `gometalinter` warnings from 140000 to 800.
Nice.

**Comment by elliotchance** [comment]
Reviewed 5 of 8 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[types/resolve.go, line 180 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L5Bdk0-JOo-YXwPjMKu:-L5Bdk0-JOo-YXwPjMKv:bwlxko9) ([raw file](https://github.com/elliotchance/c2go/blob/a5b4ed07757e9b2fddd22543aefdb0b3e46afe65/types/resolve.go#L180)):*
> ```Go
> 	}
> 
> 	// FIXME: I have no idea, how to solve.
> ```

Please raise an issue for this and put the URL in the comment.

---

*[util/util.go, line 58 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mX6nQ1CmUXZnaAPLh:-L5Bdyh4QkUbHMJSI1_O:b-3wdtnf) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/util/util.go#L58)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

This is workaround now. If we remove that replace, then we have:
```
Transpiling shell.c...
Transpiling sqlite3.c...
panic: invalid identity: 'NotFunc(int)' [recovered]
	panic: bad type: 'noarch.NotFunc(int)()'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc42f5b78c0, 0x15)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x63be20, 0xc4307335b0)
	/home/konstantin/Program/go/src/runtime/panic.go:489 +0x2cf
github.com/elliotchance/c2go/util.NewIdent(0xc42f5b78c7, 0xc, 0xc42f5b78e0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:259 +0x260
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc42f5b78c0, 0x13, 0xc42f5b78c0, 0x15)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:84 +0xf60
github.com/elliotchance/c2go/util.typeToExpr(0xc42f5b78c0, 0x15, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.NewCallExpr(0xc42f5b78c0, 0x15, 0xc430733560, 0x1, 0x1, 0xc42f5b78c0)
```
</blockquote></details>

I'm asking why did you choose `I`, could you use any other character? Please explain in the comment why you chose `I` and if it is important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Comment by Konstantin8105** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[types/resolve.go, line 180 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L5Bdk0-JOo-YXwPjMKu:-L5Dt-LvSvrmMoyFkEDi:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/a5b4ed07757e9b2fddd22543aefdb0b3e46afe65/types/resolve.go#L180)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please raise an issue for this and put the URL in the comment.
</blockquote></details>

Done.

---

*[util/util.go, line 58 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L4mX6nQ1CmUXZnaAPLh:-L5Dt42XgZeTuq2dmuVM:btv53d1) ([raw file](https://github.com/elliotchance/c2go/blob/dcce890d358d8d8e42a220ebe71414ef4e7025e4/util/util.go#L58)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm asking why did you choose `I`, could you use any other character? Please explain in the comment why you chose `I` and if it is important.
</blockquote></details>

No reason. Now, I change to '_'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by elliotchance** [comment]
Reviewed 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/goast.go, line 73 at r6](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L5lJfPcOwOhInznzalA:-L5lJfPcOwOhInznzalB:bfqrefl) ([raw file](https://github.com/elliotchance/c2go/blob/4d2cc74c8d7ef29662169050a9d599cbb92a4276/util/goast.go#L73)):*
> ```Go
> 	for _, special := range specials {
> 		input := []byte(goType)
> 	again:
> ```

Is this used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/goast.go, line 73 at r6](https://reviewable.io:443/reviews/elliotchance/c2go/611#-L5lJfPcOwOhInznzalA:-L5mKzwTbYLO3gBNpRsT:bht5gvf) ([raw file](https://github.com/elliotchance/c2go/blob/4d2cc74c8d7ef29662169050a9d599cbb92a4276/util/goast.go#L73)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Yes, it is used. For example if type is function of function ... In Go it is look, like that.
```
func(func(int),float64)
```
Also, yes can see https://codecov.io/gh/elliotchance/c2go/pull/611/src/util/goast.go?before=util/goast.go#L69 . All is green, then all is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/611)*

**Pull request merged**
