### PR TITLE
To show the sub-command print-ast position in argument list

### PR DESCRIPTION
**Pull request by tjyang**
This small change is to tell exactly  sub-command need to be in front of C file name argument.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/46)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[main.go, line 185 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/46#-KhtgacnYB_QmvR-UVdZ:-KhtgacnYB_QmvR-UVd_:bh815m5) ([raw file](https://github.com/elliotchance/c2go/blob/d800c8bae97ddb544847b8abc1fb49f52c64ae93/main.go#L185)):*
> ```Go
> func main() {
> 	flag.Usage = func() {
> 		fmt.Fprintf(os.Stderr, "Usage: %s [-print-ast] <file.c>\n", os.Args[0])
> ```

Maybe this makes more sense to be `[options]` so that we don't duplicate the flags? What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/46)*

**Comment by tjyang** [comment]
agree. [options] or [sub-commands] are better.

**Comment by elliotchance** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Makefile, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/46#-Khw5K4X71tQXdhgQr3z:-Khw5K4X71tQXdhgQr4-:brltjlm) ([raw file](https://github.com/elliotchance/c2go/blob/db0dd45068b4bf524f1363916b79b52f850585b3/Makefile#L1)):*
> ```Makefile
> BINARY=c2go
> ```

Please remove this file. The only command you need to run is "go build"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/46)*

**Comment by elliotchance** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/46)*

**Comment by elliotchance** [comment]
Thanks @tjyang

**Comment by tjyang** [comment]
@elliotchance, I am not much help so far. I am more of ops than dev guy. Hope to learn more golang programming from you guys.

**Comment by elliotchance** [comment]
@tjyang it says in the readme that no contribution is too small, and I meant it.

We are all just learning here... and what better way to learn that getting into the code and talking with others!

**Pull request merged**
