### PR TITLE
Basic  Makefile for build automation

### PR DESCRIPTION
**Pull request by tjyang**
Hi 

I hope you like this simple makefile.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/28)

### CODE REVIEW

**Comment by tjyang** [comment]
The most advanced  Makefile I know of is this one from tidb project.

https://github.com/pingcap/tidb/blob/master/Makefile

**Comment by elliotchance** [comment]
Thank you for the submission. However, I'm not sure what this is actually achieving.

Makefiles are not part of the native go ecosystem so using one to simply install the binary seems overkill. Or am I not understanding correctly?

**Comment by tjyang** [comment]
I am hoping to use Makefile to automate the go tool commands like following example
https://github.com/pingcap/tidb/blob/master/Makefile#L68
Beside "make {build|install|clean}" one can type "make check" to run all those go tool lint/vet ... commands. 

Please close this pull request, if you still not convince Makefile is helpful.

**Comment by elliotchance** [comment]
I think this would be a good idea if the build system was more complex, especially with dependencies. However, a lot of that is already offered with the go tools.

After #22 is complete the build chain should be even more simply and pure Go.

I don't want to discount your work, because it is not at all a bad idea. But I just don't think our build system is complex enough to warrant the change. Thanks anyway!

**Pull request closed without merging**
