### PR TITLE
Make ast property order flexible. Fixes #654

### LINKED ISSUE #654: Panic in parseVarDecl: could not match regexp
A panic with the following message occured:
```
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?(?:parent (?P<parent>0x[0-9a-f]+) )?<(?P<position>.*)>(?P<position2> .+:\d+)?(?P<used> used)?(?P<referenced> referenced)?(?P<name> \w+)? '(?P<type>.+?)'(?P<type2>:'.*?')?(?P<extern> extern)?(?P<static> static)?(?P<cinit> cinit)?(?P<register> register)?[\s]*$
0x7fb70e80ff30 <col:11, col:55> col:32 used c 'pcre_uint32':'unsigned int' register cinit
```
The order of the properties should not matter.

### PR DESCRIPTION
**Pull request by kamphaus**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/655)

### CODE REVIEW

**Comment by kamphaus** [comment]
Fixes #654

**Comment by elliotchance** [comment]
I don't understand why this PR is needed? Each of the test cases in the `ast` package are from real clang lines that have been encountered, and it should remain that way.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/655#-:-L8itimK549qmkElGPsU:bpel4k4)*

**Comment by kamphaus** [comment]
I made these changes, because I encountered an ast node that couldn't be parsed with the existing regexp.
I was using
```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
```
The node in question was `0x7fb70e80ff30 <col:11, col:55> col:32 used c 'pcre_uint32':'unsigned int' register cinit` (cf. issue #654).

Having encountered it once, I thought it was a good idea to make the ast node parsing more resilient for all node types where there are multiple such properties.

**Comment by elliotchance** [comment]
I understand what your saying but I want to avoid this approach for a couple of reasons:

1. It makes the regex more complicated. Some cases do not need the extra branches, but it's hard to separate cases with the ones that actually do. It also makes the code harder to read and more ambiguous.

2. All of the existing unit tests are from concrete cases that have been surfaced (that's why it provides the line in the panic). This gives us a large and complete test suite if we decide to refactor how the lines are processed in the future.

If you find any cases that do raise a panic, please put those in a PR, like you have done before :)

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/655#-:-L97h0WzCbO3qmQaMcNe:b-yjz2xr)*

**Comment by kamphaus** [comment]
* I would prefer to keep the parsing more resilient, but I understand that you'd like to have a complete test suite.
Would you accept it if I added tests for all the attribute permutations?

* If I should add PRs individually for each panic, how should I write the regex to consider the different orders, or are the regexs from this PR fine?
For example for the node `0x7fb70e80ff30 <col:11, col:55> col:32 used c 'pcre_uint32':'unsigned int' register cinit` parsed by `ast/var_decl.go`?

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/655#-:-L9JZYxN4tEd8J683rys:bjvhsxd)*

**Comment by elliotchance** [comment]
All of the existing test cases are from real data. If you create synthetic tests for cases that do not exist it will just muddy this. Panics from reading the AST are becoming increasingly rare and overtime we will naturally cover everything.

You can put in a PR with as many panics cases as you wish, but they must come from the actual panic output and only adjust the regex the minimum required to satisfy the tests.

In basically all cases the existing regexes give examples for any situation you may come across. But do not nest them like you have done with `(?: )*`. I haven't found any cases yet that cannot be handled with left-to-right (no repeating or read-ahead) simple regex.

Also keep in mind that a large part of c2go is parsing huge AST trees from clang and parsing them in parallel is not easy so we want to keep the regexes tight and quick (another reason to not make them more generic). It is also possible that in the future we use a more manual token consume approach which would only work with simple regexes.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/655#-:-L9N8btU9fmAr74ojo-Y:b-yws8c1)*

**Review by WNora — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/elliotchance/c2go/655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kamphaus)

**Pull request closed without merging**
