### PR TITLE
Added strcpy() and strncpy(). Fixes #259

### LINKED ISSUE #259: strcpy
C code:
```c
#include <stdio.h>
#include <string.h>
 
union Data {
   int i;
   float f;
   char str[20];
};
 
int main( ) {
   union Data data;        

   data.i = 10;
   printf( "data.i : %d\n", data.i);
   
   data.f = 220.5;
   printf( "data.f : %f\n", data.f);
   
   strcpy( data.str, "C Programming");
   printf( "data.str : %s\n", data.str);  // Here somethink wrong

   return 0;
}
```
correct result:
```
data.i : 10
data.f : 220.500000
data.str : C Programming
```

Problem:
`undefined: strcpy` in Go code
function `strcpy` in C from `#include <string.h>` see http://www.cplusplus.com/reference/cstring/strcpy/?kw=strcpy

### PR DESCRIPTION
**Pull request by elliotchance**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/435)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/435)*

**Comment by elliotchance** [comment]
@Konstantin8105 do you have any idea why this might be failing on linux?

**Comment by Konstantin8105** [comment]
@elliotchance , Ok, I will analyze after #469.
At the first, I will look on 
```go
	"char* strncpy(const char*, char*, size_t) -> noarch.Strncpy",
```
may be `size_t` is not acceptable, like a function argument. If it will be a true, then #469 can solve that problem(we will check).

**Comment by Konstantin8105** [comment]
```
± |strcpy ✓| → go test -tags=integration -run=TestIntegrationScripts/tests/string.c -v
=== RUN   TestIntegrationScripts
=== RUN   TestIntegrationScripts/tests/string.c
TAP: # Total tests: 0
--- FAIL: TestIntegrationScripts (3.82s)
    --- FAIL: TestIntegrationScripts/tests/string.c (3.82s)
    	main_test.go:157: Expected 
    		Got: # command-line-arguments
    		build/tests/string/main_test.go:237:44: cannot use size_t(uint32(20)) (type size_t) as type int in argument to noarch.Strncpy
    		build/tests/string/main_test.go:564:44: cannot use size_t(uint32(5)) (type size_t) as type int in argument to noarch.Strncpy
FAIL
exit status 1
FAIL	github.com/elliotchance/c2go	3.837s

```
```go
	noarch.Printf([]byte("# \x00"))
	noarch.Printf([]byte("strncpy\x00"))
	noarch.Printf([]byte("\n\x00"))
	{
		var src []byte = []byte("foo bar\x00baz\x00")
		var dest1 []byte = make([]byte, 40, 40)
		var dest2 []byte
		dest1[7] = 'a'
		dest1[15] = 'b'
		dest1[25] = 'c'
		dest2 = noarch.Strncpy(dest1, src, size_t((uint32(20)))) /// <- HERE
```
Yes, it is happen - type conversion argument of function.
My #469 , can solve but partly.

**Comment by Konstantin8105** [comment]
For information in linux:
```go
type size_t uint32
```

**Comment by elliotchance** [comment]
@Konstantin8105 thank you for investigating, I will fix it 😄

**Comment by Konstantin8105** [comment]
I think, I solved that in #469:
Step 1 - add `break`:
https://github.com/Konstantin8105/c2go/blob/6be230c021add78b92e4522229b5550ff97802ab/transpiler/translation_unit.go#L40
Step2 - remove `sigset_t` from list:
https://github.com/elliotchance/c2go/blob/b1d0713d6407c38b054bbdcf5892c9135de2c31b/transpiler/declarations.go#L212

**Comment by Konstantin8105** [comment]
Close #259

**Comment by Konstantin8105** [comment]
Dear @elliotchance , could you try to merge that PR.

**Comment by Konstantin8105** [comment]
Dear @elliotchance,
After analyze on my linux laptop. Could you try this - rename type for one of argument:
```diff
diff --git a/program/function_definition.go b/program/function_definition.go
index 0ff4f1a..6a0a3b3 100644
--- a/program/function_definition.go
+++ b/program/function_definition.go
@@ -169,7 +169,7 @@ var builtInFunctionDefinitions = []string{
 
        // string.h
        "char* strcpy(const char*, char*) -> noarch.Strcpy",
-       "char* strncpy(const char*, char*, size_t) -> noarch.Strncpy",
+       "char* strncpy(const char*, char*, int) -> noarch.Strncpy",
 
        // real return type is "size_t", but it is changed to "int"
        // in according to noarch.Strlen
```

**Comment by elliotchance** [comment]
Thanks @Konstantin8105 !

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/435)*

**Pull request merged**
