### PR TITLE
COMMA problem for variable

### PR DESCRIPTION
**Pull request by Konstantin8105**
Solving problem of few equals on one line:
```c
x = y = z = 1;
```
That expression transform to comma problem.
```c
z = 1, y = z, x = y;
```
Only after that solving - comma problem and result:
```c
z = 1;
y = z;
x = y;
```

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/185)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/operators.c, line 80 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAIT1AO2wqyj1fMX97:-KoAIT1AO2wqyj1fMX98:b-sp1zpn) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/tests/operators.c#L80)):*
> ```C
> 	diag("Operator equal for 1 variables");
> 	int x;
> 	x = 0;
> ```

Please use any value other than `0` to test the assigned value (and also below). Go automatically zeros out data, so it's possible that the assignment could not be transpiled and this test will still pass.

---

*[tests/operators.c, line 106 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAIpmYdg8snQNM53Wm:-KoAIpmYdg8snQNM53Wn:b-ubpzgo) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/tests/operators.c#L106)):*
> ```C
> 		is_eq(q, 7);
> 		is_eq(w, 10);
> 		is_eq(e, 17);
> ```

These tests are great. Can you also please add a case for multiple assignment of another type like `float`?

---

*[transpiler/binary.go, line 79 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAJCdHcyekLkXcHwYB:-KoAJCdHcyekLkXcHwYC:b3dbmqa) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L79)):*
> ```Go
> 	// |   `-ImplicitCastExpr 0x368e898 <col:13> 'int' <LValueToRValue>
> 	// |     `-DeclRefExpr 0x368e870 <col:13> 'int' lvalue Var 0x368e748 'y' 'int'
> 	if getTokenForOperator(n.Operator) == token.ASSIGN {
> ```

I'm trying to think of a case where there is more than 2 children, but the first operator is not `=`. However, I don't think that is possible because of the order of operations.

What about if they used a different assignment operator like? `a += b += c` will that compile under clang?

---

*[transpiler/binary.go, line 84 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAJwaqVBxbcuxrM97x:-KoAJwaqVBxbcuxrM97y:bxtr76d) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L84)):*
> ```Go
> 			{
> 				if getTokenForOperator(c.Operator) == token.ASSIGN {
> 					var bSecond ast.BinaryOperator
> ```

Prefer to new instantiations rather than referencing stack memory:

```go
bSecond := &ast.BinaryOperator{
    Type: c.Type,
    Operator: "=",
}
bSecond.AddChild(n.Children[0])
```

---

*[transpiler/binary.go, line 135 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAKj6_jKOgpDLViF8Z:-KoAKj6aWrz8mY3zhdKO:b-14h7v2) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L135)):*
> ```Go
> 		}
> 		preStmts = append(preStmts, newPre...)
> 		preStmts = append(preStmts, util.NewExprStmt(stmts))
> ```

`append` takes all arguments in order, so these two statements can be reduced to be more readable:

```go
preStmts = append(preStmts, newPre..., util.NewExprStmt(stmts))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/185)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/operators.c, line 80 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAIT1AO2wqyj1fMX97:-KoCiGLKcAuTmF8bNBdG:b4855pb) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/tests/operators.c#L80)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please use any value other than `0` to test the assigned value (and also below). Go automatically zeros out data, so it's possible that the assignment could not be transpiled and this test will still pass.
</blockquote></details>

Thanks! Done.

---

*[tests/operators.c, line 106 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAIpmYdg8snQNM53Wm:-KoCkSUFJNsvNeF4aWSE:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/tests/operators.c#L106)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

These tests are great. Can you also please add a case for multiple assignment of another type like `float`?
</blockquote></details>

Done.

---

*[transpiler/binary.go, line 79 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAJCdHcyekLkXcHwYB:-KoCl5wpZMQ5iHselw6-:b5udusp) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L79)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm trying to think of a case where there is more than 2 children, but the first operator is not `=`. However, I don't think that is possible because of the order of operations.

What about if they used a different assignment operator like? `a += b += c` will that compile under clang?
</blockquote></details>

I don`t see in practice using `a+=b+=c`, but this is acceptable by `gcc`:
```c
#include <stdio.h>

int main(void)
{
	int x, y, z;
	x = y = z = 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	x += y += z += 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	x *= y *= z *= 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	return 0;
}
```

Result:
```
x = 5	y = 5	z = 5
x = 20	y = 15	z = 10
x = 15000	y = 750	z = 50
```

If actual issue in your point of view, then please create the issue and later I will create the PR.

---

*[transpiler/binary.go, line 84 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAJwaqVBxbcuxrM97x:-KoCm7yb98yov9M6eCJF:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L84)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Prefer to new instantiations rather than referencing stack memory:

```go
bSecond := &ast.BinaryOperator{
    Type: c.Type,
    Operator: "=",
}
bSecond.AddChild(n.Children[0])
```
</blockquote></details>

Done.

---

*[transpiler/binary.go, line 135 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAKj6_jKOgpDLViF8Z:-KoCmJGgEvvQW4WqbvK_:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L135)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`append` takes all arguments in order, so these two statements can be reduced to be more readable:

```go
preStmts = append(preStmts, newPre..., util.NewExprStmt(stmts))
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/185)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[transpiler/binary.go, line 135 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAKj6_jKOgpDLViF8Z:-KoCnm4cf2uOG50evWm_:b-ldn1js) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L135)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I try to do that, but have error:
```error
transpiler/binary.go:135: syntax error: unexpected util, expecting )
transpiler/binary.go:146: syntax error: non-declaration statement outside function body
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/185)*

**Comment by Konstantin8105** [comment]
That PR solved problem in one file.
See: https://github.com/Konstantin8105/c2go-rating

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/binary.go, line 79 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAJCdHcyekLkXcHwYB:-KoS6otioCyVsO5-TsXy:b7n2zrp) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L79)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I don`t see in practice using `a+=b+=c`, but this is acceptable by `gcc`:
```c
#include <stdio.h>

int main(void)
{
	int x, y, z;
	x = y = z = 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	x += y += z += 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	x *= y *= z *= 5;
	printf("x = %d\ty = %d\tz = %d\n",x,y,z);
	return 0;
}
```

Result:
```
x = 5	y = 5	z = 5
x = 20	y = 15	z = 10
x = 15000	y = 750	z = 50
```

If actual issue in your point of view, then please create the issue and later I will create the PR.
</blockquote></details>

Yep, fair enough.

---

*[transpiler/binary.go, line 135 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/185#-KoAKj6_jKOgpDLViF8Z:-KoS8PQK2ovQbkccy6zL:bmhzq3v) ([raw file](https://github.com/elliotchance/c2go/blob/ab55889c5f31d0b7417ec264abbf6b3ae6647bd4/transpiler/binary.go#L135)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I try to do that, but have error:
```error
transpiler/binary.go:135: syntax error: unexpected util, expecting )
transpiler/binary.go:146: syntax error: non-declaration statement outside function body
```
</blockquote></details>

Hmm I'm not sure why that would be. It's fine to leave it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/185)*

**Pull request merged**
