### PR TITLE
Pointer to pointer. Fixes #503

### LINKED ISSUE #503: Pointer to pointer
Example:
```c
#include<stdio.h>
void main() 
{
  int i =50;
  int **ptr1;
  int *ptr2;
  ptr2 = &i;
  ptr1 = &ptr2;
  printf("\nThe value of **ptr1 : %d",**ptr1); // <<--- LOST LINE
  printf("\nThe value of *ptr2  : %d",*ptr2);
}
```
GCC:
```
○ → gcc 2.c ; ./a.out ; rm ./a.out

The value of **ptr1 : 50
The value of *ptr2  : 50
```
GO:
```go
func main() {
        var i int = 50
        var ptr1 [][]int
        var ptr2 []int
        ptr2 = (*[1]int)(unsafe.Pointer(&i))[:]
        ptr1 = (*[1][]int)(unsafe.Pointer(&ptr2))[:]
        noarch.Printf([]byte("\nThe value of *ptr2  : %d\x00"), ptr2[0])
}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #503

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/505)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by elliotchance** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/505)*

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[tests/array.c, line 275 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/505#-L1K2kI7vKhtUhIpxq5C:-L1K2kI7vKhtUhIpxq5D:b-d28hot) ([raw file](https://github.com/elliotchance/c2go/blob/f999c95203b2f80c4875013fc280128e15392a27/tests/array.c#L275)):*
> ```C
> 		(void)(PPptr2);
> 	}
> 	/*
> ```

Why did you comment this out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/505)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[tests/array.c, line 275 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/505#-L1K2kI7vKhtUhIpxq5C:-L1NHNz-e8GqZuJWAfdy:b-r9g5d9) ([raw file](https://github.com/elliotchance/c2go/blob/f999c95203b2f80c4875013fc280128e15392a27/tests/array.c#L275)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why did you comment this out?
</blockquote></details>

Now, that PR is not ready for review.
That comment block are not supported in c2go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/505)*

**Comment by Konstantin8105** [comment]
Closed, because bad design.

**Pull request closed without merging**
