### PR TITLE
Triangle dashbord

### PR DESCRIPTION
**Pull request by Konstantin8105**
Created for #560
Without #622 that PR have panic
Created for #398

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/624)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
That bash script created not for travis, but if you want I can add.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/triangle.sh, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/624#-L5BgLMyftql2eMrBrGz:-L5BgLMyftql2eMrBrH-:bwi0ncn) ([raw file](https://github.com/elliotchance/c2go/blob/4cd0adb08f45720e827df80e928cc0dcd47af5fe/travis/triangle.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Can you explain what this file is for and why it is named `triangle`? It is not attached to the build system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/624)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/triangle.sh, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/624#-L5BgLMyftql2eMrBrGz:-L5DxeDySBXJXVYXYeOq:b-8jp9uq) ([raw file](https://github.com/elliotchance/c2go/blob/4cd0adb08f45720e827df80e928cc0dcd47af5fe/travis/triangle.sh#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Can you explain what this file is for and why it is named `triangle`? It is not attached to the build system.
</blockquote></details>

Name: `triangle` because it is base name of source,  see https://www.cs.cmu.edu/~quake/triangle.html
Why: source `triangle` have better ratio = amount of warnings divided to amount of line
triangle 1600 warning to 10000 lines
sqlite   10000 warning to 400000 lines
So, in `triangle` more easy found we collisions.

Now, It is ready for adding into build system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/624)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/624)*

**Pull request merged**
