### PR TITLE
Function pointer inside struct. Fixes #467

### LINKED ISSUE #467: function pointer inside struct
After #430:
```c
typedef struct sqlite3_vfs sqlite3_vfs;
struct sqlite3_vfs {
  int (*xOpen)(sqlite3_vfs*, const char *zName, sqlite3_file*,  int flags, int *pOutFlags);
```
Another example:
```c
typedef struct {
  int x;
  int (*f)(int, float);
} THING;
```
Example with recursive:
```c
typedef struct FUNC func;
struct FUNC
{
    int a, b, s;
    void  (*sum)(func *);
};
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #467

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/490)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Close  #474

**Comment by elliotchance** [comment]
Reviewed 1 of 5 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/binary.go, line 302 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/490#-L0q6_wPyU9lSmYiDQfa:-L0q6_wPyU9lSmYiDQfb:b-ep9e9w) ([raw file](https://github.com/elliotchance/c2go/blob/6aba2dfaa591f1c46cbd755a1ec6fd53351ec3ce/transpiler/binary.go#L302)):*
> ```Go
> 					if union != nil && union.IsUnion {
> 						attrType, err := types.ResolveType(p, ref.Type)
> 						if err != nil {
> ```

Why did you remove this check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/490)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/binary.go, line 302 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/490#-L0q6_wPyU9lSmYiDQfa:-L0rsqu8zJNeV7ZiWDUz:bqc8k8u) ([raw file](https://github.com/elliotchance/c2go/blob/6aba2dfaa591f1c46cbd755a1ec6fd53351ec3ce/transpiler/binary.go#L302)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why did you remove this check?
</blockquote></details>

I return back, but in my point of view, it is identical. It is happen because, checking `err != nil` will check inside function `GenerateWarningMessage`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/490)*

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/490)*

**Pull request merged**
