### PR TITLE
FullComment ignore

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/562)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/declarations.go, line 175 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/562#-L2vzqlhMskpKJuzVc0K:-L2vzqlhMskpKJuzVc0L:b-qojvc6) ([raw file](https://github.com/elliotchance/c2go/blob/f82aba3ad069ae9dc67cc7fa2ef35555769d5878/transpiler/declarations.go#L175)):*
> ```Go
> 
> 		case *ast.FullComment:
> 			// do nothing
> ```

Does this mean that the comments inside a struct will not be output in the Go file? Or are all the comment collected somewhere else? Please add a comment either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/562)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/declarations.go, line 175 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/562#-L2vzqlhMskpKJuzVc0K:-L2xzkuV36IqJAhR_kzk:bvkxd4o) ([raw file](https://github.com/elliotchance/c2go/blob/f82aba3ad069ae9dc67cc7fa2ef35555769d5878/transpiler/declarations.go#L175)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Does this mean that the comments inside a struct will not be output in the Go file? Or are all the comment collected somewhere else? Please add a comment either way.
</blockquote></details>

add more comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/562)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/562)*

**Comment by Konstantin8105** [comment]
Merge to #558

**Pull request closed without merging**
