### PR TITLE
CSTD: strchr. Fixes #603

### LINKED ISSUE #603: CSTD: strchr
Documentation : http://www.cplusplus.com/reference/cstring/strchr/

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #603

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/604)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/operators.go, line 251 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/604#-L42w2uJ3qMT40oUHD1w:-L42w2uJ3qMT40oUHD1x:b-uxeu97) ([raw file](https://github.com/elliotchance/c2go/blob/b8f124efde7540e179f094263c3d4573660b80d5/transpiler/operators.go#L251)):*
> ```Go
> 	src := `package main
> func main(){
> 	a := (*(*[10000000]{{ .Type }})(unsafe.Pointer(uintptr(unsafe.Pointer(&{{ .Name }}[0])) {{ .Operator }} (uintptr)({{ .Condition }})*unsafe.Sizeof({{ .Name }}[0]))))[:]
> ```

Why does this need to be changed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/604)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/operators.go, line 251 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/604#-L42w2uJ3qMT40oUHD1w:-L46LszQz-O4mqNMofDP:b1w3f5p) ([raw file](https://github.com/elliotchance/c2go/blob/b8f124efde7540e179f094263c3d4573660b80d5/transpiler/operators.go#L251)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why does this need to be changed?
</blockquote></details>

I haven't any detail explanations, but it is work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/604)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/operators.go, line 251 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/604#-L42w2uJ3qMT40oUHD1w:-L48KAoKKPJKWix8njz6:b-67hgea) ([raw file](https://github.com/elliotchance/c2go/blob/b8f124efde7540e179f094263c3d4573660b80d5/transpiler/operators.go#L251)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I haven't any detail explanations, but it is work.
</blockquote></details>

I'm afraid of:

1. That it may be allocating many megabytes to do the casting.
2. 10 million is such an arbitrary number, if it doesn't take more memory then you should make this number as large as possible.
3. It's confusing because the next person doesn't know why this number was chosen, or what the reason for it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/604)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/604)*

**Pull request merged**
