### PR TITLE
Unions. Fixes #84

### LINKED ISSUE #84: Unions are not supported

### PR DESCRIPTION
**Pull request by corebreaker**
Adding support for union types.

It works with present tests (samples files in tests directory).

However, some cases must be checked like anonymous types in variable declarations and union initialization subscripts.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/163)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 10 of 18 files at r1.
Review status: 10 of 18 files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[ast/ast.go, line 385 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-JWhWSuBUi5qrtS3W:-Km-JWhXgMp9qYJhL43z:b3q1zcg) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/ast.go#L385)):*
> ```Go
> 	case "WhileStmt":
> 		return parseWhileStmt(line)
> 	case "NullStmt", "WeakAttr":
> ```

`NullStmt` is a special case because it does not follow the syntax of all of the others.

`WeakAttr` (even if it's of no use to us right now) does and it should have a `weak_attr.go` and `weak_attr_test.go` respectively.

You should be able to copy one of the other `_attr` files that will be similar.

---

*[ast/member_expr.go, line 40 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-KGg-Yhbjg9E7CB-4:-Km-KGg-Yhbjg9E7CB-5:bu4lbbs) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/member_expr.go#L40)):*
> ```Go
> // GetDeclRef gets DeclRef from MemberExpr, or nil if there is not
> func (n *MemberExpr) GetDeclRef() *DeclRefExpr {
> 	child := n.Children[0]
> ```

I'm not sure if if can be guaranteed that the first child is the only one that matters (attributes, for example).

You should check all children for the `*DeclRefExpr`.

---

*[ast/member_expr.go, line 49 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-LGx0zzsrStGPa6li:-Km-LGx0zzsrStGPa6lj:b-n340zy) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/member_expr.go#L49)):*
> ```Go
> 	}
> 
> 	return res
> ```

Does `nil` mean there is no `*DeclRefExpr` and that's fine. Or that we couldn't understand the definition properly and we will fall back to `nil` so that it can proceed?

---

*[program/import.go, line 28 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-Le0QDX-rOoBAFA0k:-Km-Le0QDX-rOoBAFA0l:b-bv0r3q) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/import.go#L28)):*
> ```Go
> 		if p.Unions.HasType("union " + t) {
> 			addImport("reflect")
> 			addImport("unsafe")
> ```

This is the wrong place to put this logic. When a union is discovered during the transpiling it should append the imports at that point.

---

*[program/program.go, line 110 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-MWK2CyGCSyvnWPgE:-Km-MWK2CyGCSyvnWPgF:b-g5su11) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/program.go#L110)):*
> ```Go
> func (p *Program) GetStruct(name string) *Struct {
> 	last := len(name) - 1
> 	if name[last] == '*' {
> ```

Why would the pointer ever be in the struct name? This should be sanitised before this point.

---

*[program/struct.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-MrnjWGsbWyrHt7ns:-Km-MrnjWGsbWyrHt7nt:b-ycobqm) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/struct.go#L15)):*
> ```Go
> 
> 	// True if the struct kind is an union.
> 	IsUnion bool
> ```

If this exists, do we need separate `Structs` and `Unions` on the program?

---

*[samples/union.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NFLy78jYkoGG39fH:-Km-NFLy78jYkoGG39fI:b-kbqkfg) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/samples/union.go#L1)):*
> ```Go
> package main
> ```

Is this file for your debugging?

---

*[tests/struct.c, line 38 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NWBAEoqz5K_QWg2k:-Km-NWBAEoqz5K_QWg2l:b4ke8w9) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/struct.c#L38)):*
> ```C
>     is_streq(variable.pointer, "Programming in Software Development.");
> 
>     f(&variable);
> ```

Another test case (pass by value):

```c
f(variable);
```

---

*[tests/struct.c, line 42 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NcrKXx2tjlGaA0Ok:-Km-NcrKXx2tjlGaA0Ol:b-irbsiq) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/struct.c#L42)):*
> ```C
>     done_testing();
> 
>     return 0;
> ```

Remove this. `done_testing()` is a macro that will return the correct exit status.

---

*[tests/union.c, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-Oafjg56N7HeSNlBS:-Km-Oafjg56N7HeSNlBT:bjfohj9) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L1)):*
> ```C
> // Tests for unions.
> ```

Please update `sizeof.c` to add tests for unions sizes.

---

*[tests/union.c, line 36 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-O4pl_VvLFbh7XVbx:-Km-O4pl_VvLFbh7XVby:b-jrbv1x) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L36)):*
> ```C
> 
>     variable.constant = 1.23;
>     is_eq(variable.constant, 1.23);
> ```

Please move all of the above to a function, like `f`.

---

*[tests/union.c, line 42 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-OCcpSCm0gleNc_Fq:-Km-OCcpSCm0gleNc_Fr:b-6nzv6v) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L42)):*
> ```C
>     done_testing();
> 
>     return 0;
> ```

Remove this.

---

*[transpiler/declarations.go, line 83 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-OoSJqL3OXZNyGld9:-Km-OoSJqL3OXZNyGldA:b-beoj48) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/transpiler/declarations.go#L83)):*
> ```Go
> 		size, err := types.SizeOf(p, "union "+name)
> 		if err != nil {
> 			fmt.Println("Error:", err)
> ```

Is this a legitimate failure (like something has gone wrong) and the output code will not work? Or is this a warning that can be recovered from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Comment by corebreaker** [comment]
I pushed changes after your code review.

**Comment by elliotchance** [comment]
@corebreaker please `git fmt` the code.

Also, can you please reply to discussions in reviewable.

**Comment by corebreaker** [comment]
Ok, i'm going to do it

**Comment by corebreaker** [comment]
Review status: 1 of 20 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[ast/ast.go, line 385 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-JWhWSuBUi5qrtS3W:-Km0Z7BwdSnXvS2PLesB:b-nuztm9) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/ast.go#L385)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`NullStmt` is a special case because it does not follow the syntax of all of the others.

`WeakAttr` (even if it's of no use to us right now) does and it should have a `weak_attr.go` and `weak_attr_test.go` respectively.

You should be able to copy one of the other `_attr` files that will be similar.
</blockquote></details>

OK, i did all that. I created files weak_attr.go and weak_attr_test.go

---

*[ast/member_expr.go, line 40 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-KGg-Yhbjg9E7CB-4:-Km0Zsy99DCaFBnT5W7D:b-n44pqg) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/member_expr.go#L40)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm not sure if if can be guaranteed that the first child is the only one that matters (attributes, for example).

You should check all children for the `*DeclRefExpr`.
</blockquote></details>

Ok, i did it in a loop.

---

*[ast/member_expr.go, line 49 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-LGx0zzsrStGPa6li:-Km0_3ES9HQZJ1IWwStF:b-y9rurz) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/ast/member_expr.go#L49)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Does `nil` mean there is no `*DeclRefExpr` and that's fine. Or that we couldn't understand the definition properly and we will fall back to `nil` so that it can proceed?
</blockquote></details>

`nil` means that there is no `*DeclRefExpr`, i add comments in code to explain that.

---

*[program/program.go, line 110 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-MWK2CyGCSyvnWPgE:-Km0cpz-FDvxvyDqTBvf:bhl9k9) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/program.go#L110)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why would the pointer ever be in the struct name? This should be sanitised before this point.
</blockquote></details>

Not always, i added comments in code to explain. Actually, in `DeclRefExpr`, there is a pointer type in the case we use `->` operator for accessing to a member.

---

*[program/struct.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-MrnjWGsbWyrHt7ns:-Km0bdhNIGuGGSX9xuPK:bfwaogs) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/struct.go#L15)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

If this exists, do we need separate `Structs` and `Unions` on the program?
</blockquote></details>

I prefered reuse the Go struct to gain in homogeneity. So Union is a "special" struct. But it's not the main reason, that's simplify algorithms in some cases. I added comments in code to explain.

---

*[tests/struct.c, line 38 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NWBAEoqz5K_QWg2k:-Km0_SqQ_-m6SQ1CVVLx:b-s9k8s) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/struct.c#L38)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Another test case (pass by value):

```c
f(variable);
```
</blockquote></details>

That's done.

---

*[tests/struct.c, line 42 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NcrKXx2tjlGaA0Ok:-Km0_XZc1SBXnOjAIkU6:b-iwfr47) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/struct.c#L42)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Remove this. `done_testing()` is a macro that will return the correct exit status.
</blockquote></details>

Ok, sorry. That's done.

---

*[tests/union.c, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-Oafjg56N7HeSNlBS:-Km0_cVMq6Rbi9m2TN-y:b-5l8pyi) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please update `sizeof.c` to add tests for unions sizes.
</blockquote></details>

Yes, thank you, i haven't seen it. That's done.

---

*[tests/union.c, line 36 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-O4pl_VvLFbh7XVbx:-Km0_ugyw6Mq_vScQsVu:b-dl1muu) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L36)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please move all of the above to a function, like `f`.
</blockquote></details>

I tried to do it, but i wanted a variable in the test function to test pointer on a union without doing a malloc. So, i made an initialization function (`init_var()`) which move main tests. I keeped all other function to test call with arguments passed by reference.

---

*[tests/union.c, line 42 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-OCcpSCm0gleNc_Fq:-Km0acA8hsbZUfceVpj9:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/tests/union.c#L42)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.

---

*[transpiler/declarations.go, line 83 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-OoSJqL3OXZNyGld9:-Km0afumG8pK39JXj6rP:b-p7imeq) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/transpiler/declarations.go#L83)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this a legitimate failure (like something has gone wrong) and the output code will not work? Or is this a warning that can be recovered from?
</blockquote></details>

You are right, normally, there is no error, but i wanted prevent future problems. But i replaced it by a warning.

---

*[program/import.go, line 28 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-Le0QDX-rOoBAFA0k:-Km0b1GvkvDun3ni5-MN:b5hrcjj) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/program/import.go#L28)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is the wrong place to put this logic. When a union is discovered during the transpiling it should append the imports at that point.
</blockquote></details>

Ok, i moved it in the transpiling function.

---

*[samples/union.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km-NFLy78jYkoGG39fH:-Km0bD1Gf5cPrgbU5UAY:b4bm09) ([raw file](https://github.com/elliotchance/c2go/blob/efa35eecc621b51e96fff1d07a4a1fbe8ff312c8/samples/union.go#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this file for your debugging?
</blockquote></details>

Not really, more as a pattern to compare to produced code by the transpiler. I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Comment by elliotchance** [comment]
Reviewed 4 of 18 files at r1, 3 of 16 files at r2, 12 of 12 files at r3.
Review status: 18 of 20 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[util/regexp.go, line 9 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km0f9SYQKFshAn7lgpk:-Km0f9SYQKFshAn7lgpl:b-61uby0) ([raw file](https://github.com/elliotchance/c2go/blob/21112c4644e7372ca489200fb3e8cbbc389e7a00/util/regexp.go#L9)):*
> ```Go
> 
> // GroupsFromRegex gets RegExp groups after matching it on a line
> func GroupsFromRegex(rx, line string) map[string]string {
> ```

`GroupsFromRegex` logic and purpose it quite specific to the `ast` package. Why did you move it to a public package? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Comment by elliotchance** [comment]
Reviewed 1 of 18 files at r1, 1 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[types/sizeof.go, line 79 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km0fwHG3EDpWzcLR9a0:-Km0fwHHsnXdvivRHOqI:bumzmy0) ([raw file](https://github.com/elliotchance/c2go/blob/21112c4644e7372ca489200fb3e8cbbc389e7a00/types/sizeof.go#L79)):*
> ```Go
> 		}
> 
> 		for _, t := range s.Fields {
> ```

This is duplicate from above. Please extract this to a common method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Comment by corebreaker** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[types/sizeof.go, line 79 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km0fwHG3EDpWzcLR9a0:-Km0j7HTvJBKZYQ2Om55:b6qnzkk) ([raw file](https://github.com/elliotchance/c2go/blob/21112c4644e7372ca489200fb3e8cbbc389e7a00/types/sizeof.go#L79)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is duplicate from above. Please extract this to a common method.
</blockquote></details>

It's not a duplicate code, for struts, the size of each member is summed but for unions we must compute the max size.

Inside each `if string.HasPrefix(...)`, there is no common part.

---

*[util/regexp.go, line 9 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/163#-Km0f9SYQKFshAn7lgpk:-Km0htZq1wAVrcuoa5l2:blwv0jv) ([raw file](https://github.com/elliotchance/c2go/blob/21112c4644e7372ca489200fb3e8cbbc389e7a00/util/regexp.go#L9)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`GroupsFromRegex` logic and purpose it quite specific to the `ast` package. Why did you move it to a public package? 
</blockquote></details>

That function is not specific, it's a generic function to get a map result from a regexp. It's used in types/sizeof.go . That function is for general purpose and used as a shortcut for using regexp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Comment by elliotchance** [comment]
Please fix the remaining build failure and this will be ready to merge in.

**Comment by corebreaker** [comment]
I'd like but the problem is on OSX. On windows and Linux there is no problem.

How can i do ?

I'm trying to download an OSX ISO image for VirtualBox but it'll take time (5Gb to download).

**Comment by elliotchance** [comment]
I will debug it for you later today and send you the patch.

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/163)*

**Pull request merged**
