### PR TITLE
Fixed CStyleCastExpr #145

### PR DESCRIPTION
**Pull request by yulvil**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/314)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 16 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/314#-Kxyza79HNBK6Rpp_iWe:-Kxyza79HNBK6Rpp_iWf:bvadamz) ([raw file](https://github.com/elliotchance/c2go/blob/69cae50cd10da4dbd145993b32285cec11baf1ca/transpiler/transpiler.go#L16)):*
> ```Go
> 	"github.com/elliotchance/c2go/program"
> 	"github.com/elliotchance/c2go/util"
> 	"github.com/yulvil/c2go/types"
> ```

Have you got c2go checked out in `$GOROOT/src/github.com/elliotchance/c2go` or a different folder?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/314)*

**Comment by yulvil** [comment]
@elliotchance I am working in $GOPATH/src/github.com/elliotchance/c2go but for some reason my IDE resolved to github.com/yulvil/c2go. I removed the latter to prevent that from happening again.

**Comment by yulvil** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 16 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/314#-Kxyza79HNBK6Rpp_iWe:-KxzFfYL8F7FX_5KpUpJ:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/69cae50cd10da4dbd145993b32285cec11baf1ca/transpiler/transpiler.go#L16)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Have you got c2go checked out in `$GOROOT/src/github.com/elliotchance/c2go` or a different folder?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/314)*

**Comment by yulvil** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 16 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/314#-Kxyza79HNBK6Rpp_iWe:-KxzK1V5XCHAVOOZe1wl:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/69cae50cd10da4dbd145993b32285cec11baf1ca/transpiler/transpiler.go#L16)):*
<details><summary><i>Previously, yulvil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/314)*

**Comment by elliotchance** [comment]
All good :thumbsup: I've seen in the past sometimes people check it out to their github path.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/314#-:-KxzV8YQ6yE6xP2d8S-D:b1ctj30)*

**Pull request merged**
