### PR TITLE
Single line and multiline comments. Fix #121

### LINKED ISSUE #121: Maintain comments in Go
All of the comments are currently discarded when generating the Go output.

This might be useful: https://stackoverflow.com/questions/25275212/how-to-extract-comments-and-match-to-declaration-with-recursiveastvisitor-in-lib

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #121

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/547)

### CODE REVIEW

**Comment by elliotchance** [comment]
Please resolve merge conflicts before I review.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/547#-:-L2HoZcYE403DfiUr3nT:bso86kq)*

**Comment by elliotchance** [comment]
Reviewed 15 of 19 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[preprocessor/preprocessor.go, line 134 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/547#-L2JSPOBaLApe8fRYrXB:-L2JSPOBaLApe8fRYrXC:bwdhc3x) ([raw file](https://github.com/elliotchance/c2go/blob/7f2c38763764228f3978812c1999411f7cdc75d6/preprocessor/preprocessor.go#L134)):*
> ```Go
> 
> func isPreprocessorWord(line string) bool {
> 	preprocessorWords := []string{"#pragma", "#elif", "#define", "# define"}
> ```

It allows a space for `define` but not the other words? Maybe it's enough to check that the first character is `#`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/547)*

**Comment by Konstantin8105** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[preprocessor/preprocessor.go, line 134 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/547#-L2JSPOBaLApe8fRYrXB:-L2JiSppsmYrG8BhINm_:bj18h6f) ([raw file](https://github.com/elliotchance/c2go/blob/7f2c38763764228f3978812c1999411f7cdc75d6/preprocessor/preprocessor.go#L134)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It allows a space for `define` but not the other words? Maybe it's enough to check that the first character is `#`?
</blockquote></details>

I create a regexp for that that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/547)*

**Comment by Konstantin8105** [comment]
For next PRs:
* Multiline comments
* Guarantee of comment sequence
* Guarantee : all comments will added

**Comment by Konstantin8105** [comment]
List of implemented features:
- Multiline comments
- Guarantee of comment sequence
- Guarantee : all comments will added

**Comment by elliotchance** [comment]
Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/547)*

**Pull request merged**
