### PR TITLE
Fixed typedef inside function. Fixes #272

### LINKED ISSUE #272: cannot use TypedefDecl for DeclStmt
C
```
int main() {
    struct node { int kind; int val; };
    typedef struct node node;

    node n;
    n.kind = 10;
    n.val = 20;
    return n.kind;
}
```

Go (current)
```
// Warning (TypedefDecl): %!s(int=3): cannot use TypedefDecl for DeclStmt
// Warning (VarDecl): %!s(int=5): I couldn't find an appropriate Go type for the C type 'node'.
// Warning (MemberExpr): %!s(int=6): I couldn't find an appropriate Go type for the C type 'node'.
// Warning (MemberExpr): %!s(int=6): cannot determine type for LHS 'node', will use 'void *' for all fields
// Warning (MemberExpr): %!s(int=7): I couldn't find an appropriate Go type for the C type 'node'.
// Warning (MemberExpr): %!s(int=7): cannot determine type for LHS 'node', will use 'void *' for all fields
// Warning (MemberExpr): %!s(int=8): I couldn't find an appropriate Go type for the C type 'node'.
// Warning (MemberExpr): %!s(int=8): cannot determine type for LHS 'node', will use 'void *' for all fields

package main

import "os"
import "github.com/elliotchance/c2go/noarch"

type __int128_t int64
type __uint128_t uint64

func main() {
        __init()
        var n interface {
        }
        n.kind = 10
        n.val = 20
        os.Exit(noarch.ByteSliceToInt(n.kind))
}
func __init() {
}
```

### PR DESCRIPTION
**Pull request by yulvil**
For #272

This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/347)

### CODE REVIEW

**Comment by yulvil** [comment]
@elliotchance I am still trying to come up with tests for this change, but all the tests require #322 to be fixed first.

It is up to you to decide if you want to wait for #322.

**Comment by Konstantin8105** [comment]
Could you check the result of that example:
```c
int main(){
    typedef int INT;
    INT i = 42;
    return 0;
}
```
Is look like that :
```go
type INT int // <---- Outside of function
func main(){
    var i INT = 42;
}
```

**Comment by yulvil** [comment]
@Konstantin8105 Hi. This is an easy fix that will fix most of the typedef cases.

I opened another issue #346 to fix the rare cases (?) where a typedef is defined multiple times (with different target types) within the same compilation unit.

**Comment by Konstantin8105** [comment]
@yulvil Hello, yes you are right. Now,`c2go` haven't any support of typedef types. It is more then nothing. And about - how to inject into function, we will in next PR.

**Comment by elliotchance** [comment]
I don't see any test cases for this so I'm not sure what has changed?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/347#-:-KywdZGu5GAW5Kh_diA5:burnz5j)*

**Comment by yulvil** [comment]
@elliotchance I need to fix #322 before I can write a test case that is working.

**Comment by elliotchance** [comment]
Do you want it merged or do you want me to wait for #322?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/347#-:-Kz6Hs4FMGONm7FQA_vz:b-yo52yl)*

**Comment by yulvil** [comment]
@elliotchance Please merge. I think it is safe. I will provide tests later.

**Pull request merged**
