### PR TITLE
Multiple C files in one go. Fixes #362

### LINKED ISSUE #362: Multifiles C code to single Go code
Now, we have the problem in multifile transpilation is separating `#define` on each file.
**Solution**
Example : `c2go transpile 1.c 2.c 3.c ....`
1) Find all definition for `1.c` like that:
```
clang -dM -E  1.c
```
Output:
```
#define BUFSIZ _IO_BUFSIZ
#define EOF (-1)
#define FILENAME_MAX 4096
#define FOPEN_MAX 16
#define L_ctermid 9
#define L_tmpnam 20
#define NULL ((void*)0)
...
```
2) Transfer definition to file 2.c. Used `-D` of clang.
3) ...
Link for help: https://clang.llvm.org/docs/ClangCommandLineReference.html#dumping-preprocessor-state

Main task for issue: Transling sqlite files `shell.c` and `sqlite3.c` in one.

> Last trying: https://github.com/Konstantin8105/c2go/blob/e70dfa5765eff7e05fdefaa754bf5c62b4a3986b/travis/test.sh

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #362

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/384)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
close #362

**Comment by elliotchance** [comment]
As I said on the original issue (#362) you *cannot* change anything before the preprocessor has run. You must only deal with the duplicates as a Go problem after the transpile process is complete.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L-YhcKT9iWBZOXQXs0x:bt66kyu)*

**Comment by Konstantin8105** [comment]
In according to #362,  you wrote about 2 variants of solution.
In that PR, choosed way 1.
How it is work?
`c2go transpile 1.c 2.c 3.c`
Preprocessor create a one file `union.c` with body:
https://github.com/Konstantin8105/c2go/blob/94c8210c7d7865762c58a0669e5717d821fa0e08/preprocessor/preprocessor.go#L157-L168
```c
#include "1.c"
#include "2.c"
#include "3.c"
```
and `clang` convert `union.c` like a solid file.

In according to #232, you wrote about dublicates of include header file.
For that case, we have a code for avoid that:
https://github.com/Konstantin8105/c2go/blob/94c8210c7d7865762c58a0669e5717d821fa0e08/preprocessor/preprocessor.go#L64-L94

In according to #232, you wrote about corner case with `#define` and I added test in PR#363 and solved.

In according to #232, you wrote about saving `gcc` steps - **one-to-one transpiling**. But I agree with [stackoverflow](https://stackoverflow.com/a/15445431/6896156), `gcc` use that just for saving compilation time for large projects, because you can recompile only changed source code.

In accroding to [travis result](https://travis-ci.org/elliotchance/c2go/jobs/310399406):
```
In files (sqlite3.go and shell.go) summary :    22937 warnings.
After transpiling shell.c and sqlite3.c together, have summary:    22488 warnings.
```
Present PR are solved a ~500 warnings.

If you want to check that PR on practice, then I can create a new travis test for project - see #398.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L-_TYeuYbOrprKWuy9h:bjvmec8)*

**Comment by Konstantin8105** [comment]
If you want, then I can create a new PR for founding dublicate of function. Also, it will good PR about postrocessing of transpile with 2 steps:
* Avoid null in GO AST. move https://github.com/Konstantin8105/c2go/blob/f75f3b6b31b3584e51214818c9f44a72b6053b07/transpiler/util.go#L269 to postprocessor
* Avoid dublicates of function. ( I don't write about other var, ... , because for begin it is ok and other will added later)

Please merge #384 and #391 "how is", if it possible for you.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L-_nA7ucLU7LKJ2GODV:bb75h5v)*

**Comment by elliotchance** [comment]
If you go down this direction you will end up with a lot of messy code that will not work very well. The correct way to handle multiple files is that you have to not interfere with the preprocessor (you cannot merge a single file or move #defines to other files). Instead:

1. Transpile each input file to its own output file. This should be easy as c2go already does this with one file, just iterate each input file.
2. Parse the Go AST of each output file to identify duplicate entities. Write the duplicate entities to a new Go file and remove them from the existing files.

The change you previously made to process multiple file was a great first step but its not a complete solution. You will have to do it the way I've outlined above otherwise there will be lots and lots of hacky code to try and get around issues. The proper solution is more reliable and easier.

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[main_test.go, line 162 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L-n2j_Wj2pTKrQuMwNw:-L-n2j_Wj2pTKrQuMwNx:bgmmj4i) ([raw file](https://github.com/elliotchance/c2go/blob/6f79a65f541740128d194b0c2964afe58cf2261c/main_test.go#L162)):*
> ```Go
> 				t.Fatal("Cannot get currently dir")
> 			}
> 			goProgramStderr = strings.Replace(goProgramStderr, currentDir+"/", "", -1)
> ```

Is this because assert now reports the lines in the union file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L-n33C-5tt2wR8pwS4V:b-264ihx)*

**Comment by elliotchance** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[preprocessor/parse_define_list.go, line 12 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vvF9047iy9Gi8vb53:-L2vvF9047iy9Gi8vb54:b-bhf00) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/parse_define_list.go#L12)):*
> ```Go
> )
> 
> func parseDefineList(line string) (define []string, err error) {
> ```

Is this used anymore?

---

*[preprocessor/parse_define_list_test.go, line 8 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vvMC_Nu4cATsVJ_Rr:-L2vvMC_Nu4cATsVJ_Rs:b-8drucz) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/parse_define_list_test.go#L8)):*
> ```Go
> )
> 
> func TestParseDefineList(t *testing.T) {
> ```

I'm not clear what this actually does? If `parseDefineList` is not used then this can also be removed.

---

*[preprocessor/preprocessor.go, line 245 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuiB2f-3jMWBtrQwA:-L2vuiB2f-3jMWBtrQwB:bs7k79e) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/preprocessor.go#L245)):*
> ```Go
> 	args = append(args, "-E", "-C")
> 	args = append(args, clangFlags...)
> 	args = append(args, unionFileName) // inputFiles...)
> ```

It looks like you have left some code behind. You can remove the comment or make it more clear like `// All inputFiles`

---

*[travis/test.sh, line 111 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuEewfgbF9Th9LWBb:-L2vuEewfgbF9Th9LWBc:bxcticn) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/travis/test.sh#L111)):*
> ```Shell
> fi
> 
> # SQLITE
> ```

You are already transpiling this above. Why do it again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[main_test.go, line 162 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L32RxoQ0_w8CijY4VlB:-L32RxoQ0_w8CijY4VlC:b-tfk6ld) ([raw file](https://github.com/elliotchance/c2go/blob/aea421cd0c9c962afce717346c0c7956e0873f1f/main_test.go#L162)):*
> Yes. Warning without that lines:
```
=== RUN   TestIntegrationScripts/tests/assert.c
TAP: # Total tests: 0
--- FAIL: TestIntegrationScripts (1.21s)
    --- FAIL: TestIntegrationScripts/tests/assert.c (1.21s)
    	main_test.go:165: Expected a.out: tests/assert.c:12: void print_number(int *): Assertion `myInt != NULL' failed.
    		
    		Got: a.out: /home/konstantin/go/src/github.com/elliotchance/c2go/tests/assert.c:12: void print_number(int *): Assertion `myInt != NULL' failed.
FAIL
exit status 1
```

---

*[preprocessor/parse_define_list.go, line 12 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vvF9047iy9Gi8vb53:-L32StqYyOwT2Gb8Gi3K:b-pej54n) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/parse_define_list.go#L12)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this used anymore?
</blockquote></details>

Yes , you are right - I will remove.

---

*[preprocessor/parse_define_list_test.go, line 8 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vvMC_Nu4cATsVJ_Rr:-L32T5fDd68dZdqM2Isf:bxbgzvc) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/parse_define_list_test.go#L8)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm not clear what this actually does? If `parseDefineList` is not used then this can also be removed.
</blockquote></details>

I will remove.

---

*[preprocessor/preprocessor.go, line 245 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuiB2f-3jMWBtrQwA:-L32TVKprKUT2rsLt7xS:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/preprocessor/preprocessor.go#L245)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It looks like you have left some code behind. You can remove the comment or make it more clear like `// All inputFiles`
</blockquote></details>

Done.

---

*[travis/test.sh, line 111 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuEewfgbF9Th9LWBb:-L32TZv-BQfg8ySJ5kFl:b-7nrqrg) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/travis/test.sh#L111)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You are already transpiling this above. Why do it again?
</blockquote></details>

Just for see with different between present design and design of multifiles in that PR.
Few PRs ago - it is look:
```
Transpiling shell.c...
Transpiling sqlite3.c...
In files (sqlite3.go and shell.go) summary :    11153 warnings.
After transpiling shell.c and sqlite3.c together, have summary:    10933 warnings.
```
Different ~200 warnings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384)*

**Comment by Konstantin8105** [comment]
Now I add `gometalinter`:
```
----------------------
Transpiling shell.c...
Transpiling sqlite3.c...
In files (sqlite3.go and shell.go) summary : 7211 warnings.
After transpiling shell.c and sqlite3.c together, have summary: 6998 warnings.
Amount gometalinter warnings: 148823 warnings.
```

**Comment by elliotchance** [comment]
Reviewed 3 of 5 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[main_test.go, line 162 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L32RxoQ0_w8CijY4VlB:-L3AQJH8CkJqAVfUJdPm:blm7bli) ([raw file](https://github.com/elliotchance/c2go/blob/aea421cd0c9c962afce717346c0c7956e0873f1f/main_test.go#L162)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

> Yes. Warning without that lines:
```
=== RUN   TestIntegrationScripts/tests/assert.c
TAP: # Total tests: 0
--- FAIL: TestIntegrationScripts (1.21s)
    --- FAIL: TestIntegrationScripts/tests/assert.c (1.21s)
    	main_test.go:165: Expected a.out: tests/assert.c:12: void print_number(int *): Assertion `myInt != NULL' failed.
    		
    		Got: a.out: /home/konstantin/go/src/github.com/elliotchance/c2go/tests/assert.c:12: void print_number(int *): Assertion `myInt != NULL' failed.
FAIL
exit status 1
```

</blockquote></details>

I don't understand why this is changing now. Did the functionality of `__FILE__` also change? I see you are creating absolute paths below. If you have to do that then you should keep a map of the original relative paths to substitute in the code so this isn't needed.

---

*[preprocessor/preprocessor.go, line 275 at r7](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L3ARRwJ497OMdKcgzyN:-L3ARRwKl0XnZRc_6o8O:b-a7v2nz) ([raw file](https://github.com/elliotchance/c2go/blob/208dfb10abe19f274af069d13f518625515f2695/preprocessor/preprocessor.go#L275)):*
> ```Go
> 		inputFiles[i], err = filepath.Abs(inputFiles[i])
> 		if err != nil {
> 			return
> ```

The error isn't handled, it will silently give up on error.

---

*[travis/test.sh, line 111 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuEewfgbF9Th9LWBb:-L3AR_Ngh5RwZjGPloNS:bwx8vpf) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/travis/test.sh#L111)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Just for see with different between present design and design of multifiles in that PR.
Few PRs ago - it is look:
```
Transpiling shell.c...
Transpiling sqlite3.c...
In files (sqlite3.go and shell.go) summary :    11153 warnings.
After transpiling shell.c and sqlite3.c together, have summary:    10933 warnings.
```
Different ~200 warnings.
</blockquote></details>

Ah OK, so it's debugging code. Please remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384)*

**Comment by Konstantin8105** [comment]
Could you merge #558

**Comment by elliotchance** [comment]
I'll wait un til #558 is merged before reviewing this.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L3Px5opJ46ZoJFOJL1C:b6s9ehs)*

**Comment by Konstantin8105** [comment]
Yes, you can merge that PR before or after #558.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[travis/test.sh, line 111 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuEewfgbF9Th9LWBb:-L3Rq96ijbloEy5LQyzb:b7t07oi) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/travis/test.sh#L111)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Generally, that PR is not good for you in according to https://github.com/elliotchance/c2go/pull/384#issuecomment-350113423 .
If it acceptable for you now, then I will remove.
Could you clarify.
</blockquote></details>

Now output is:
```
----------------------
Transpiling shell.c...
Transpiling sqlite3.c...
In files (sqlite3.go and shell.go) summary : 7211 warnings.
After transpiling shell.c and sqlite3.c together, have summary: 6998 warnings.
Amount gometalinter warnings: 148823 warnings.
```
What exactly - you want to remove.

Line can be removed, you don't compare the results:
```
In files (sqlite3.go and shell.go) summary : 7211 warnings.
```
That line cannot be removed, because it is use that PR algorithm of transpilation:
```
After transpiling shell.c and sqlite3.c together, have summary: 6998 warnings.
```
That line can be removed, if you want to see amount of all problems:
```
Amount gometalinter warnings: 148823 warnings.
```
Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384#-:-L3Rq27Dnl52TJF7z43U:bqndmkl)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/test.sh, line 111 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L2vuEewfgbF9Th9LWBb:-L3h92T25UOHETDK75Sj:b2nhll9) ([raw file](https://github.com/elliotchance/c2go/blob/3ded07512c4440a0a27519a49639f07a8db7a65d/travis/test.sh#L111)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm sorry, I understand the difference now. This is fine.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384)*

**Comment by Konstantin8105** [comment]
Dear @elliotchance 
In according to our discussion, that PR ready for merge.

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[main_test.go, line 162 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/384#-L32RxoQ0_w8CijY4VlB:-L4o36ZOXoVpFZZDAr5U:b-ys12uy) ([raw file](https://github.com/elliotchance/c2go/blob/aea421cd0c9c962afce717346c0c7956e0873f1f/main_test.go#L162)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I don't understand why this is changing now. Did the functionality of `__FILE__` also change? I see you are creating absolute paths below. If you have to do that then you should keep a map of the original relative paths to substitute in the code so this isn't needed.
</blockquote></details>

In according https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html:
```
For example, "/usr/local/include/myheader.h" is a possible expansion of this macro.
```
So, absolute path is acceptable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/384)*

**Pull request merged**
