### PR TITLE
Better error reporting when binary expressions cannot be transpiled

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/468)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[transpiler/binary.go, line 49 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/468#-L0MEYg4w8aOGA4b2HmM:-L0MEYg4w8aOGA4b2HmN:b-cecn7o) ([raw file](https://github.com/elliotchance/c2go/blob/70a2980820ef328414462e04a07317376feea6f0/transpiler/binary.go#L49)):*
> ```Go
> func transpileBinaryOperator(n *ast.BinaryOperator, p *program.Program, exprIsStmt bool) (
> 	_ goast.Expr, resultType string, preStmts []goast.Stmt, postStmts []goast.Stmt, err error) {
> 	defer func() {
> ```

Where is the panic being thrown from? If the panic is thrown by us we should replace it with a more graceful error. If the panic cannot be avoided a comment as to how this situation occurs would be helpful.

---

*[types/resolve.go, line 258 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/468#-L0MErPbrg51M6AOIEJQ:-L0MErPbrg51M6AOIEJR:bhbqkff) ([raw file](https://github.com/elliotchance/c2go/blob/70a2980820ef328414462e04a07317376feea6f0/types/resolve.go#L258)):*
> ```Go
> // ResolveFunction determines the Go type from a C type.
> func ResolveFunction(p *program.Program, s string) (fields []string, returns []string, err error) {
> 	defer func() {
> ```

Same as comment above.

---

*[types/resolve.go, line 301 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/468#-L0MEtLu3tSADbmsxn2z:-L0MEtLu3tSADbmsxn3-:bhbqkff) ([raw file](https://github.com/elliotchance/c2go/blob/70a2980820ef328414462e04a07317376feea6f0/types/resolve.go#L301)):*
> ```Go
> // ParseFunction - parsing elements of C function
> func ParseFunction(s string) (f []string, r []string, err error) {
> 	defer func() {
> ```

Same as comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/468)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[transpiler/binary.go, line 49 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/468#-L0MEYg4w8aOGA4b2HmM:-L0PNxKg7UqYnwalYF8C:bx51lct) ([raw file](https://github.com/elliotchance/c2go/blob/70a2980820ef328414462e04a07317376feea6f0/transpiler/binary.go#L49)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Where is the panic being thrown from? If the panic is thrown by us we should replace it with a more graceful error. If the panic cannot be avoided a comment as to how this situation occurs would be helpful.
</blockquote></details>

I think, I understood.
In according to https://blog.golang.org/defer-panic-and-recover:
```go
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered in f", r)
        }
    }()
```
This is typical part of code for handling the `panic`, but it is only about ` if r := recover(); ` and not about `defer`.
Function `defer` is used for  execute part of code after end of function. https://tour.golang.org/flowcontrol/12 , https://tour.golang.org/flowcontrol/13 .
In my case, we use `defer` for handling error, in detail: if function have error, then add "Cannot transpile ..." at begin of error. It is not about `panic - recover` working.
```go
	defer func() {
		if err != nil {
			err = fmt.Errorf("Cannot transpile BinaryOperator : result type = {%s}. Error: %v", resultType, err)
		}
	}()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/468)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/binary.go, line 49 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/468#-L0MEYg4w8aOGA4b2HmM:-L0cGXJqXXOKayq1TtwM:b-j01wca) ([raw file](https://github.com/elliotchance/c2go/blob/70a2980820ef328414462e04a07317376feea6f0/transpiler/binary.go#L49)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I think, I understood.
In according to https://blog.golang.org/defer-panic-and-recover:
```go
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered in f", r)
        }
    }()
```
This is typical part of code for handling the `panic`, but it is only about ` if r := recover(); ` and not about `defer`.
Function `defer` is used for  execute part of code after end of function. https://tour.golang.org/flowcontrol/12 , https://tour.golang.org/flowcontrol/13 .
In my case, we use `defer` for handling error, in detail: if function have error, then add "Cannot transpile ..." at begin of error. It is not about `panic - recover` working.
```go
	defer func() {
		if err != nil {
			err = fmt.Errorf("Cannot transpile BinaryOperator : result type = {%s}. Error: %v", resultType, err)
		}
	}()
```

</blockquote></details>

Sorry, I did not understand the code. I thought you were catching a panic but that is not the case. This is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/468)*

**Comment by Konstantin8105** [comment]
:+1:

**Pull request merged**
