### PR TITLE
Minor

### PR DESCRIPTION
**Pull request by Konstantin8105**
Find place for solving one of case for https://github.com/elliotchance/c2go/issues/154

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/176)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Fix #174

**Comment by elliotchance** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 109 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRqKCQuJLiQbO8bzzt:-KnRqKCQuJLiQbO8bzzu:bgd7re4) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/main.go#L109)):*
> ```Go
> }
> 
> /* Dead code
> ```

You can remove this completely.

---

*[main.go, line 254 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRqrK46YFoBmVr4UrD:-KnRqrK46YFoBmVr4UrE:b-258enj) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/main.go#L254)):*
> ```Go
> 		flag.PrintDefaults()
> 
> 		// print flags of transpile command
> ```

I understand what you are trying to do here, but this is not an appropriate way to do it. Each mode would have to be separate.

Please undo this change as I have created a ticket to clean this up: https://github.com/elliotchance/c2go/issues/177

---

*[types/binary_operator.go, line 26 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRsL6xjSM1xNX_h3v9:-KnRsL6xjSM1xNX_h3vA:bn0302d) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/types/binary_operator.go#L26)):*
> ```Go
> 	*/
> 	if operator == "," {
> 		panic("Now, Algorithm is not fully ready")
> ```

This message is not helpful and also stops the execution of the script. It is better to output code that is broken than stopping the entire process.

You should raise a warning so c2go can keep going:

```go
err := errors.New("Cannot use comma in a for loop. See https://github.com/elliotchance/c2go/issues/154#issuecomment-310768001")
p.AddMessage(ast.GenerateWarningMessage(err, n))
```

The `n` will be the original `ast.Node` that caused the problem. You don't have the node in this scope so you will have to return an error here and handle it properly by the function that calls this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/176)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 109 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRqKCQuJLiQbO8bzzt:-KnTbQ_JGyarxlq8P8R4:bb6un1j) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/main.go#L109)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You can remove this completely.
</blockquote></details>

Done

---

*[main.go, line 254 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRqrK46YFoBmVr4UrD:-KnTcYNE6JeCkwi32K5a:bb6un1j) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/main.go#L254)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I understand what you are trying to do here, but this is not an appropriate way to do it. Each mode would have to be separate.

Please undo this change as I have created a ticket to clean this up: https://github.com/elliotchance/c2go/issues/177
</blockquote></details>

Done

---

*[types/binary_operator.go, line 26 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnRsL6xjSM1xNX_h3v9:-KnTnHrugkCYYolYQ3-M:bip1ju4) ([raw file](https://github.com/elliotchance/c2go/blob/a875e68c3e559b42d993f9cdff93e7bf3879878a/types/binary_operator.go#L26)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This message is not helpful and also stops the execution of the script. It is better to output code that is broken than stopping the entire process.

You should raise a warning so c2go can keep going:

```go
err := errors.New("Cannot use comma in a for loop. See https://github.com/elliotchance/c2go/issues/154#issuecomment-310768001")
p.AddMessage(ast.GenerateWarningMessage(err, n))
```

The `n` will be the original `ast.Node` that caused the problem. You don't have the node in this scope so you will have to return an error here and handle it properly by the function that calls this function.
</blockquote></details>

In present pull request, I just remove code and think more about that for solving.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/176)*

**Comment by elliotchance** [comment]
I feel like you have no purpose for this pull request. You are just constantly making changes. Open a pull request for each separate thing you want to change with a title on the pull request.

Once you open a pull request the work should be complete, don't leave TODOs and debugging code lying around. Treat an open PR as production quality code.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[main.go, line 173 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWWS3hCMwvNi700hDj:-KnWWS3iFb5drsI2QLii:b-3as6xv) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/main.go#L173)):*
> ```Go
> 	}
> 
> 	err = ioutil.WriteFile(args.outputFile, []byte(p.String()), 0755)
> ```

Restore this back to what it was. I have added an explanation in `main()`

---

*[main.go, line 267 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWWlXKUnUs1CIjj62m:-KnWWlXKUnUs1CIjj62n:b-h2q4w5) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/main.go#L267)):*
> ```Go
> 	}
> 
> 	// Prepare output file name
> ```

Move this back to where it was. The `main` function should only be a proxy to the Start which is the real main function.

---

*[tests/for.c, line 48 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWX5amweIkBuOWS-XH:-KnWX5amweIkBuOWS-XI:b-bk748p) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/tests/for.c#L48)):*
> ```C
>     }
> 
> 	diag("Very big name of argument");	
> ```

Did you encounter an error with long variable names? How long is the variable name?

---

*[tests/for.c, line 55 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWXBEMYamNj7hJYCCk:-KnWXBEMYamNj7hJYCCl:b-6ckno1) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/tests/for.c#L55)):*
> ```C
> 		pass("%d", veryBigNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee); 
> 	}	
> /*
> ```

Why did you disable all the rest of the tests?

---

*[transpiler/branch.go, line 144 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWXL3upx8tsxfEwt86:-KnWXL3upx8tsxfEwt87:b-1f2vb4) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/transpiler/branch.go#L144)):*
> ```Go
> 			//
> 			//lastIndex := len(c.Children) - 1
> 			// TODO
> ```

Fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/176#-:-KnWXhHJ96cKoiWzycOX:b-s0fq29)*

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[main_test.go, line 65 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnX8uUn8OKeDfnDWjTn:-KnX8uUoYlPSriVxQlnn:byft6kf) ([raw file](https://github.com/elliotchance/c2go/blob/b046da01e392d0d71aac24a0d518d3e8ce83bb36/main_test.go#L65)):*
> ```Go
> 	// Create build folder
> 	os.Mkdir("build/", os.ModePerm)
> 	defer os.RemoveAll("build")
> ```

It makes more sense to clean up before you start, not when you finish. Any files left over as part of the build should remain for debugging.

It's probably unnecessary to clean up at all. It can hide potential issues that would otherwise be caught by testing. For example, what happens if it needs to replace a file or there other files lying around that might effect future tests.

---

*[tests/for.c, line 59 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnXAQCwU6SkfqMh1lno:-KnXAQCwU6SkfqMh1lnp:bd811y1) ([raw file](https://github.com/elliotchance/c2go/blob/b046da01e392d0d71aac24a0d518d3e8ce83bb36/tests/for.c#L59)):*
> ```C
> 		j++;
> 	}
> /*
> ```

You have commented out tests here.

---

*[transpiler/branch.go, line 145 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnX9thYWdedEO7rpjdh:-KnX9thYWdedEO7rpjdi:b9mxwrv) ([raw file](https://github.com/elliotchance/c2go/blob/b046da01e392d0d71aac24a0d518d3e8ce83bb36/transpiler/branch.go#L145)):*
> ```Go
> 			//
> 			//lastIndex := len(c.Children) - 1
> 			if len(c.Children) != 2 {
> ```

Why is this required to be here at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/176)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[main.go, line 173 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWWS3hCMwvNi700hDj:-KnYZyMmJFpg2uvzv2ju:bkuq5zw) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/main.go#L173)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Restore this back to what it was. I have added an explanation in `main()`
</blockquote></details>

Return back.

---

*[main.go, line 267 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWWlXKUnUs1CIjj62m:-KnY_-pAdbAttZj_0oaW:b-hnol7y) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/main.go#L267)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Move this back to where it was. The `main` function should only be a proxy to the Start which is the real main function.
</blockquote></details>

Return back

---

*[tests/for.c, line 48 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWX5amweIkBuOWS-XH:-KnY_PNzIlPsUwvADuJk:b1z60ci) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/tests/for.c#L48)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Did you encounter an error with long variable names? How long is the variable name?
</blockquote></details>

Excuse me for fail information. I just that, but don`t found any bug about lenght of name.

---

*[tests/for.c, line 55 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWXBEMYamNj7hJYCCk:-KnY_cadvv1pTVn1QhXa:bas5m1f) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/tests/for.c#L55)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why did you disable all the rest of the tests?
</blockquote></details>

Remove other. Yes I solve problem only with 2 init parameter in "For". I will add after solving problem fully

---

*[tests/for.c, line 59 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnXAQCwU6SkfqMh1lno:-KnYaBmgxaaOxCBrKfHW:b-t5w4sr) ([raw file](https://github.com/elliotchance/c2go/blob/b046da01e392d0d71aac24a0d518d3e8ce83bb36/tests/for.c#L59)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You have commented out tests here.
</blockquote></details>

Remove. This is  only for future. I didn`t solve the problem fully.
If acceptable - commented test`s for indicate the bug, then Please clarify.

---

*[transpiler/branch.go, line 144 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnWXL3upx8tsxfEwt86:-KnYcRyfUX5pvpdWOB6R:b-xgo9wy) ([raw file](https://github.com/elliotchance/c2go/blob/db046edd5956133e78ef30d7267e6828096d65cf/transpiler/branch.go#L144)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Fix this.
</blockquote></details>

After testing Binary Operation have only 2 children. Remove that panic.

---

*[transpiler/branch.go, line 145 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/176#-KnX9thYWdedEO7rpjdh:-KnYbM5v-PT6BP-KDvSA:b8gcq85) ([raw file](https://github.com/elliotchance/c2go/blob/b046da01e392d0d71aac24a0d518d3e8ce83bb36/transpiler/branch.go#L145)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why is this required to be here at all?
</blockquote></details>

I put in function for, because Go cannot use operation comma like C. I try to clarify here https://github.com/elliotchance/c2go/issues/154. If we found comma in ForInitialization, then we have to move initiazation before operator For.
Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/176)*

**Comment by Konstantin8105** [comment]
Excuse me @elliotchance, I close the pull request and we return back after complete solving "Comma" problem.
I will follow your opinion - separate different task by different pull requests.

**Pull request closed without merging**
