### PR TITLE
Pointer arith. with size_t. Fix #618, #620

### LINKED ISSUE #618: pointer arith. size_t
```c
          size_t size;
          char *left_ptr;
          char *lo = base_ptr;
	  left_ptr  = lo + size;// <- problem here
```

### LINKED ISSUE #620: Pointer arith.
```c
      size_t size = ...;
      char *lo    = ...;
      char *hi    = ...;
      char *mid   = lo + size * ((hi - lo) / size >> 1);
//                               --------
//                            Problem here
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #618
Close #620

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/619)

### CODE REVIEW

**Comment by elliotchance** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/619#-L4wyI-SisB-_omXIyi7:-L4wyI-SisB-_omXIyi8:bukylqg) (no related file):*
I'll review when merge conflicts are resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/619)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/619#-L4wyI-SisB-_omXIyi7:-L4yAg7yFIb1Pbr0TLzY:b-el33eg) (no related file):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'll review when merge conflicts are resolved.
</blockquote></details>

Done. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/619)*

**Comment by elliotchance** [comment]
Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/binary.go, line 241 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/619#-L5BcwaqX3CF9YpCfYMh:-L5BcwaqX3CF9YpCfYMi:b-hdro56) ([raw file](https://github.com/elliotchance/c2go/blob/f851423cf9d3d2bc4a6e07c46e983457f1152152/transpiler/binary.go#L241)):*
> ```Go
> 		return nil, "unknown53", nil, nil, err
> 	}
> 	if types.IsPointer(leftType) && types.IsPointer(rightType) && operator == token.SUB {
> ```

Why does this only work with `SUB`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/619)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/binary.go, line 241 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/619#-L5BcwaqX3CF9YpCfYMh:-L5DtltPadLLCwcIE_86:bnoaxa) ([raw file](https://github.com/elliotchance/c2go/blob/f851423cf9d3d2bc4a6e07c46e983457f1152152/transpiler/binary.go#L241)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why does this only work with `SUB`?
</blockquote></details>

I see in practice only operation `SUB` and it is logical for me.
`Pointer1 - Pointer2` is that case mean `Address of pointer 1  -(minus)- Address of pointer2` . Address is unsigned int of position in RAM(memory).
So, operations `+`, `*`, ... is not logically for me and I don't see anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/619)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/619)*

**Pull request merged**
