### PR TITLE
Add snapshot testing for command help output

### PR DESCRIPTION
**Pull request by bradleyjkemp**
Saw #190 and it seems a great use case for a testing tool I was writing which automagically handles the creating and updating of snapshots from test cases: https://github.com/bradleyjkemp/cupaloy

I've put together this PR mainly as a test of my api but it might be useful to you too.

PR involved some minor changes to allow redirecting stderr and being able to run the command without os.Exit(1) failing the test which you might have some opinions on a better way to do this.

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/209)

### CODE REVIEW

**Comment by elliotchance** [comment]
Love it! I think this is a great solution.

I'm curious as to how the Travis build passed? I would expect it to fail since `go get` is not fetching `bradleyjkemp/cupaloy`. Perhaps the tests are not running?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli_test.go, line 25 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr38KOXvgH7lcpyM4RK:-Kr38KOXvgH7lcpyM4RL:b-6r1qbd) ([raw file](https://github.com/elliotchance/c2go/blob/3d5cf313548c66321f5d1eef4f12dfe5d38d1264/cli_test.go#L25)):*
> ```Go
> 
> // Test that help is printed if no files are given
> func TestTranspileNoFilesHelp(t *testing.T) {
> ```

I can see us having potentially a lot of these tests. I'm not sure how it knows which test relates to which output. Is it possible to write it as a provider like?

```go
var cliTests = map[string]struct{
    args []string
}{
    // Test that help is printed if no files are given
    "TranspileNoFilesHelp": []string{"test", "transpile"},

    // Test that help is printed if help flag is set, even if file is given
    "TranspileHelpFlag": []string{"test", "transpile", "-h", "foo.c"},

    // ...
}

func TestCLI(t *testing.T) {
    for testName, test := range cliTests {
        t.Run(testName, func (t *testing.T) {
            output, teardown := setupTest(test.args)
            defer teardown()
         
            runCommand()
            err := cupaloy.Snapshot(output.String())
            if err != nil {
                t.Fatalf("error: %s", err)
            }
        })
    }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209#-:-Kr37_c42Q5TZkmS9rQb:b-cr6yzu)*

**Comment by bradleyjkemp** [comment]
Seems that, as part of setup, Travis go gets all dependencies: https://travis-ci.org/elliotchance/c2go/jobs/262424935#L438 so that shouldn't be an issue.
However, I only see "Unit tests: 303" printed (vs 300 for the latest build of master) whereas I'd expect to see 304? I'll check what's going on

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli_test.go, line 25 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr38KOXvgH7lcpyM4RK:-Kr5-5GwuwMek96mRN1-:b-oaoeld) ([raw file](https://github.com/elliotchance/c2go/blob/3d5cf313548c66321f5d1eef4f12dfe5d38d1264/cli_test.go#L25)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I can see us having potentially a lot of these tests. I'm not sure how it knows which test relates to which output. Is it possible to write it as a provider like?

```go
var cliTests = map[string]struct{
    args []string
}{
    // Test that help is printed if no files are given
    "TranspileNoFilesHelp": []string{"test", "transpile"},

    // Test that help is printed if help flag is set, even if file is given
    "TranspileHelpFlag": []string{"test", "transpile", "-h", "foo.c"},

    // ...
}

func TestCLI(t *testing.T) {
    for testName, test := range cliTests {
        t.Run(testName, func (t *testing.T) {
            output, teardown := setupTest(test.args)
            defer teardown()
         
            runCommand()
            err := cupaloy.Snapshot(output.String())
            if err != nil {
                t.Fatalf("error: %s", err)
            }
        })
    }
}
```
</blockquote></details>

That's a good point, this would eliminate all the current boilerplate. I'll update the PR to use table driven tests.

cupaloy uses the name of the calling function to infer which snapshot file to read so Snapshot() cannot be called multiple times from the same test function. But, there's cupaloy.SnapshotMulti(testName, value) though which can be called multiple times as long as testName is unique so this would work for table driven tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209#-:-Kr4zJwcxfCnTRE1FzDh:b-9kqy2b)*

**Comment by bradleyjkemp** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli_test.go, line 25 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr38KOXvgH7lcpyM4RK:-Kr7VRyrDsAnOUuEn3KE:bgcg75k) ([raw file](https://github.com/elliotchance/c2go/blob/3d5cf313548c66321f5d1eef4f12dfe5d38d1264/cli_test.go#L25)):*
<details><summary><i>Previously, bradleyjkemp wrote…</i></summary><blockquote>

That's a good point, this would eliminate all the current boilerplate. I'll update the PR to use table driven tests.

cupaloy uses the name of the calling function to infer which snapshot file to read so Snapshot() cannot be called multiple times from the same test function. But, there's cupaloy.SnapshotMulti(testName, value) though which can be called multiple times as long as testName is unique so this would work for table driven tests.
</blockquote></details>

Done. (moved to table driven tests and use cupaloy.SnapshotMulti() to perform multiple snapshots from the same function)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209)*

**Comment by bradleyjkemp** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli_test.go, line 25 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr38KOXvgH7lcpyM4RK:-Kr7dRG6Uw1nydv_LEgB:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/3d5cf313548c66321f5d1eef4f12dfe5d38d1264/cli_test.go#L25)):*
<details><summary><i>Previously, bradleyjkemp wrote…</i></summary><blockquote>

Done. (moved to table driven tests and use cupaloy.SnapshotMulti() to perform multiple snapshots from the same function)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209)*

**Comment by elliotchance** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.snapshots/c2go-TestCLI-func1-AstHelpFlag, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr7yCdLB4bPL1JxjF2S:-Kr7yCdLB4bPL1JxjF2T:b7ngwql) ([raw file](https://github.com/elliotchance/c2go/blob/3805fdd67cff30d7b9ec77ff539699286e728ea7/.snapshots/c2go-TestCLI-func1-AstHelpFlag#L1)):*
> ```
> (string) (len=51) "Usage: test ast file.c\n  -h\tprint help information\n"
> ```

It looks like there are duplicate result files. 8 snapshot files for 4 tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209)*

**Comment by bradleyjkemp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.snapshots/c2go-TestCLI-func1-AstHelpFlag, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr7yCdLB4bPL1JxjF2S:-Kr8-HTWuYRr0dpcxeQ7:b-3qjlmh) ([raw file](https://github.com/elliotchance/c2go/blob/3805fdd67cff30d7b9ec77ff539699286e728ea7/.snapshots/c2go-TestCLI-func1-AstHelpFlag#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It looks like there are duplicate result files. 8 snapshot files for 4 tests.
</blockquote></details>

Really? I can only see 4 snapshot files (on github and reviewable)
Moving to table driven tests did change the names of the snapshot files but I deleted the old ones. Are you seeing the old c2go-TestAstHelpFlag as well as the new c2go-TestCLI-func1-AstHelpFlag then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.snapshots/c2go-TestCLI-func1-AstHelpFlag, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/209#-Kr7yCdLB4bPL1JxjF2S:-Kr81Xj0D95enBlpm-ys:b-yn0y8e) ([raw file](https://github.com/elliotchance/c2go/blob/3805fdd67cff30d7b9ec77ff539699286e728ea7/.snapshots/c2go-TestCLI-func1-AstHelpFlag#L1)):*
<details><summary><i>Previously, bradleyjkemp wrote…</i></summary><blockquote>

Really? I can only see 4 snapshot files (on github and reviewable)
Moving to table driven tests did change the names of the snapshot files but I deleted the old ones. Are you seeing the old c2go-TestAstHelpFlag as well as the new c2go-TestCLI-func1-AstHelpFlag then?
</blockquote></details>

Ah you're right. I think I was reviewing right at the moment when you were pushing the changes. All good! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209)*

**Comment by elliotchance** [comment]
Let me know when you are happy with this and I'll merge it in.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209#-:-Kr81pvUPFOIDPmN5a9h:bh0x4i9)*

**Comment by bradleyjkemp** [comment]
Yep, I'm happy for this to be merged :)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/209#-:-Kr85PDa16G3s2EfXV0D:b-y0em1o)*

**Comment by elliotchance** [comment]
Thanks @bradleyjkemp! https://github.com/elliotchance/c2go/releases/tag/v0.14.2

**Pull request merged**
