### PR TITLE
added rexeg cache for utils-goast

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/241)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/goast.go, line 17 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/241#-KwbjuRTSBcmvUkTN3jV:-KwbjuRTSBcmvUkTN3jW:b-it7qwd) ([raw file](https://github.com/elliotchance/c2go/blob/26b47521855971a6773bcc84ee7516f8441a4778/util/goast.go#L17)):*
> ```Go
> var cachedRegex = map[string]*regexp.Regexp{}
> 
> func getRegex(rx string) *regexp.Regexp {
> ```

This is great! Please move this function and `cachedRegex` to `util/regexp.go`. Then refactor this code https://github.com/elliotchance/c2go/pull/236/files#diff-a65b8f172aa8575e2e6d5cf7208e26daR226 to use this function instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/goast.go, line 17 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/241#-KwbjuRTSBcmvUkTN3jV:-Kwdp1KnGurjj7VGDgQY:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/26b47521855971a6773bcc84ee7516f8441a4778/util/goast.go#L17)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is great! Please move this function and `cachedRegex` to `util/regexp.go`. Then refactor this code https://github.com/elliotchance/c2go/pull/236/files#diff-a65b8f172aa8575e2e6d5cf7208e26daR226 to use this function instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/goast.go, line 17 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/241#-KwbjuRTSBcmvUkTN3jV:-Kwe1wDuadpBSXRRJbLN:b-4oa0zv) ([raw file](https://github.com/elliotchance/c2go/blob/26b47521855971a6773bcc84ee7516f8441a4778/util/goast.go#L17)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After that PR, I will create a PR for using util/regex in ast/ast.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 20 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/241#-KwgdIk_THEtgsXb2HSk:-KwgdIk_THEtgsXb2HSl:bqfwl1x) ([raw file](https://github.com/elliotchance/c2go/blob/f920e766d00843dd3eb2e9e896692e41bb04f79e/types/cast.go#L20)):*
> ```Go
> var cachedRegexTypes = map[string]*regexp.Regexp{}
> 
> func getRegexTypes(rx string) *regexp.Regexp {
> ```

Remove this and `cachedRegexTypes` above. All packages can use `util.GetRegex`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/cast.go, line 20 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/241#-KwgdIk_THEtgsXb2HSk:-KwlBm3RwSEHDZBurvwe:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f920e766d00843dd3eb2e9e896692e41bb04f79e/types/cast.go#L20)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Remove this and `cachedRegexTypes` above. All packages can use `util.GetRegex`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/241)*

**Comment by elliotchance** [comment]
Thanks, great work! 👍

**Pull request merged**
