### PR TITLE
Char overflow. Fixes #590

### LINKED ISSUE #590: char overflow
C:
```c
char c;
c = (-1); // Overflow
c = -1; // Overflow
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #590

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/591)

### CODE REVIEW

**Comment by elliotchance** [comment]
Please resolve the merge conflicts, then I will review.

---

Review status: 0 of 110 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/591#-:-L3o_vccsttsinfPszFS:b5w7lc9)*

**Comment by Konstantin8105** [comment]
ready for review

**Comment by elliotchance** [comment]
Reviewed 2 of 110 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/operators.go, line 594 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/591#-L3u6AgfNZJYaQOuR4Y1:-L3u6AgfNZJYaQOuR4Y2:b-8h6ky9) ([raw file](https://github.com/elliotchance/c2go/blob/c5b66bd66b33c3e3301d84801abbe2e986c66c0d/transpiler/operators.go#L594)):*
> ```Go
> 				var u *ast.UnaryOperator
> 
> 				findUnaryWithInteger = func(node ast.Node) {
> ```

Please do not create anonymous functions, it makes the code unnecessarily complicated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/591)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/operators.go, line 594 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/591#-L3u6AgfNZJYaQOuR4Y1:-L4tKQzEeZKQyncaD8cj:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/c5b66bd66b33c3e3301d84801abbe2e986c66c0d/transpiler/operators.go#L594)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please do not create anonymous functions, it makes the code unnecessarily complicated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/591)*

**Comment by Konstantin8105** [comment]
That PR included in PR #605

**Pull request closed without merging**
