### PR TITLE
Function free(). Fixes #123

### LINKED ISSUE #123: Remove calls to free()
`free()` is not required in Go because it has automatic memory management. However, this relates to a larger issue of having code removed, rather than just transpiled directly.

### PR DESCRIPTION
**Pull request by Konstantin8105**
Created for #123

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/255)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 283 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/255#-Kx5i3Iw5JIj9UImpRFI:-Kx5i3Iw5JIj9UImpRFJ:b3ovcwy) ([raw file](https://github.com/elliotchance/c2go/blob/5ace69ad9765f9db57be2bd63b293f5a28f2f9e7/transpiler/transpiler.go#L283)):*
> ```Go
> 	}
> 
> 	// Injection for specific implementation of function `free`
> ```

This looks like a very brittle way to do it. It would be better to use the function definitions: https://github.com/elliotchance/c2go/blob/master/program/function_definition.go#L180

Should be:

```
	"void free(void*) -> _",
```

Update the function substituter to allow removing of any function like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/255)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 283 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/255#-Kx5i3Iw5JIj9UImpRFI:-KxeBYWbRZ0qzZwIfwae:bb7f2mf) ([raw file](https://github.com/elliotchance/c2go/blob/5ace69ad9765f9db57be2bd63b293f5a28f2f9e7/transpiler/transpiler.go#L283)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This looks like a very brittle way to do it. It would be better to use the function definitions: https://github.com/elliotchance/c2go/blob/master/program/function_definition.go#L180

Should be:

```
	"void free(void*) -> _",
```

Update the function substituter to allow removing of any function like this.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/255)*

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[program/function_definition.go, line 198 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeOpyVanqvI_YB_0NL:-KxeOpyVanqvI_YB_0NM:b-dl13u1) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/program/function_definition.go#L198)):*
> ```Go
> 	"long unsigned int strtoul(const char *, char **, int) -> noarch.Strtoul",
> 	"long long unsigned int strtoull(const char *, char **, int) -> noarch.Strtoull",
> 	"void free(void*) -> _",
> ```

Nice! :thumbsup: 

---

*[program/import.go, line 18 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxePADj5t6YbUDJRUnC:-KxePADj5t6YbUDJRUnD:b253dy3) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/program/import.go#L18)):*
> ```Go
> 	quotedImportPath := strconv.Quote(importPath)
> 
> 	if len(importPath) == 0 {
> ```

Is these a special reason for this? If there are no elements in the `importPath` it should have the same effect.

---

*[tests/stdlib.c, line 157 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxePxYO__qT_x5MMvzr:-KxePxYO__qT_x5MMvzs:b3lo446) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/tests/stdlib.c#L157)):*
> ```C
> void test_free()
> {
> 	diag("free");
> ```

You can remove this line (you have the same line below).

---

*[transpiler/call.go, line 213 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeQ7XTA21lZ3uK4ePT:-KxeQ7XTA21lZ3uK4ePU:bqtp3wl) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/transpiler/call.go#L213)):*
> ```Go
> 	// i += 4
> 	// _ = buffer
> 	if functionName == "_" && functionDef.Name == "free" && functionDef.Substitution == "_" {
> ```

How about simply?

```go
if functionDef.Substitution == "_" {
```

So that `_` will work for any function in the future as well.

---

*[transpiler/call.go, line 245 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeQjTOOWLsqvyxEGDS:-KxeQjTPUPl7n7uv6sQE:b5o8603) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/transpiler/call.go#L245)):*
> ```Go
> 	}
> 
> 	if functionName == "_" {
> ```

There is no need to raise a warning in this case because it perfectly legal in C and not needed in Go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/255)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[program/function_definition.go, line 198 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeOpyVanqvI_YB_0NL:-KxhZXlQIK49ijJsle17:b32wtd) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/program/function_definition.go#L198)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Nice! :thumbsup: 
</blockquote></details>

ok

---

*[program/import.go, line 18 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxePADj5t6YbUDJRUnC:-KxhZ_6P8EWdCkSz7M1m:bh5fdwo) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/program/import.go#L18)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is these a special reason for this? If there are no elements in the `importPath` it should have the same effect.
</blockquote></details>

`_` haven't name of package like `noarch` and without that `if` it is try to add package "".

---

*[tests/stdlib.c, line 157 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxePxYO__qT_x5MMvzr:-Kxh_KsQ19Vo1ndBc0dB:b-7rl0jd) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/tests/stdlib.c#L157)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You can remove this line (you have the same line below).
</blockquote></details>

done.

---

*[transpiler/call.go, line 213 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeQ7XTA21lZ3uK4ePT:-Kxh_U4RSXsyCMk_kaMJ:b-7rl0jd) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/transpiler/call.go#L213)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

How about simply?

```go
if functionDef.Substitution == "_" {
```

So that `_` will work for any function in the future as well.
</blockquote></details>

done.

---

*[transpiler/call.go, line 245 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/255#-KxeQjTOOWLsqvyxEGDS:-Kxh_b9XEld765Y7m3UY:b-l6mwxj) ([raw file](https://github.com/elliotchance/c2go/blob/9c3c11f9b153be1e02a547f2cf30c2fc3dd469b1/transpiler/call.go#L245)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

There is no need to raise a warning in this case because it perfectly legal in C and not needed in Go.
</blockquote></details>

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/255)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/255)*

**Pull request merged**
