### PR TITLE
Add support of 2 or more C source files. Fixes #63

### LINKED ISSUE #63: Compiling multiple files
At the moment all the preprocessed code is output into a single Go file. If there were multiple files process you would get lots of duplicate symbols in the same package.

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #257, #63 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/258)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 301 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6RklJPXgiVC2UHmaa:-Kx6RklJPXgiVC2UHmab:b-w9kvpp) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/main.go#L301)):*
> ```Go
> func runCommand() int {
> 	flag.Usage = func() {
> 		usage := "Usage: %s [-v] [<command>] [<flags>] file.c\n\n"
> ```

Indicate that multiple files can be passed as extra arguments:

`usage := "Usage: %s [-v] [<command>] [<flags>] file1.c ...\n\n"`

---

*[main.go, line 353 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6RuieHqLPKXzhfUUm:-Kx6RuieHqLPKXzhfUUn:b-o26nw0) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/main.go#L353)):*
> ```Go
> 
> 		if *transpileHelpFlag || transpileCommand.NArg() == 0 {
> 			fmt.Fprintf(stderr, "Usage: %s transpile [-V] [-o file.go] [-p package] file.c\n", os.Args[0])
> ```

Same here:

`fmt.Fprintf(stderr, "Usage: %s transpile [-V] [-o file.go] [-p package] file1.c ...\n", os.Args[0])`

---

*[tests/multi/four.c, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6SCnOBhlp9U6qMPOz:-Kx6SCnOBhlp9U6qMPP-:b30ah0a) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/tests/multi/four.c#L1)):*
> ```C
> void say_four(){
> ```

Please add `#include <stdio.h>` so that we can test that no errors are produced when multiple files include the same headers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 301 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6RklJPXgiVC2UHmaa:-Kx96ucbZ8AvHghjsbOm:b-7rl0jd) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/main.go#L301)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Indicate that multiple files can be passed as extra arguments:

`usage := "Usage: %s [-v] [<command>] [<flags>] file1.c ...\n\n"`
</blockquote></details>

done.

---

*[main.go, line 353 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6RuieHqLPKXzhfUUm:-Kx9760Cc84p9fwP2iLO:bs7wumb) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/main.go#L353)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Same here:

`fmt.Fprintf(stderr, "Usage: %s transpile [-V] [-o file.go] [-p package] file1.c ...\n", os.Args[0])`
</blockquote></details>

Done.

---

*[tests/multi/four.c, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6SCnOBhlp9U6qMPOz:-Kx9B5-t932_m13op6oj:b-57p3a8) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/tests/multi/four.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please add `#include <stdio.h>` so that we can test that no errors are produced when multiple files include the same headers.
</blockquote></details>

I change little bit - Is it ok for you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[tests/multi/four.c, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6SCnOBhlp9U6qMPOz:-KxA_rzTq3RtMulk7fwU:bhgxhk3) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/tests/multi/four.c#L1)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I change little bit - Is it ok for you?
</blockquote></details>

`stdio.h` will manage it's own duplicate includes. You need to be able to put `#include <stdio.h>` in several files. Remove all of the `#ifndef` from all of the files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/multi/four.c, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/258#-Kx6SCnOBhlp9U6qMPOz:-KxC5OtlPDB8pMfF5ajk:bm030eh) ([raw file](https://github.com/elliotchance/c2go/blob/ff2f9bdc4b2cd84bb0e4e7c3aa1590904b7baf17/tests/multi/four.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`stdio.h` will manage it's own duplicate includes. You need to be able to put `#include <stdio.h>` in several files. Remove all of the `#ifndef` from all of the files.
</blockquote></details>

Ok. We will see the result in travis, but we have to wait merging branch https://github.com/elliotchance/c2go/pull/270 , because now many fails borned from "typedef struct".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/multi/four.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLoYur9IJskKLSiUd:-KxjLoYur9IJskKLSiUe:bpg55e) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/four.c#L1)):*
> ```C
> #ifdef USE_STDIO
> ```

It needs to work without these preprocessor directives. As normal code would not have them either.

---

*[tests/multi/head.h, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLxt0LV1-d2K9fuG1:-KxjLxt0LV1-d2K9fuG2:bpg55e) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/head.h#L1)):*
> ```objc
> #ifdef USE_STDIO
> ```

It needs to work without these preprocessor directives. As normal code would not have them either.

---

*[tests/multi/two.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLycaRUE_U99J0TxE:-KxjLycaRUE_U99J0TxF:bpg55e) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/two.c#L1)):*
> ```C
> #ifdef USE_STDIO
> ```

It needs to work without these preprocessor directives. As normal code would not have them either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/multi/four.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLoYur9IJskKLSiUd:-KxlLfNAFq3eUogORkjg:b-cstmpl) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/four.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It needs to work without these preprocessor directives. As normal code would not have them either.
</blockquote></details>

I check that option in last commit https://github.com/elliotchance/c2go/pull/258/commits/0aa4566ef36aa06001043a5b6ae0e05e85997937 and dublicates is acceptable for `gcc` , but not for `clang` .
Same way to using `#ifdef` you can see in many project:
https://github.com/DaveGamble/cJSON/blob/master/cJSON.c
https://github.com/sheredom/json.h/blob/master/json.c
Or on discussions:
https://stackoverflow.com/questions/10278494/duplicate-header-files-throughout-source-files
https://en.wikipedia.org/wiki/Include_guard see Use of #include guards

But if that feature is important for you, then I can add that in new `Preprocessor` https://github.com/elliotchance/c2go/pull/273 .

---

*[tests/multi/head.h, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLxt0LV1-d2K9fuG1:-KxlNflgduTFpKatRtku:blkqby6) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/head.h#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It needs to work without these preprocessor directives. As normal code would not have them either.
</blockquote></details>

see upper.

---

*[tests/multi/two.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLycaRUE_U99J0TxE:-KxlNh4iz6_CBmrT0rO1:blkqby6) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/two.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It needs to work without these preprocessor directives. As normal code would not have them either.
</blockquote></details>

see upper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/multi/four.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLoYur9IJskKLSiUd:-KxoMh45ICl5-UdRAn_W:buzk4va) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/four.c#L1)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I check that option in last commit https://github.com/elliotchance/c2go/pull/258/commits/0aa4566ef36aa06001043a5b6ae0e05e85997937 and dublicates is acceptable for `gcc` , but not for `clang` .
Same way to using `#ifdef` you can see in many project:
https://github.com/DaveGamble/cJSON/blob/master/cJSON.c
https://github.com/sheredom/json.h/blob/master/json.c
Or on discussions:
https://stackoverflow.com/questions/10278494/duplicate-header-files-throughout-source-files
https://en.wikipedia.org/wiki/Include_guard see Use of #include guards

But if that feature is important for you, then I can add that in new `Preprocessor` https://github.com/elliotchance/c2go/pull/273 .
</blockquote></details>

I'm familiar with how `#ifdef` works. However it is used to wrap around your own header files in case they are included in multiple places.

I could `#include` standard header files (like `stdio.h`) as many times as I want in every file without issue because the header files themselves already have that built in mechanism.

Also, by using `#ifdef USE_STDIO` you are actually just always *not* including `stdio.h` because `USE_STDIO` is not defined. The pattern you are trying to achieve requires that each file has a different macro name and that you set the macro at least once.

It looks like you are doing this to prevent an error. If it causes an error then this is not an acceptable solution. To be clear the code must compile with:

1. More than one file.
2. More than two files must include the same standard header.
3. No `#ifdef` trickery to avoid errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/multi/four.c, line 1 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KxjLoYur9IJskKLSiUd:-KxwoeCLBthrz4a1g9Ut:brga1dw) ([raw file](https://github.com/elliotchance/c2go/blob/0aa4566ef36aa06001043a5b6ae0e05e85997937/tests/multi/four.c#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm familiar with how `#ifdef` works. However it is used to wrap around your own header files in case they are included in multiple places.

I could `#include` standard header files (like `stdio.h`) as many times as I want in every file without issue because the header files themselves already have that built in mechanism.

Also, by using `#ifdef USE_STDIO` you are actually just always *not* including `stdio.h` because `USE_STDIO` is not defined. The pattern you are trying to achieve requires that each file has a different macro name and that you set the macro at least once.

It looks like you are doing this to prevent an error. If it causes an error then this is not an acceptable solution. To be clear the code must compile with:

1. More than one file.
2. More than two files must include the same standard header.
3. No `#ifdef` trickery to avoid errors.
</blockquote></details>

I will change proprocessor #273 in according to your rules. Please confirm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
**Not ready for review**

**Comment by Konstantin8105** [comment]
**Not ready for review**

**Comment by Konstantin8105** [comment]
:fireworks: Ready for review

**Comment by elliotchance** [comment]
Reviewed 8 of 31 files at r6, 3 of 15 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 281 at r8](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyDK_MsA3rQpjXFafAP:-KyDK_MsA3rQpjXFafAQ:b-17m86j) ([raw file](https://github.com/elliotchance/c2go/blob/4c5301559a3a902c394cde83dcd59eda27c92cd5/main.go#L281)):*
> ```Go
> 	if outputFilePath == "" {
> 		// Choose inputFile for creating name of output file
> 		input := args.inputFiles[len(args.inputFiles)-1]
> ```

Why are you using the last input file as the base for the output file?

---

*[main_test.go, line 332 at r8](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyDKmENnyV43QKLo-iP:-KyDKmENnyV43QKLo-iQ:bnrc6dt) ([raw file](https://github.com/elliotchance/c2go/blob/4c5301559a3a902c394cde83dcd59eda27c92cd5/main_test.go#L332)):*
> ```Go
> 	// Run Go program
> 	var buf bytes.Buffer
> 	cmd := exec.Command("go", "run", args.outputFile)
> ```

So to be clear, multiple input files still generate a single Go output file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 281 at r8](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyDK_MsA3rQpjXFafAP:-KyFX_NdW6NU67vy-G1v:bv8kqi9) ([raw file](https://github.com/elliotchance/c2go/blob/4c5301559a3a902c394cde83dcd59eda27c92cd5/main.go#L281)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why are you using the last input file as the base for the output file?
</blockquote></details>

Yes, It is true. In my point of view, only last file have function `main()`, that the reason, but in you another think - please clarify.

---

*[main_test.go, line 332 at r8](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyDKmENnyV43QKLo-iP:-KyFY76E_cnu62KJ26sX:buiby8t) ([raw file](https://github.com/elliotchance/c2go/blob/4c5301559a3a902c394cde83dcd59eda27c92cd5/main_test.go#L332)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

So to be clear, multiple input files still generate a single Go output file?
</blockquote></details>

Yes. Many C code in input ---> One Go code output.
For present, It is ok(in my point of view). If you see like "Many C code input ---> Many Go code output", then please clarify and create the issue for discussion  in detail. But for that PR, please accepted(I am a affaid, because PR with huge commits).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[main.go, line 281 at r8](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyDK_MsA3rQpjXFafAP:-KyIWbf8mLbbqmrgP0rE:b-u4eu5r) ([raw file](https://github.com/elliotchance/c2go/blob/4c5301559a3a902c394cde83dcd59eda27c92cd5/main.go#L281)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Yes, It is true. In my point of view, only last file have function `main()`, that the reason, but in you another think - please clarify.
</blockquote></details>

I would prefer the first provided file:

```go
input := args.inputFiles[0]
```

I feel it makes more sense from a CLI point of view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyIY8bskg-NdLenLwRh:-KyIY8bskg-NdLenLwRi:bngml63) (no related file):*
This is a great PR and will be the v0.17.0 release. Can you also update https://github.com/elliotchance/c2go/blob/master/travis/test.sh#L86-L89 so that we transpile both sqlite3 files with the same command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by Konstantin8105** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyIY8bskg-NdLenLwRh:-KyKqPVAnKFBgZuHUvXt:b5ez4xt) (no related file):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Could to merge this PR? Now, need to implement a compiler flag - this another good task for PR :).
Your idea is great, but I want in next PR solve:
* transpile both sqlite3 files in according https://sqlite.org/howtocompile.html
* Trigraph sequences #303
* Allow passing include directory to clang #196
And If you want , then you will create v0.17.0 release.
</blockquote></details>

Please confirm design #331 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Comment by elliotchance** [comment]
Reviewed 1 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/258#-KyIY8bskg-NdLenLwRh:-KyNf06krl4s77saMJXH:b5xhg7t) (no related file):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Please confirm design #331 
</blockquote></details>

Yes, that's fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/258)*

**Pull request merged**
