### PR TITLE
Allow struct inside a function. Fixes #344 and #346

### LINKED ISSUE #344: Structure inside function
Example 
```c
int main(){
    struct tt{int i;};
    struct tt t;
    tt.i = 42;
    return 0;
}

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #344, #346 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/345)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[transpiler/declarations.go, line 313 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgKujh3YXeBUtxZQs:-KyhgKujh3YXeBUtxZQt:bgxf5bt) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/declarations.go#L313)):*
> ```Go
> 			return
> 		}
> 	*/
> ```

Uncomment or delete this.

---

*[transpiler/declarations.go, line 367 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgVr1vco4-CSH-xYd:-KyhgVr1vco4-CSH-xYe:b2kejzp) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/declarations.go#L367)):*
> ```Go
> 		if err != nil {
> 			p.AddMessage(p.GenerateWarningMessage(fmt.Errorf("Cannot resolve function : %v", err), n))
> 			err = nil // Hack
> ```

Is there a better explanation about why this is a hack?

---

*[transpiler/declarations.go, line 437 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgeAKy5eRgufMP27-:-KyhgeAKy5eRgufMP270:bu59tlc) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/declarations.go#L437)):*
> ```Go
> 
> 	if len(preStmts) != 0 || len(postStmts) != 0 {
> 		panic("Not acceptable Stmt")
> ```

Do you know of a case that causes this to happen? Also, it should try to continue instead of panicking.

---

*[transpiler/functions.go, line 83 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgtcZ-DBhPTquzyDA:-KyhgtcZ-DBhPTquzyDB:b-9kjs7f) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/functions.go#L83)):*
> ```Go
> 	if functionBody != nil {
> 		body, _, _, _ = transpileToBlockStmt(functionBody, p)
> 		// Hack : Error is not handled for
> ```

Handle the error here?

---

*[transpiler/transpiler.go, line 32 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlGj9-L99DdsSK7km:-KyhlGj9-L99DdsSK7kn:bfsg61w) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L32)):*
> ```Go
> 
> 	// Now begin building the Go AST.
> 	decls, _ := transpileToNode(root, p)
> ```

Why are you not handling the error here?

---

*[transpiler/transpiler.go, line 220 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlK1v5i5skbEf17f0:-KyhlK1v5i5skbEf17f1:bkrk3zc) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L220)):*
> ```Go
> 	switch n := node.(type) {
> 	case *ast.DeclStmt:
> 		stmts, _ = transpileDeclStmt(n, p) // Hack : error not handled
> ```

Handle the error.

---

*[transpiler/transpiler.go, line 226 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlMZPmScSPjJyy37g:-KyhlMZPmScSPjJyy37h:b-k2pczf) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L226)):*
> ```Go
> 	}
> 	stmts = append(stmts, combineStmts(stmt, preStmts, postStmts)...)
> 	err = nil // Hack : error not handled
> ```

Here too.

---

*[transpiler/transpiler.go, line 328 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlPEQqvp-xQlUDk4H:-KyhlPEQqvp-xQlUDk4I:bkrk3zc) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L328)):*
> ```Go
> 				if v.Name != "" || i == len(n.Children())-1 {
> 					d, _ := transpileRecordDecl(p, v)
> 					// err is ignored
> ```

Handle the error.

---

*[transpiler/transpiler.go, line 340 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlRoeagnprUDZRC7Y:-KyhlRoeagnprUDZRC7Z:bkrk3zc) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L340)):*
> ```Go
> 						recordDecl.Name = nameTypedefStruct
> 						recordDecl.ChildNodes = fields
> 						d, _ := transpileRecordDecl(p, &recordDecl)
> ```

Handle the error.

---

*[transpiler/transpiler.go, line 349 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlSbqs5EdNeQDw93a:-KyhlSbqs5EdNeQDw93b:bkrk3zc) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L349)):*
> ```Go
> 				}
> 			default:
> 				d, _ := transpileToNode(n.Children()[i], p)
> ```

Handle the error.

---

*[transpiler/transpiler.go, line 355 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlUabBvyfy-0Ey59c:-KyhlUabBvyfy-0Ey59d:btb7iu5) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/transpiler.go#L355)):*
> ```Go
> 
> 	case *ast.FunctionDecl:
> 		d, _ := transpileFunctionDecl(n, p)
> ```

Handle this error and all of the ones below (in the other cases).

---

*[transpiler/variables.go, line 176 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhlcUa5nwdIUzdqzO-:-KyhlcUa5nwdIUzdqzO0:b-9kjs7w) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/variables.go#L176)):*
> ```Go
> 	tud.ChildNodes = n.Children()
> 	var decls []goast.Decl
> 	decls, _ = transpileToNode(&tud, p) // Hack : error is ignored
> ```

Handle the error here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/345)*

**Comment by elliotchance** [comment]
There is no tests with this PR so I cannot be sure what you are actually fixing with this PR.

---

Reviewed 3 of 10 files at r2.
Review status: 4 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[ast/non_null_attr.go, line 15 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuWnMKhliugnYQN0j6:-KzuWnML8ZEjoWUI4zDK:bfd6ljq) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/ast/non_null_attr.go#L15)):*
> ```Go
> 	B          int
> 	C          int
> 	D          int
> ```

Did you have a test case for this change?

---

*[transpiler/branch.go, line 86 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuY24j4MmoWjy-vm0W:-KzuY24j4MmoWjy-vm0X:b-8hyqhn) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/transpiler/branch.go#L86)):*
> ```Go
> 
> 	if body == nil {
> 		return nil, nil, nil, fmt.Errorf("Body of If cannot by nil")
> ```

I see lots of new error conditions in all of these files, but no changes to the tests. What was changed?

---

*[transpiler/branch.go, line 118 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuYIEjdhHG0qaUJKF2:-KzuYIEjdhHG0qaUJKF3:b-kr1fcg) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/transpiler/branch.go#L118)):*
> ```Go
> 
> 	// This `defer` is workaround
> 	// Please remove after solving all problems
> ```

You need to explain this better, what are the "problems"? Is there already an issue raise for them?

---

*[transpiler/declarations.go, line 437 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgeAKy5eRgufMP27-:-KzuXOvHAKZ9KCbVsZnu:bahn5ql) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/declarations.go#L437)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Do you know of a case that causes this to happen? Also, it should try to continue instead of panicking.
</blockquote></details>

I don't understand why this is an error. The pre and post statements are allowed to have a value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/345#-:-KzuYTX08mrRPpfhdUTj:b-kroz1y)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[ast/non_null_attr.go, line 15 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuWnMKhliugnYQN0j6:-KzxBTbmUF8HX1hj3Cd4:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/ast/non_null_attr.go#L15)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Did you have a test case for this change?
</blockquote></details>

Done.

---

*[transpiler/branch.go, line 86 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuY24j4MmoWjy-vm0W:-KzxBekUchJ-5FMLHobO:b-nyqkln) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/transpiler/branch.go#L86)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I see lots of new error conditions in all of these files, but no changes to the tests. What was changed?
</blockquote></details>

for test in `c2go/tests` no need that checking on nil.
It is need for transpiling `sqlite`. I haven't detail clarification for question - Why it is need for sqlite?
After adding checking on nil, some of test in https://github.com/Konstantin8105/c2go-rating are Ok.

---

*[transpiler/branch.go, line 118 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KzuYIEjdhHG0qaUJKF2:-KzxDOVpyEzhJuqd4jDM:b-7lf8rh) ([raw file](https://github.com/elliotchance/c2go/blob/9077fb8758adbde830fe028376083adcf6586c3c/transpiler/branch.go#L118)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You need to explain this better, what are the "problems"? Is there already an issue raise for them?
</blockquote></details>

I don't have the detail explanation of problem. Something is not support in c2go:
```
// Warning (TypedefDecl): 341: function pointers are not supported
// Warning (TypedefDecl): 350: function pointers are not supported
// Warning (EnumDecl): 209: Add support of continues counter for type : *ast.BasicLit
// Warning (EnumDecl): 209: Add support of continues counter for type : *ast.BasicLit
// Warning (EnumDecl): 347: Add support of continues counter for type : *ast.UnaryExpr
.....
```

---

*[transpiler/declarations.go, line 437 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/345#-KyhgeAKy5eRgufMP27-:-KzxGFGp2hMAc7Gk9Wt_:b-tmxru3) ([raw file](https://github.com/elliotchance/c2go/blob/3bf878ce594689fdd0a76ac23b39965a12c48d27/transpiler/declarations.go#L437)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I don't understand why this is an error. The pre and post statements are allowed to have a value.
</blockquote></details>

Before that PR - preStmt and postStmt are ignored. I just add warning if they is not empty. So, If we will see that warning in result, then we will modify that part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/345)*

**Comment by Konstantin8105** [comment]
ready for merge

**Comment by elliotchance** [comment]
Reviewed 5 of 10 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/345)*

**Pull request merged**
