### PR TITLE
Travis tests for local machine

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #281 , #294 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/320)

### CODE REVIEW

**Comment by yulvil** [comment]
@Konstantin8105 Cool. Thanks for implementing the sqlite3 warnings monitor.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[travis/test.sh, line 75 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD3mOqO6Z3NXL8tMSf:-KyD3mOr7M7HMtvXGJlp:b-j4sris) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L75)):*
> ```Shell
> 
> # Remove temp folder of SQLITE3
> if [ -d $SQLITE_TEMP_FOLDER ]; then
> ```

In this case you are always downloading the SQLite3. Since the SQLite3 files do not change after being downloaded you should only download when the files do not exist:

```bash
SQLITE_TEMP_FOLDER="/tmp/SQLITE"
mkdir -p $SQLITE_TEMP_FOLDER

# Download/unpack SQLite if required.
if [ ! -e $SQLITE_TEMP_FOLDER/$SQLITE3_FILE.zip ]; then
    curl https://sqlite.org/2017/$SQLITE3_FILE.zip > $SQLITE_TEMP_FOLDER/$SQLITE3_FILE.zip
    unzip $SQLITE_TEMP_FOLDER/$SQLITE3_FILE.zip -d $SQLITE_TEMP_FOLDER
fi

# Clean generated files. This should not be required, but it's polite.
rm -f $SQLITE_TEMP_FOLDER/sqlite3.go $SQLITE_TEMP_FOLDER/shell.go

# Transpile the SQLite3 files.
```

---

*[travis/test.sh, line 89 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD59HxC4nwDML5x8tO:-KyD59HxC4nwDML5x8tP:bgm8e9w) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L89)):*
> ```Shell
> # If transpiling write to stderr, then it will be append into OUTFILE
> echo "Transpiling shell.c..."
> ./c2go transpile -o=$SQLITE_TEMP_FOLDER/shell.go   $SQLITE_TEMP_FOLDER/sqlite-amalgamation-3190300/shell.c  >> $OUTFILE 2>&1
> ```

Use `$SQLITE3_FILE` instead of hardcoding the path.

---

*[travis/test.sh, line 91 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD5DDCiggYvms6b6qm:-KyD5DDCiggYvms6b6qn:bgm8e9w) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L91)):*
> ```Shell
> ./c2go transpile -o=$SQLITE_TEMP_FOLDER/shell.go   $SQLITE_TEMP_FOLDER/sqlite-amalgamation-3190300/shell.c  >> $OUTFILE 2>&1
> echo "Transpiling sqlite3.c..."
> ./c2go transpile -o=$SQLITE_TEMP_FOLDER/sqlite3.go $SQLITE_TEMP_FOLDER/sqlite-amalgamation-3190300/sqlite3.c >> $OUTFILE 2>&1
> ```

Use `$SQLITE3_FILE` instead of hardcoding the path.

---

*[travis/test.sh, line 98 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD5JhKTQybKPVFtFq7:-KyD5JhKTQybKPVFtFq8:bf3ecly) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L98)):*
> ```Shell
> 
> # Remove c2go executable file
> rm ./c2go
> ```

Remove this. We want this to hang around after test because it can be used as a stand alone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/320)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/test.sh, line 98 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD5JhKTQybKPVFtFq7:-KyFUZG2xyDLMKJklx4R:bhtosjj) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L98)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Done. May be, we will change at the middle of script from `go build` to `go install`?
</blockquote></details>

Test script should not install. You don't want any state from the tests to interfere with any production installations of the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/320)*

**Comment by Konstantin8105** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[travis/test.sh, line 98 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/320#-KyD5JhKTQybKPVFtFq7:-KyFX49zfnFDlLXDYf5T:b2nhll9) ([raw file](https://github.com/elliotchance/c2go/blob/4431c68e821a79e9a14042c2c1b2a454f01dc065/travis/test.sh#L98)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Test script should not install. You don't want any state from the tests to interfere with any production installations of the code.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/320)*

**Pull request merged**
