### PR TITLE
Allow passing include directory to clang

### PR DESCRIPTION
**Pull request by lestrrat**
I was trying out c2go on a random piece of code, and could not get past the preprocessing stage. This change adds a new flag `-I` to c2go, and passes it to clang invocation.

---

This allows code like this:

  c2go transpile -I path/to/include foo.c

so #include statements work

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/196)

### CODE REVIEW

**Comment by elliotchance** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/196#-KoS4usSwfKbsjobWNwb:-KoS4usSwfKbsjobWNwc:b-r0murr) (no related file):*
This is a good point. Perhaps it would be better to pass arbitrary arguments to clang so that we can handle any case but also not pollute the c2go args, like:

```bash
c2go transpile -a "-I path/to/include" foo.c
```

Is it also worth thinking about sending different clang arguments for when the preprocessor stage runs vs the AST stage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/196)*

**Comment by elliotchance** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/196#-KoS4usSwfKbsjobWNwb:-KrF9iFtSwwNlGPVXv-a:b-ogsc9p) (no related file):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is a good point. Perhaps it would be better to pass arbitrary arguments to clang so that we can handle any case but also not pollute the c2go args, like:

```bash
c2go transpile -a "-I path/to/include" foo.c
```

Is it also worth thinking about sending different clang arguments for when the preprocessor stage runs vs the AST stage?
</blockquote></details>

Are you able to update the PR @lestrrat ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/196)*

**Comment by lestrrat** [comment]
Sorry for warnocking this, but I currently have no time to do this due to family matters. :/

**Comment by elliotchance** [comment]
I think this is a needed improvement - would you like me to finish it?

**Comment by hnsl** [comment]
A workaround for this is environment variables `env C_INCLUDE_PATH=include c2go ...` but yeah, the real problem is that you can't pass arbitrary flags to clang.

**Comment by elliotchance** [comment]
@hnsl do you want to work on a new PR to pass in custom options to clang?

**Comment by elliotchance** [comment]
@Konstantin8105 can this be closed now?

**Comment by Konstantin8105** [comment]
Feel free for close

**Comment by elliotchance** [comment]
Thanks @Konstantin8105

**Pull request closed without merging**
