### PR TITLE
Patch: Simple pointer arithmetic, warning file idendification. Fixes #511 and #575, #584, #549

### LINKED ISSUE #511: struct of tree
```c
	diag("name of struct inside struct")
	{
		typedef struct TI TI;
		struct TI{
			TI *left, *right;
			double varTI;
		};
		TI t1;
		t1.varTI = 4.3;
		TI t2;
		t2.varTI = 4.1;
		TI tt;
		tt.left       = &t1;
		(*tt.left).right = &t2;
		tt.right      = &t2;
		is_eq((*tt.left ).varTI, 4.3);
		is_eq((*(*tt.left).right).varTI, 4.1);
		is_eq((*tt.right).varTI, 4.1);
	}
```
```go
	noarch.Printf([]byte("# \x00"))
	noarch.Printf([]byte("name of struct inside struct\x00"))
	noarch.Printf([]byte("\n\x00"))
	{
		type TI struct {
			left  []TI
			right []TI
			varTI float64
		}
		var t1 TI
		t1.varTI = 4.3
		var t2 TI
		t2.varTI = 4.1
		var tt TI
		tt.left = (*[1]TI)(unsafe.Pointer(&t1))[:]
		(tt[noarch.InterfaceToInt(0 .left)]).right = (*[1]TI)(unsafe.Pointer(&t2))[:]
		tt.right = (*[1]TI)(unsafe.Pointer(&t2))[:]
		if approxf(((tt[noarch.InterfaceToInt(0 .left)]).varTI), (4.3), func() int { /// <<-- warning here
...
		if approxf((((tt[noarch.InterfaceToInt(0 .left)])[noarch.InterfaceToInt((0).right)]).varTI), (4.1), func() int { /// <<-- warning here
...
```
```
    		build/tests/struct/main_test.go:1440: undefined: noarch.InterfaceToInt
    		build/tests/struct/main_test.go:1440: 0.left undefined (type int has no field or method left)
    		build/tests/struct/main_test.go:1442: undefined: noarch.InterfaceToInt
    		build/tests/struct/main_test.go:1442: 0.left undefined (type int has no field or method left)
    		build/tests/struct/main_test.go:1470: undefined: noarch.InterfaceToInt
    		build/tests/struct/main_test.go:1470: 0.left undefined (type int has no field or method left)
    		build/tests/struct/main_test.go:1475: undefined: noarch.InterfaceToInt
    		build/tests/struct/main_test.go:1475: 0.left undefined (type int has no field or method left)
    		build/tests/struct/main_test.go:1475: undefined: noarch.InterfaceToInt
    		build/tests/struct/main_test.go:1475: 0.right undefined (type int has no field or method right)
    		build/tests/struct/main_test.go:1475: too many errors
```

### LINKED ISSUE #549: SWITCH simplification
In Go code:
```go
	switch hl {
	case 2:
		{
		}
		fallthrough
	case 4:
		{
			return 33
		}
		fallthrough
	case 5:
		{
			return 32
		}
		fallthrough
	case 6:
		{
			return 35
		}
		fallthrough
}
```
Expect:
```go
	switch hl {
	case 2:
		fallthrough
	case 4:
		return 33
	case 5:
		return 32
	case 6:
		return 35
	}
```

Result of govet:
```
main.go:4222: unreachable code
```
```go
			case 'd':
				{
					debug[0] = 1
					break
				}
			fallthrough /// Warning about that line
```

### LINKED ISSUE #575: Typedef function pointer
`/usr/include/libio.h`:
```c
/* Close COOKIE.  */
typedef int __io_close_fn (void *__cookie);


#ifdef _GNU_SOURCE
/* User-visible names for the above.  */
typedef __io_read_fn cookie_read_function_t;
typedef __io_write_fn cookie_write_function_t;
typedef __io_seek_fn cookie_seek_function_t;
typedef __io_close_fn cookie_close_function_t;
```
Warning in Go:
```
// Warning (TypedefDecl): /usr/include/libio.h:361: Cannot resolve type '__io_close_fn' : Cannot resolve type 'int (void *)' : function pointers are not supported [2] : 'int (void *)'
```

### LINKED ISSUE #584: Operator equal a=b=c=...
```c
	{
		int x, y, z = x = y = 42;
		is_eq(x,42);
		is_eq(y,42);
		is_eq(z,42);
	}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Created for #503
Close #575
Close #511
Close #584
Close #549

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/558)

### CODE REVIEW

**Comment by elliotchance** [comment]
Does this fix all the cases in #503?

---

Reviewed 6 of 11 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/util.go, line 10 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3Pt1OSEsQK-cW3IVrV:-L3Pt1OSEsQK-cW3IVrW:bd89fco) ([raw file](https://github.com/elliotchance/c2go/blob/c8fe17fbc70716d92a2f64e808bef2f6ebf0ebe6/transpiler/util.go#L10)):*
> ```Go
> 
> func isNil(stmt goast.Stmt) bool {
> 	if stmt != nil &&
> ```

This is interesting, I had to check this logic because I didn't know that `nil`s of different types are not actually equal in Go. There may be other types of `nil` in the future, to be safe you can simplify:

```go
func isNil(stmt goast.Stmt) bool {
    return !reflect.ValueOf(stmt).IsValid()
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/558#-:-L3PwZO2lb9p3xcm5rRN:bfdew3p)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/util.go, line 10 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3Pt1OSEsQK-cW3IVrV:-L3RfPlhejip-a_vZimQ:b-t1cflh) ([raw file](https://github.com/elliotchance/c2go/blob/c8fe17fbc70716d92a2f64e808bef2f6ebf0ebe6/transpiler/util.go#L10)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is interesting, I had to check this logic because I didn't know that `nil`s of different types are not actually equal in Go. There may be other types of `nil` in the future, to be safe you can simplify:

```go
func isNil(stmt goast.Stmt) bool {
    return !reflect.ValueOf(stmt).IsValid()
}
```
</blockquote></details>

I don't have good experience with `reflect` package, so I check: https://play.golang.org/p/WXhXiG1znx0
So, that `reflect` code is not the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/558)*

**Comment by elliotchance** [comment]
Reviewed 100 of 100 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tests/operators.c, line 263 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIBfQvz26FS-FuRVI:-L3eIBfQvz26FS-FuRVJ:b1w9j16) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/tests/operators.c#L263)):*
> ```C
> 		is_eq(a[(iterator = 0,iterator  )] ,   5);
> 		/* is_eq(a[(iterator = 0,iterator++)] ,   5); */
> 		/* is_eq(a[(iterator = 1,++iterator)] , -13); */
> ```

If these do not work can you add an issue and remove the comments.

---

*[tests/code_quality/generate.sh, line 16 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIXKa8kaEQpbdzEjB:-L3eIXKa8kaEQpbdzEjC:b-v1y55p) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/tests/code_quality/generate.sh#L16)):*
> ```Shell
> 
>   echo "Processing $file file..."
>   filename=${file%.*}".expected.c"
> ```

You will have to replace the version in the output file so that when I change the package version these tests will still pass.

---

*[transpiler/binary.go, line 196 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIhtS_6MRUenpo4yv:-L3eIhtS_6MRUenpo4yw:bse26yk) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/transpiler/binary.go#L196)):*
> ```Go
> 	preStmts, postStmts = combinePreAndPostStmts(preStmts, postStmts, newPre, newPost)
> 
> 	right, rightType, newPre, newPost, err := atomicOperation(n.Children()[1], p) //transpileToExpr(n.Children()[1], p, false)
> ```

Remove code comment if it's not needed. Also the one above.

---

*[transpiler/util.go, line 10 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3Pt1OSEsQK-cW3IVrV:-L3eK98eCrT56BukgD-B:b-m1l0ku) ([raw file](https://github.com/elliotchance/c2go/blob/c8fe17fbc70716d92a2f64e808bef2f6ebf0ebe6/transpiler/util.go#L10)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I don't have good experience with `reflect` package, so I check: https://play.golang.org/p/WXhXiG1znx0
So, that `reflect` code is not the same.
</blockquote></details>

Hmm that is confusing. You don't have to change anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/558)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[tests/operators.c, line 263 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIBfQvz26FS-FuRVI:-L3gY3abOmzr23R0Pl3F:b-rhnf93) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/tests/operators.c#L263)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

If these do not work can you add an issue and remove the comments.
</blockquote></details>

Add new issue about that.

---

*[tests/code_quality/generate.sh, line 16 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIXKa8kaEQpbdzEjB:-L3gYFLTgCeYYzF1kWOZ:b-rqflj1) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/tests/code_quality/generate.sh#L16)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You will have to replace the version in the output file so that when I change the package version these tests will still pass.
</blockquote></details>

Yes in comments of files *.expectd.c we have the version of c2go, but it is Ok, because All comments is ignored for that test.
So, fell free to change version.

---

*[transpiler/binary.go, line 196 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3eIhtS_6MRUenpo4yv:-L3gYbxWUND3CqUC6uSm:byp18fd) ([raw file](https://github.com/elliotchance/c2go/blob/0492c1537b7bbef5b189b3da3f8f04297367f65b/transpiler/binary.go#L196)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Remove code comment if it's not needed. Also the one above.
</blockquote></details>

Remove

---

*[transpiler/util.go, line 10 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/558#-L3Pt1OSEsQK-cW3IVrV:-L3gYdqYgBuT-EVeEUZb:b6p5omv) ([raw file](https://github.com/elliotchance/c2go/blob/c8fe17fbc70716d92a2f64e808bef2f6ebf0ebe6/transpiler/util.go#L10)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Hmm that is confusing. You don't have to change anything.
</blockquote></details>

Your idea is nice, but little bit not correct.
I found the function `IsNil()` in package `reflect` and add that code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/558)*

**Comment by elliotchance** [comment]
Reviewed 20 of 20 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/558)*

**Pull request merged**
