### PR TITLE
Add support for function pointers. Fixes #85 and #157

### LINKED ISSUE #85: Some platform structs are ignored
There are some `struct`s that have been ignored for various reasons. The code to ignore them should be removed. Search the codebase for "issues/85"

### PR DESCRIPTION
**Pull request by Konstantin8105**
Not ready for review

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/469)

### CODE REVIEW

**Comment by elliotchance** [comment]
I will wait until you say its ready for review :smile: 

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/469#-:-L0MF9kfqgvjEWxG-eHI:bp8m44f)*

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by Konstantin8105** [comment]
Not ready in according to travis

**Comment by Konstantin8105** [comment]
Partly #85

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by Konstantin8105** [comment]
If you want, then I can try to separate to small PRs.

**Comment by elliotchance** [comment]
This is a such a big and great feature it will be the v0.19.0 Uranium release 👍

**Comment by elliotchance** [comment]
Reviewed 11 of 16 files at r1, 6 of 7 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/469)*

**Pull request merged**
