### PR TITLE
Add information for function call without declaration. Fix #495

### LINKED ISSUE #495: Add warning for functions without implementations
```c
char *
STRNCAT (char *s1, const char *s2, size_t n)
{
  char *s = s1;

  /* Find the end of S1.  */
  s1 += strlen (s1);

  size_t ss = __strnlen (s2, n);

  s1[ss] = '\0';
  memcpy (s1, s2, ss);

  return s;
}
```
```go
func strncat(s1 []byte, s2 []byte, n uint32) []byte {
        var s []byte = s1
        s1 += noarch.Strlen(s1)
        var// Warning (CallExpr): 34: probably an incorrect type translation 1 // <-- WRONG HERE
        ss uint32 = uint32((uint32(__strnlen(nil, n))))
        s1[ss] = '\x00'
        memcpy(s1, s2, uint32((ss)))
        return s
}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #495

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/546)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[program/program.go, line 47 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/546#-L2HnGvQnydUbzR5BpWq:-L2HnGvQnydUbzR5BpWr:b9q84oj) ([raw file](https://github.com/elliotchance/c2go/blob/bb4a59c28c398ca3fb9273b0899149779de55a9f/program/program.go#L47)):*
> ```Go
> 
> 	// Functions declarated
> 	FunctionDeclareted map[string]bool
> ```

`FunctionDeclared`

---

*[transpiler/transpiler.go, line 40 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/546#-L2Ho5Wff4xu8KdraMzt:-L2Ho5Wff4xu8KdraMzu:b-yevlv8) ([raw file](https://github.com/elliotchance/c2go/blob/bb4a59c28c398ca3fb9273b0899149779de55a9f/transpiler/transpiler.go#L40)):*
> ```Go
> 
> 	// add warning if function is called, but not declareted
> 	p.FunctionWithoutDeclaration()
> ```

Is this really necessary? If a function is called that does not exist go will not compile the source and give better information about what has gone wrong. What would be the advantage of adding the comment to the output file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/546)*

**Comment by Konstantin8105** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[program/program.go, line 47 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/546#-L2HnGvQnydUbzR5BpWq:-L2JGstEfAIGKt0t8-Iq:bb6un1j) ([raw file](https://github.com/elliotchance/c2go/blob/bb4a59c28c398ca3fb9273b0899149779de55a9f/program/program.go#L47)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

`FunctionDeclared`
</blockquote></details>

Done

---

*[transpiler/transpiler.go, line 40 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/546#-L2Ho5Wff4xu8KdraMzt:-L2JGwra-9_UX24Kaxg3:b-soa9uj) ([raw file](https://github.com/elliotchance/c2go/blob/bb4a59c28c398ca3fb9273b0899149779de55a9f/transpiler/transpiler.go#L40)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this really necessary? If a function is called that does not exist go will not compile the source and give better information about what has gone wrong. What would be the advantage of adding the comment to the output file?
</blockquote></details>

Yes, you are right.
That PR don't are some specific features. 
Fell free to close.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/546)*

**Comment by Konstantin8105** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 40 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/546#-L2Ho5Wff4xu8KdraMzt:-L2ZUtrwpMn-2vNYZ2Q-:b9hc029) ([raw file](https://github.com/elliotchance/c2go/blob/bb4a59c28c398ca3fb9273b0899149779de55a9f/transpiler/transpiler.go#L40)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Yes, you are right.
That PR don't are some specific features. 
Fell free to close.
</blockquote></details>

`go build` is show just 10 errors, but for myself it is not enough. In my test C project, need to see all lost functions
May we can merge "as is"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/546)*

**Comment by Konstantin8105** [comment]
Close that issue, because `gometalinter` create more detail information.

**Pull request closed without merging**
