### PR TITLE
Added basic support for array initialization. Fixes #250

### LINKED ISSUE #250: Array not initialized properly
```
#include <stdio.h>

int main(int argc, char* argv[]) {
        argc = argc;

   int arr[] = {2,3,4};
   //arr[0] = 2;
   //arr[1] = 3;
   //arr[2] = 4;
   printf("%d\n", arr[0]);
   printf("%d\n", arr[1]);
   printf("%d\n", arr[2]);
}
```

The array initialization is translated to `var arr []int = make([]int, 3, 3)`

This will print

```
0
0
0
```

### PR DESCRIPTION
**Pull request by yulvil**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/256)

### CODE REVIEW

**Comment by yulvil** [comment]
@elliotchance I can remove the commented test cases if you want. They need to be fixed at a later time.

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/array.c, line 44 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6P7Ekxm2GMB4co83z:-Kx6P7Ekxm2GMB4co84-:boqglu6) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L44)):*
> ```C
> // void test_intarr_init2()
> // {
> //     int a[4] = {10, 20};
> ```

If I saw someone do that in code I would expect that it was a mistake. What is the expected behaviour of this in C? Please open an issue with these examples so they can be removed (rather than commented out).

---

*[tests/array.c, line 75 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6PYTcH6vMyW0klWSo:-Kx6PYTcH6vMyW0klWSp:bhi58h9) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L75)):*
> ```C
> }
> 
> // currently transpiles to: var arr []string
> ```

In previous versions I treated `char *` as a Go `string` until I realised that wasn't going to work. It looks like there is still one case left over where it is resolving to a `string` instead of `[]byte`.

---

*[tests/array.c, line 95 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6Pxw1Ax8TxeY7Dshw:-Kx6Pxw1Ax8TxeY7Dshx:b7haxuz) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L95)):*
> ```C
> 
> // currently transpiles to: var a []interface {} = []interface{}{nil, nil}
> // void test_structarr()
> ```

Based on my previous comment. It is better to put these examples in a Github issue so they can be found and fixed rather than keeping them as code that is inactive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/256)*

**Comment by yulvil** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/array.c, line 44 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6P7Ekxm2GMB4co83z:-Kx6sqh-mz5lZ1QO9quR:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L44)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

If I saw someone do that in code I would expect that it was a mistake. What is the expected behaviour of this in C? Please open an issue with these examples so they can be removed (rather than commented out).
</blockquote></details>

Done.

---

*[tests/array.c, line 75 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6PYTcH6vMyW0klWSo:-Kx6ssCOqN4F8G7A830J:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L75)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

In previous versions I treated `char *` as a Go `string` until I realised that wasn't going to work. It looks like there is still one case left over where it is resolving to a `string` instead of `[]byte`.
</blockquote></details>

Done.

---

*[tests/array.c, line 95 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/256#-Kx6Pxw1Ax8TxeY7Dshw:-Kx6suHNzfbBQdU0ZnwI:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/8fd06199326d0d73643f26a61f294999b7ed668b/tests/array.c#L95)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Based on my previous comment. It is better to put these examples in a Github issue so they can be found and fixed rather than keeping them as code that is inactive.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/256)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/256)*

**Pull request merged**
