### PR TITLE
Add support for "typedef struct C C". Fixes #459

### LINKED ISSUE #459: typedef struct with same names
C example:
```c
typedef struct T T; // SAME NAME
struct T{
        int t;
};

int main(){
        T tt;
        return 0;
}
```

Go:
```go
package main

type T struct {
//// <--- LOST
}

func main() {
        __init()
        var tt T
        return
}
func __init() {
}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #459 
See #11

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/460)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Warnings going down from ~45000 to ~17000. :+1:

**Comment by elliotchance** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/460)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/460#-L0CD5KvhFJeIrX8cR6l:-L0CD5KvhFJeIrX8cR6m:b-ze3qww) (no related file):*
Please fix the merge conflicts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/460)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/460)*

**Comment by Konstantin8105** [comment]
Ready for review.

**Comment by elliotchance** [comment]
Please resolve conflicts, then I can review.

**Comment by Konstantin8105** [comment]
Done )

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/460)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/460)*

**Pull request merged**
