### PR TITLE
Union in struct. Fixes #502

### LINKED ISSUE #502: union inside sttruct
Example:

```c
struct Bitvec {
  u32 iSize;      /* Maximum bit index.  Max iSize is 4,294,967,296. */
  u32 nSet;       /* Number of bits that are set - only valid for aHash
                  ** element.  Max is BITVEC_NINT.  For BITVEC_SZ of 512,
                  ** this would be 125. */
  u32 iDivisor;   /* Number of bits handled by each apSub[] entry. */
                  /* Should >=0 for apSub element. */
                  /* Max iDivisor is max(u32) / BITVEC_NPTR + 1.  */
                  /* For a BITVEC_SZ of 512, this would be 34,359,739. */
  union {
    BITVEC_TELEM aBitmap[BITVEC_NELEM];    /* Bitmap representation */
    u32 aHash[BITVEC_NINT];      /* Hash table representation */
    Bitvec *apSub[BITVEC_NPTR];  /* Recursive representation */
  } u;
};
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #502

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/509)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/union.c, line 65 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K3E6YdzvwTHOQHgiu:-L1K3E6YdzvwTHOQHgiv:b-xo7t46) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/tests/union.c#L65)):*
> ```C
> void union_inside_struct()
> {
> 	{int g;(void)g;}
> ```

What does this line do?

---

*[types/resolve.go, line 413 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K4GleQwusEzYmHYZ5:-L1K4GleQwusEzYmHYZ6:b-gflefn) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/types/resolve.go#L413)):*
> ```Go
> 		}
> 	}
> 	inside := string(([]byte(name))[index : last+1])
> ```

Can you explain what is going on here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/509)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/union.c, line 65 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K3E6YdzvwTHOQHgiu:-L1MARd13zY1Wvd-1vUW:bwrv2mt) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/tests/union.c#L65)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

What does this line do?
</blockquote></details>

I removed this line.
That code help for searching the bug.

---

*[types/resolve.go, line 413 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K4GleQwusEzYmHYZ5:-L1MApDYOTrWKDu-M6J2:b-ghqqu0) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/types/resolve.go#L413)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Can you explain what is going on here?
</blockquote></details>

// Example: 'union (anonymous union at tests/union.c:46:3)'
that line get string inside "(...)".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/509)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/resolve.go, line 413 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K4GleQwusEzYmHYZ5:-L1P4VHm5mdwZJuUbMLT:b9m1m55) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/types/resolve.go#L413)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

// Example: 'union (anonymous union at tests/union.c:46:3)'
that line get string inside "(...)".
</blockquote></details>

Please add a comment to the code explaining what this code does and what and example looks like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/509)*

**Comment by Konstantin8105** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[types/resolve.go, line 413 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/509#-L1K4GleQwusEzYmHYZ5:-L1QwyjbvpZxLz3E7vw7:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/2f7c579efcbfefb63947831c2ac2c3997dbcc0eb/types/resolve.go#L413)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please add a comment to the code explaining what this code does and what and example looks like.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/509)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/509)*

**Comment by Konstantin8105** [comment]
Ready for review, merging

**Comment by Konstantin8105** [comment]
Dear, @elliotchance , could you merge that old PR.

**Pull request merged**
