### PR TITLE
Add resolving function types

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/641)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 11 of 21 files at r1.
Review status: 11 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[program/program.go, line 417 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMBnuNbjoPdJ0tWTq:-L7MMBnuNbjoPdJ0tWTr:b-n1zmrg) ([raw file](https://github.com/elliotchance/c2go/blob/5019819622e118e46199ea4628a1e085496fa06e/program/program.go#L417)):*
> ```Go
> }
> 
> // IncudeHeaderIsExist - return true if C #include header is inside list
> ```

"IncludeHeaderIsExists"

---

*[tests/function.c, line 222 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMM0jUZ-uEH0OXOrQ:-L7MMM0jUZ-uEH0OXOrR:bbdbhm1) ([raw file](https://github.com/elliotchance/c2go/blob/5019819622e118e46199ea4628a1e085496fa06e/tests/function.c#L222)):*
> ```C
> 	diag("function name like in CSTD");
> 	{
> 		is_eq(tolower2(34,52),86);
> ```

You have changed the function name so it's no longer testing what it was originally testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/641)*

**Comment by elliotchance** [comment]
Please resolve merge conflicts.

---

Review status: 11 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/641#-:-L7MNYNR8euls7tlqhz9:bu4pwai)*

**Comment by Konstantin8105** [comment]
Review status: 6 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[program/program.go, line 417 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMBnuNbjoPdJ0tWTq:-L7OMCLCWrta5lw-EB8h:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/e4bb3a766c517534e973c146a1fe8e4613bf91bb/program/program.go#L417)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

"IncludeHeaderIsExists"
</blockquote></details>

Done.

---

*[tests/function.c, line 222 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMM0jUZ-uEH0OXOrQ:-L7OMES_CK3w4m-Mvx4L:b-faohpd) ([raw file](https://github.com/elliotchance/c2go/blob/e4bb3a766c517534e973c146a1fe8e4613bf91bb/tests/function.c#L222)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You have changed the function name so it's no longer testing what it was originally testing.
</blockquote></details>

Yes, I will return that test in next prepared PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/641)*

**Comment by elliotchance** [comment]
Reviewed 2 of 21 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tests/function.c, line 222 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMM0jUZ-uEH0OXOrQ:-L7vkexqdToKt-nNyTeA:bjbbead) ([raw file](https://github.com/elliotchance/c2go/blob/e4bb3a766c517534e973c146a1fe8e4613bf91bb/tests/function.c#L222)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Yes, I will return that test in next prepared PR.
</blockquote></details>

It's not appropriate to have a PR merge with half changes based on the fact that it will be fixed in the future, either remove the changes to incorporate the fixes.

---

*[transpiler/call.go, line 125 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7vl7zMSTdbOgk86kXo:-L7vl7zNk4u5C0HLnu35:b8gjj3z) ([raw file](https://github.com/elliotchance/c2go/blob/2f5e243c2e01246417271c1b1b3b3294ef81f07e/transpiler/call.go#L125)):*
> ```Go
> 
> 	if insideCall, ok := n.Children()[0].(*ast.CallExpr); ok {
> 		// TODO :
> ```

Why is this left here?

---

*[types/resolve.go, line 535 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7vljoVgZ8z_9FwwXh0:-L7vljoVgZ8z_9FwwXh1:bxw1lzl) ([raw file](https://github.com/elliotchance/c2go/blob/2f5e243c2e01246417271c1b1b3b3294ef81f07e/types/resolve.go#L535)):*
> ```Go
> 	// return type : void (*)(int *, void *, char *)
> 	// prefix      : *
> 	// Find the block
> ```

Nice docs :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/641)*

**Comment by Konstantin8105** [comment]
Review status: 6 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/function.c, line 222 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7MMM0jUZ-uEH0OXOrQ:-L8CQKUjDXPeagXwStWv:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/e4bb3a766c517534e973c146a1fe8e4613bf91bb/tests/function.c#L222)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It's not appropriate to have a PR merge with half changes based on the fact that it will be fixed in the future, either remove the changes to incorporate the fixes.
</blockquote></details>

Done.

---

*[transpiler/call.go, line 125 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7vl7zMSTdbOgk86kXo:-L8CQdaxzUUettLs9eYP:b-gfzwhk) ([raw file](https://github.com/elliotchance/c2go/blob/2f5e243c2e01246417271c1b1b3b3294ef81f07e/transpiler/call.go#L125)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why is this left here?
</blockquote></details>

This is workaround, but for indication that, I add a Warning and TODO.

---

*[types/resolve.go, line 535 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/641#-L7vljoVgZ8z_9FwwXh0:-L8CR1YGco1-WZbdvsoM:b-9755fa) ([raw file](https://github.com/elliotchance/c2go/blob/2f5e243c2e01246417271c1b1b3b3294ef81f07e/types/resolve.go#L535)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Nice docs :thumbsup: 
</blockquote></details>

Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/641)*

**Comment by elliotchance** [comment]
Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[noarch/math.go, line 22 at r3](https://beta.reviewable.io/reviews/elliotchance/c2go/641#-L8VBvnH-NnYJJYmwo_V:-L8VBvnH-NnYJJYmwo_W:bg8ggvi) ([raw file](https://github.com/elliotchance/c2go/blob/9bb29c378923907e0c64a9443f50f5d15c08b989/noarch/math.go#L22)):*
> ```Go
> }
> 
> // IsNaN ...
> ```

A description may not be necessary for these four functions individually, but if they have a doctag they should say something relevant. How about?

```
// IsNaN is provided by the cstdlib.
```

---

*[transpiler/unary.go, line 264 at r3](https://beta.reviewable.io/reviews/elliotchance/c2go/641#-L8VDTp9CsScTI88dNKd:-L8VDTp9CsScTI88dNKe:b45j5bj) ([raw file](https://github.com/elliotchance/c2go/blob/9bb29c378923907e0c64a9443f50f5d15c08b989/transpiler/unary.go#L264)):*
> ```Go
> 	f = func(n ast.Node) {
> 		for i := range n.Children() {
> 			state := func() {
> ```

Why does `state` and `f` need to be anonymous functions?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/641)*

**Comment by Konstantin8105** [comment]
Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[noarch/math.go, line 22 at r3](https://beta.reviewable.io/reviews/elliotchance/c2go/641#-L8VBvnH-NnYJJYmwo_V:-L8XgQnr4p8BIUSa1kd-:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/9bb29c378923907e0c64a9443f50f5d15c08b989/noarch/math.go#L22)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

A description may not be necessary for these four functions individually, but if they have a doctag they should say something relevant. How about?

```
// IsNaN is provided by the cstdlib.
```
</blockquote></details>

Done.

---

*[transpiler/unary.go, line 264 at r3](https://beta.reviewable.io/reviews/elliotchance/c2go/641#-L8VDTp9CsScTI88dNKd:-L8Xh8It6_1sZUlDEIHk:b39nic7) ([raw file](https://github.com/elliotchance/c2go/blob/9bb29c378923907e0c64a9443f50f5d15c08b989/transpiler/unary.go#L264)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Why does `state` and `f` need to be anonymous functions?
</blockquote></details>

Theoretically each of that function will have by 7 arguments.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/641)*

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/unary.go, line 264 at r3](https://beta.reviewable.io/reviews/elliotchance/c2go/641#-L8VDTp9CsScTI88dNKd:-L8es43D4uZOTUGu9ihy:bnzp1vl) ([raw file](https://github.com/elliotchance/c2go/blob/9bb29c378923907e0c64a9443f50f5d15c08b989/transpiler/unary.go#L264)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Theoretically each of that function will have by 7 arguments.
</blockquote></details>

I would rather functions with lots of arguments. Rather than sharing variables from different scopes which can lead to some really bad nested code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/641)*

**Pull request closed without merging**
