### PR TITLE
Added test for noarch

### PR DESCRIPTION
**Pull request by Konstantin8105**
For functions `NotUint16` test is not added, because that functions is not used

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/194)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Fix #158

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[noarch/function_test.go, line 52 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/194#-KoS9gIJWbrwfdWG-os8:-KoS9gIJWbrwfdWG-os9:bygc800) ([raw file](https://github.com/elliotchance/c2go/blob/759ce5c52279bab252c9172c8d660800b7d4b952/noarch/function_test.go#L52)):*
> ```Go
> func testC() interface{} {
> 	return "c"
> }
> ```

Please rename these so they don't have a `test` prefix. I know they won't be treated as a test but it's confusing to read.

---

*[noarch/functions.go, line 20 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/194#-KoSBBJhSn5KoGe1sDSV:-KoSBBJhSn5KoGe1sDSW:bs4w1rp) ([raw file](https://github.com/elliotchance/c2go/blob/759ce5c52279bab252c9172c8d660800b7d4b952/noarch/functions.go#L20)):*
> ```Go
> }
> 
> /* Dead code
> ```

If it is dead you can remove it.

---

*[noarch/stdlib.go, line 41 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/194#-KoSAuksCdHnZzuiPOeG:-KoSAuksCdHnZzuiPOeH:b-r8f9zt) ([raw file](https://github.com/elliotchance/c2go/blob/759ce5c52279bab252c9172c8d660800b7d4b952/noarch/stdlib.go#L41)):*
> ```Go
> 	}
> 	if countByteForInt == 0 {
> 		panic("function Strtol: Cannot found integer")
> ```

It is tempting to panic on error but `strtol` must work exactly the same way as the C version. Make sure you include a test case for a totally invalid input.

---

*[noarch/stdlib_test.go, line 9 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/194#-KoSAMynArhwxcpD5Vyz:-KoSAMynArhwxcpD5Vz-:bppxhbm) ([raw file](https://github.com/elliotchance/c2go/blob/759ce5c52279bab252c9172c8d660800b7d4b952/noarch/stdlib_test.go#L9)):*
> ```Go
> // web link with clarification:
> // http://www.cplusplus.com/reference/cstdlib/strtol/
> func TestStrtol(t *testing.T) {
> ```

It's good to know the logic for `strtol` works from Go, but these need to be translated into TAP tests in `stdlib.c`.

Separately I am working on a PR to include code coverage from these packages as part of the integration testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/194)*

**Comment by elliotchance** [comment]
@Konstantin8105 please fix merge conflicts and finalise discussions.

**Comment by Konstantin8105** [comment]
Hello, @elliotchance !
This is minor changes. 
Let's return to that PR after creating test with C function.

**Comment by elliotchance** [comment]
No problem 😄

**Pull request closed without merging**
