### PR TITLE
Concept for transpiling glibc. Example for "qsort"

### PR DESCRIPTION
**Pull request by Konstantin8105**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/625)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by elliotchance** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/glibc.sh, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/625#-L5BgnPZIKx2Xfzit8B3:-L5BgnPZIKx2Xfzit8B4:b-27148u) ([raw file](https://github.com/elliotchance/c2go/blob/3bbb46bd70b19c64b8eb1674d3cd5c7b034e0df8/travis/glibc.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

I don't understand what this is doing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/625)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/glibc.sh, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/625#-L5BgnPZIKx2Xfzit8B3:-L5mMHVCMks8iFpoczNS:b-95ybop) ([raw file](https://github.com/elliotchance/c2go/blob/3bbb46bd70b19c64b8eb1674d3cd5c7b034e0df8/travis/glibc.sh#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I don't understand what this is doing?
</blockquote></details>

Concept is transpile `glibc` or using `glibc` for dashboard of success.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/625)*

**Comment by Konstantin8105** [comment]
Not ready for review and merge.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[travis/glibc.sh, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/625#-L5BgnPZIKx2Xfzit8B3:-L5u_hVr7gD-3pk8jXE1:b3vb3gw) ([raw file](https://github.com/elliotchance/c2go/blob/3bbb46bd70b19c64b8eb1674d3cd5c7b034e0df8/travis/glibc.sh#L1)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Concept is transpile `glibc` or using `glibc` for dashboard of success.
</blockquote></details>

Ah I see, this is useful, you should create another travis job for this one so it doesn't become forgotten.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/625)*

**Pull request closed without merging**
