### PR TITLE
Group imports at the top of the file. Fixes #119

### LINKED ISSUE #119: Group imports in Go output
At the moment the imports are individual like:

```go
import "math"
import "os"
import "github.com/elliotchance/c2go/noarch"
import "github.com/elliotchance/c2go/darwin"
```

They should be grouped like:

```go
import (
    "math"
    "os"
    "github.com/elliotchance/c2go/noarch"
    "github.com/elliotchance/c2go/darwin"
)
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Fix #119

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/421)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/421)*

**Comment by elliotchance** [comment]
@Konstantin8105 Why did you close this?

**Comment by Konstantin8105** [comment]
Because I don't understand- why it is fail

**Comment by elliotchance** [comment]
It is still a good change, we should leave it open until the issue is found.

**Comment by Konstantin8105** [comment]
Ok

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/421)*

**Pull request closed without merging**
