### PR TITLE
Fix for operator FOR without body

### PR DESCRIPTION
**Pull request by Konstantin8105**
Fix for operator FOR without body.
Example of C code:
```c
for(p=1, lcv=2; lcv <= n; p=p*lcv, lcv++);
```

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/186)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/branch.go, line 179 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtkXTmYG4KzLtoyLR:-KoAtkXTmYG4KzLtoyLS:b-rlajqd) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L179)):*
> ```Go
> 			// if body is exist
> 			if children[4] != nil {
> 				compound = *children[4].(*ast.CompoundStmt)
> ```

Are you dereferencing it for a reason?

---

*[transpiler/branch.go, line 230 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtr7uY8UaRd724xHE:-KoAtr7uY8UaRd724xHF:bfd8lvb) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L230)):*
> ```Go
> 			// if body is exist
> 			if children[4] != nil {
> 				compound = *children[4].(*ast.CompoundStmt)
> ```

Same thing here. Are you dereferencing because you need to take a shallow copy of it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/186)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/branch.go, line 179 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtkXTmYG4KzLtoyLR:-KoCdSJtU1VfEx5RMhPX:b-90gpah) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L179)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Are you dereferencing it for a reason?
</blockquote></details>

In case if operator FOR haven`t body and we have many increments elements.
We have to have any body for append increments elements.
The case operator FOR without body used in example: https://github.com/Konstantin8105/c2go-rating/blob/master/SingleCcode/factorial.c

Or you mean - Why we don`t use  pointer : `var compound &ast.CompoundStmt`?
Please clarify.

---

*[transpiler/branch.go, line 230 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtr7uY8UaRd724xHE:-KoCfQf6MWpvWDTP0EAJ:b3xqjpv) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L230)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Same thing here. Are you dereferencing because you need to take a shallow copy of it?
</blockquote></details>

Same point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/186)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/branch.go, line 179 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtkXTmYG4KzLtoyLR:-KoS9E4t5rH_9RjeTysi:bk3ampe) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L179)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

In case if operator FOR haven`t body and we have many increments elements.
We have to have any body for append increments elements.
The case operator FOR without body used in example: https://github.com/Konstantin8105/c2go-rating/blob/master/SingleCcode/factorial.c

Or you mean - Why we don`t use  pointer : `var compound &ast.CompoundStmt`?
Please clarify.
</blockquote></details>

Yes, I mean't "Why we dont use pointer :var compound &ast.CompoundStmt`?"

---

*[transpiler/branch.go, line 230 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtr7uY8UaRd724xHE:-KoS9L5tBERheOrnRZfw:b-80wp0l) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L230)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Same point.
</blockquote></details>

Same question

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/186)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/branch.go, line 179 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtkXTmYG4KzLtoyLR:-KoSLYzcXnj5_O104wCu:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L179)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Yes, I mean't "Why we dont use pointer :var compound &ast.CompoundStmt`?"
</blockquote></details>

Done.

---

*[transpiler/branch.go, line 230 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/186#-KoAtr7uY8UaRd724xHE:-KoSLenW4bZDWWoMe0_k:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/a54c871801389683c87cb1cf2a5ab3321adbec60/transpiler/branch.go#L230)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Same question
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/186)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/186)*

**Pull request merged**
