### PR TITLE
extra blocks in operator FOR. Fixes #545, #563

### LINKED ISSUE #545: extra function for operator For
Go example:
```go
		for i = 1; i <= N; func() int {
			i += 1
			return i
}() {
```
Expected:
```go
		for i = 1; i <= N; i += 1 {
```

### LINKED ISSUE #563: extra block around operator FOR
```go
{
	for n = 1; n <= nU[lc]; func() int {
		n += 1
		return n
	}() {
		// BODY
	}
}
```
Expected
```go
for n = 1; n <= nU[lc]; func() int {
	n += 1
	return n
}() {
	// BODY
}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #545
Close #563

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/564)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/code_quality/for.c.txt, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/564#-L2w-deAdONMV-CVltKU:-L2w-deAdONMV-CVltKV:bq75qsu) ([raw file](https://github.com/elliotchance/c2go/blob/5b3937e2aa78af79c353dd20f8624ec6c1cec289/tests/code_quality/for.c.txt#L1)):*
> ```
> /* Package main - transpiled by c2go
> ```

Keep the `.c` file type so that it can still be understood by IDEs and run on the CLI. Perhaps `for.expected.c`?

---

*[transpiler/branch.go, line 233 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/564#-L2w0-owA2Vny8HBqGqg:-L2w0-owA2Vny8HBqGqh:b-uend1o) ([raw file](https://github.com/elliotchance/c2go/blob/5b3937e2aa78af79c353dd20f8624ec6c1cec289/transpiler/branch.go#L233)):*
> ```Go
> 	var post goast.Stmt
> 	var transpilate bool
> 	if v, ok := children[3].(*ast.UnaryOperator); ok && v.Operator == "++" {
> ```

What about the `--` operator?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/564)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[tests/code_quality/for.c.txt, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/564#-L2w-deAdONMV-CVltKU:-L2xxJOtOtikyg6Ie6d7:bw0y3i2) ([raw file](https://github.com/elliotchance/c2go/blob/5b3937e2aa78af79c353dd20f8624ec6c1cec289/tests/code_quality/for.c.txt#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Keep the `.c` file type so that it can still be understood by IDEs and run on the CLI. Perhaps `for.expected.c`?
</blockquote></details>

Not clear for myself. That file is result of transpilation - Go Expected file.
May be `for.c.go.expected` or ...?

---

*[transpiler/branch.go, line 233 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/564#-L2w0-owA2Vny8HBqGqg:-L2xy5IiSJo0o959eBxs:b8uh4vf) ([raw file](https://github.com/elliotchance/c2go/blob/5b3937e2aa78af79c353dd20f8624ec6c1cec289/transpiler/branch.go#L233)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

What about the `--` operator?
</blockquote></details>

Ok, I will implement `--`, but after #558

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/564)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[tests/code_quality/for.c.txt, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/564#-L2w-deAdONMV-CVltKU:-L30812jZcpf4AFE5Hed:b-n70pgy) ([raw file](https://github.com/elliotchance/c2go/blob/5b3937e2aa78af79c353dd20f8624ec6c1cec289/tests/code_quality/for.c.txt#L1)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

Not clear for myself. That file is result of transpilation - Go Expected file.
May be `for.c.go.expected` or ...?
</blockquote></details>

I'm saying keep the extension as `.c` so that the code is recognised as C code. `for.c.go.expected` would have an extension of `.expected` which would be the same as calling it `.txt`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/564)*

**Comment by Konstantin8105** [comment]
Ready for review

**Comment by Konstantin8105** [comment]
Merged to #558

**Pull request closed without merging**
