### PR TITLE
Future/69 go ast

### PR DESCRIPTION
**Pull request by elliotchance**
This is a large refactoring to render the output with the `go/ast` package instead of building the code manually with strings.

Since this is such a massive PR, it is broken down into several stages so that others can understand the progress.

- [x] All tests work on Mac. This is almost done and is the majority of the work.
- [x] All tests also work on Linux.
- [x] Remove all the existing "render" stuff.
- [x] Go through (pun intended) the code and add comments and TODOs where necessary.

Once the first two are done (the build is green) it would be great if anyone wanted to code review parts or all of the changes :)

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/72)

### CODE REVIEW

**Comment by cristim** [comment]
Once merged, this would fix #69.

**Comment by cristim** [comment]
Reviewed 1 of 8 files at r1, 3 of 16 files at r2, 64 of 64 files at r3.
Review status: 68 of 77 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/72)*

**Comment by cristim** [comment]
Reviewed 5 of 16 files at r2.
Review status: 70 of 77 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[transpiler/functions.go, line 15 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI16BdZX61NVorW_lD:-KjI16BeGhkfkyxxQpcO:b4ckvh4) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/functions.go#L15)):*
> ```Go
> 
> func transpileCallExpr(n *ast.CallExpr, p *program.Program) (*goast.CallExpr, string, error) {
> 	functionName := n.Children[0].(*ast.ImplicitCastExpr).Children[0].(*ast.DeclRefExpr).Name
> ```

I'd split this on multiple lines, because things may blow up in a lot of places on this line if anything is nil.

Because we have so many dereferences it may be hard to find out which one was it.

---

*[transpiler/literals.go, line 40 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI2TWkubF__rresUaa:-KjI2TWlvofwHABut2rL:b-ytwhos) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/literals.go#L40)):*
> ```Go
> 	var s string
> 
> 	// TODO: There are other characters to escape.
> ```

Perhaps we should  panic for those, so we can easier catch the missing cases.

---

*[transpiler/literals.go, line 64 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI2rahD25p7sycKf3Y:-KjI2raiDL5Sa-v0tC2X:b-r5d0xf) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/literals.go#L64)):*
> ```Go
> 		// FIXME
> 		value = "\"void print_number(int *)\""
> ```

I don't understand this "magic", perhaps it needs better comments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/72)*

**Comment by elliotchance** [comment]
Review status: 70 of 77 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[transpiler/functions.go, line 15 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI16BdZX61NVorW_lD:-KjIBmDjx3_84pyQyxUP:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/functions.go#L15)):*
<details><summary><i>Previously, cristim (Cristian Măgherușan-Stanciu @magheru_san) wrote…</i></summary><blockquote>

I'd split this on multiple lines, because things may blow up in a lot of places on this line if anything is nil.

Because we have so many dereferences it may be hard to find out which one was it.
</blockquote></details>

Done.

---

*[transpiler/literals.go, line 40 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI2TWkubF__rresUaa:-KjIC73EVlJsCzttdf7X:ba6w47x) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/literals.go#L40)):*
<details><summary><i>Previously, cristim (Cristian Măgherușan-Stanciu @magheru_san) wrote…</i></summary><blockquote>

Perhaps we should  panic for those, so we can easier catch the missing cases.
</blockquote></details>

I have created an issue and added a comment.

---

*[transpiler/literals.go, line 64 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/72#-KjI2rahD25p7sycKf3Y:-KjIAsnR22l7JXGsqpF_:b-dkf490) ([raw file](https://github.com/elliotchance/c2go/blob/6c44629f40b836071b8759bb324c54863199ac0c/transpiler/literals.go#L64)):*
<details><summary><i>Previously, cristim (Cristian Măgherușan-Stanciu @magheru_san) wrote…</i></summary><blockquote>

I don't understand this "magic", perhaps it needs better comments?
</blockquote></details>

I have created an issue for this and added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/72)*

**Pull request merged**
