### PR TITLE
Implement goto. Fixes #269

### LINKED ISSUE #269: Implement goto
goto is not currently implemented

This prints "2" when compiled with gcc/clang.
```
#include <stdio.h>

int main()
{
    int i = 0;

    mylabel: i++;

    if (i == 1) {
        goto mylabel;
    }

    printf("%d\n", i);
}
```

AST:
```
`-FunctionDecl 0x5589ccdf0830 <main.c:3:1, line:14:1> line:3:5 main 'int ()'
  `-CompoundStmt 0x5589ccdf0c60 <line:4:1, line:14:1>
    |-DeclStmt 0x5589ccdf0968 <line:5:5, col:14>
    | `-VarDecl 0x5589ccdf08e8 <col:5, col:13> col:9 used i 'int' cinit
    |   `-IntegerLiteral 0x5589ccdf0948 <col:13> 'int' 0
    |-LabelStmt 0x5589ccdf0a10 <line:7:5, col:15> 'mylabel'
    | `-UnaryOperator 0x5589ccdf09a8 <col:14, col:15> 'int' postfix '++'
    |   `-DeclRefExpr 0x5589ccdf0980 <col:14> 'int' lvalue Var 0x5589ccdf08e8 'i' 'int'
    |-IfStmt 0x5589ccdf0ae8 <line:9:5, line:11:5>
    | |-<<<NULL>>>
    | |-BinaryOperator 0x5589ccdf0a88 <line:9:9, col:14> 'int' '=='
    | | |-ImplicitCastExpr 0x5589ccdf0a70 <col:9> 'int' <LValueToRValue>
    | | | `-DeclRefExpr 0x5589ccdf0a28 <col:9> 'int' lvalue Var 0x5589ccdf08e8 'i' 'int'
    | | `-IntegerLiteral 0x5589ccdf0a50 <col:14> 'int' 1
    | |-CompoundStmt 0x5589ccdf0ac8 <col:17, line:11:5>
    | | `-GotoStmt 0x5589ccdf0ab0 <line:10:9, col:14> 'mylabel' 0x5589ccdf09c8
    | `-<<<NULL>>>
    `-CallExpr 0x5589ccdf0be0 <line:13:5, col:21> 'int'
      |-ImplicitCastExpr 0x5589ccdf0bc8 <col:5> 'int (*)(const char *, ...)' <FunctionToPointerDecay>
      | `-DeclRefExpr 0x5589ccdf0b18 <col:5> 'int (const char *, ...)' Function 0x5589ccde4148 'printf' 'int (const char *, ...)'
      |-ImplicitCastExpr 0x5589ccdf0c30 <col:12> 'const char *' <BitCast>
      | `-ImplicitCastExpr 0x5589ccdf0c18 <col:12> 'char *' <ArrayToPointerDecay>
      |   `-StringLiteral 0x5589ccdf0b40 <col:12> 'char [4]' lvalue "%d\n"
      `-ImplicitCastExpr 0x5589ccdf0c48 <col:20> 'int' <LValueToRValue>
        `-DeclRefExpr 0x5589ccdf0b70 <col:20> 'int' lvalue Var 0x5589ccdf08e8 'i' 'int'
```

Current go
```
func main() {
   __init()
   var i int = 0
   nil
   if i == 1 {
      nil
   }
   noarch.Printf([]byte("%d\n\x00"), i)
}
```

Expected go
```
func main() {
   __init()
   var i int = 0
mylabel:
   i++
   if i == 1 {
      goto mylabel
   }
   noarch.Printf([]byte("%d\n\x00"), i)
}
```

### PR DESCRIPTION
**Pull request by yulvil**
for issue #269

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/271)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 355 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/271#-KxFVWEU_AlOz4ve7xiF:-KxFVWEU_AlOz4ve7xiG:b-6o9cgm) ([raw file](https://github.com/elliotchance/c2go/blob/f3e5419473b01d1a425a5de22ea7b5dd1e91106d/transpiler/transpiler.go#L355)):*
> ```Go
> }
> 
> func transpileLabelStmt(n *ast.LabelStmt, p *program.Program) (*goast.LabeledStmt, error) {
> ```

Please move `transpileLabelStmt` and `transpileGotoStmt` into a new file `transpiler/goto.go`. I want to keep this file free from pollution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/271)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/271#-KxFVqQKUvWOEef92u1S:-KxFVqQKUvWOEef92u1T:bfx7wnv) (no related file):*
There was only one minor change -- great PR!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/271)*

**Comment by yulvil** [comment]
@elliotchance Sorry about the small commits. Thankfully you can do a merge-commit into your repo.

**Comment by yulvil** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpiler.go, line 355 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/271#-KxFVWEU_AlOz4ve7xiF:-KxFjEu_fqUn2m2vny1Y:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f3e5419473b01d1a425a5de22ea7b5dd1e91106d/transpiler/transpiler.go#L355)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please move `transpileLabelStmt` and `transpileGotoStmt` into a new file `transpiler/goto.go`. I want to keep this file free from pollution.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/271)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/goto.go, line 1 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/271#-KxFkTHuu1kjO_ulWG36:-KxFkTHuu1kjO_ulWG37:b97bpox) ([raw file](https://github.com/elliotchance/c2go/blob/a7bef8d658a2f9eaa6e67313bcff592234bfe80d/transpiler/goto.go#L1)):*
> ```Go
> // This file contains functions for transpiling goto/label statements.
> ```

Perfect! :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/271)*

**Pull request merged**
