### PR TITLE
Add partial support for syslog.h

### PR DESCRIPTION
**Pull request by gmp216**
I thought this might be helpful as I am coming across AST nodes that c2go doesn't seem to need to know about.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/670)

### CODE REVIEW

**Comment by gmp216** [comment]
Got it, makes sense.

Let me know if you think it could be useful to define a catch-all node type for certain types of attributes that c2go doesn't need to know about (except as you point out for position info and tree structure). For example I am seeing a lot of function attributes that do not seem to provide any useful information to c2go -- e.g. from darwin /include/sys/syslog.h:

`void    syslog(int, const char *, ...) __printflike(2, 3) __not_tail_called;`

Perhaps some kind of generic function declaration attribute to scoop up things like this?

**Comment by elliotchance** [comment]
It's true that there are lots of nodes that don't provide any useful information. However they still have to be read to create the consistent tree. Until the cost benefit flips the other way let's keep it how it is. If you find any cases that cannot be understood by c2go (cases a panic) then we should create test cases for these.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/670#-:-L9hgQ0R3E1M36XYFFD-:b-tufr53)*

**Comment by gmp216** [comment]
Thanks for your response, fully agree with your points as my understanding of the Clang AST was incomplete. As an alternative you might consider the addition of a noarch/syslog.go and a new node type for NotTailCalledAttr, which shows up in the Darwin version of syslog.h.

As golang's builtin "log/syslog" is no longer maintained and is not available on Windows, this may not be ideal, but it could at least assist in porting c code that includes syslog.h.

**Comment by elliotchance** [comment]
Reviewed 7 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/c2go/670)*

**Pull request merged**
