### PR TITLE
Pointer initialization. Fixes #382 and #381

### LINKED ISSUE #381: null pointer
Little example:
```c
int main(){
        double u = 4.444;
        if ( &u == (double *) 0){
                return 1;
        }
        return 0;
}
```
pp.c:
```
# 1 "1.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 317 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "1.c" 2
int main(){
 double u = 4.444;
 if ( &u == (double *) 0){
  return 1;
 }
 return 0;
}
```
Ast dump:
```
`-FunctionDecl 0x2318730 <1.c:1:1, line:7:1> line:1:5 main 'int ()'
  `-CompoundStmt 0x236b148 <col:11, line:7:1>
    |-DeclStmt 0x236af68 <line:2:2, col:18>
    | `-VarDecl 0x236aee8 <col:2, col:13> col:9 used u 'double' cinit
    |   `-FloatingLiteral 0x236af48 <col:13> 'double' 4.444000e+00
    |-IfStmt 0x236b0d8 <line:3:2, line:5:2>
    | |-<<<NULL>>>
    | |-<<<NULL>>>
    | |-BinaryOperator 0x236b058 <line:3:7, col:24> 'int' '=='
    | | |-UnaryOperator 0x236afd8 <col:7, col:8> 'double *' prefix '&'
    | | | `-DeclRefExpr 0x236af80 <col:8> 'double' lvalue Var 0x236aee8 'u' 'double'
    | | `-CStyleCastExpr 0x236b030 <col:13, col:24> 'double *' <NullToPointer>
    | |   `-IntegerLiteral 0x236aff8 <col:24> 'int' 0
    | |-CompoundStmt 0x236b0b8 <col:26, line:5:2>
    | | `-ReturnStmt 0x236b0a0 <line:4:3, col:10>
    | |   `-IntegerLiteral 0x236b080 <col:10> 'int' 1
    | `-<<<NULL>>>
    `-ReturnStmt 0x236b130 <line:6:2, col:9>
      `-IntegerLiteral 0x236b110 <col:9> 'int' 0
```
go code:
```go
func main() {
        __init()
        var u float64 = 4.444
        if (*[1]float64)(unsafe.Pointer(&u))[:] == noarch.IntToFloat64Slice(noarch.IntToFloat64Slice(0)) {
                os.Exit(1)
        }
        return
}
```

Best result in Go:
```go
package main

import(
	"os"
)

func main(){
	u := 4.444
	if &u == nil{
		os.Exit(1)
	}
	return
}
```
https://play.golang.org/p/IdT-UiBA_j

### LINKED ISSUE #382: pointer initialization
Example:
```c
int main(){
        double *f = (double *) 0;
        return 0;
}
```
pp.c:
```
# 1 "2.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 317 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "2.c" 2
int main(){
 double *f = (double *) 0;
 return 0;
}
```
ast tree:
```
`-FunctionDecl 0x2b95730 <2.c:1:1, line:4:1> line:1:5 main 'int ()'
  `-CompoundStmt 0x2be8000 <col:11, line:4:1>
    |-DeclStmt 0x2be7fb0 <line:2:2, col:26>
    | `-VarDecl 0x2be7ef0 <col:2, col:25> col:10 f 'double *' cinit
    |   `-CStyleCastExpr 0x2be7f88 <col:14, col:25> 'double *' <NullToPointer>
    |     `-IntegerLiteral 0x2be7f50 <col:25> 'int' 0
    `-ReturnStmt 0x2be7fe8 <line:3:2, col:9>
      `-IntegerLiteral 0x2be7fc8 <col:9> 'int' 0
```
golang:
```go
func main() {
        __init()
        var f []float64 = noarch.IntToFloat64Slice(noarch.IntToFloat64Slice(0))
        return
}
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #382 
Close #381

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/392)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/cast.c, line 43 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/392#-L-T_0350rNmMS3F1Xqq:-L-T_0350rNmMS3F1Xqr:b9qpjj) ([raw file](https://github.com/elliotchance/c2go/blob/9e1d50fd5b036354fe42547ba3ccbdf7b83a9310/tests/cast.c#L43)):*
> ```C
> 	assert(f == NULL);
> 	char   *c = (char   *) 0;
> 	assert(c == NULL);
> ```

Please use `is_ok(c == NULL)` instead so that only the `assert.c` tests need to use `assert.h`. Also we can guarantee that `is_ok` will work, assert may be disabled and we would not know if this would fail in the future.

---

*[tests/if.c, line 28 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/392#-L-T_WDgrRQk18ZrYlvS:-L-T_WDgrRQk18ZrYlvT:bpd3h6s) ([raw file](https://github.com/elliotchance/c2go/blob/9e1d50fd5b036354fe42547ba3ccbdf7b83a9310/tests/if.c#L28)):*
> ```C
> 		pass("%s", "NULL is zero");
> 	} else {
> 		pass("%s", "NULL is not zero");
> ```

Use `fail` instead. Neither the C or the Go should reach in here.

---

*[tests/if.c, line 32 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/392#-L-T_b4hRdVYBqAgSRju:-L-T_b4hRdVYBqAgSRjv:bpd3h6s) ([raw file](https://github.com/elliotchance/c2go/blob/9e1d50fd5b036354fe42547ba3ccbdf7b83a9310/tests/if.c#L32)):*
> ```C
> 
> 	if ( ! NULL) {
> 		pass("%s", "Invert : ! NULL is zero");
> ```

Use `fail` instead. Neither the C or the Go should reach in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/392)*

**Comment by elliotchance** [comment]
This is a great PR :thumbsup: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/392#-:-L-TaDqK-d5wYzSW4QbR:b8zwhk5)*

**Comment by Konstantin8105** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/cast.c, line 43 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/392#-L-T_0350rNmMS3F1Xqq:-L-XsbPPxGuBH6YtpukM:bb7f2mf) ([raw file](https://github.com/elliotchance/c2go/blob/9e1d50fd5b036354fe42547ba3ccbdf7b83a9310/tests/cast.c#L43)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please use `is_ok(c == NULL)` instead so that only the `assert.c` tests need to use `assert.h`. Also we can guarantee that `is_ok` will work, assert may be disabled and we would not know if this would fail in the future.
</blockquote></details>

done

---

*[tests/if.c, line 28 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/392#-L-T_WDgrRQk18ZrYlvS:-L-XseoK1V6Ih1voGLL-:bb7f2mf) ([raw file](https://github.com/elliotchance/c2go/blob/9e1d50fd5b036354fe42547ba3ccbdf7b83a9310/tests/if.c#L28)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Use `fail` instead. Neither the C or the Go should reach in here.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/392)*

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/392)*

**Pull request merged**
