### PR TITLE
File identification for warnings

### PR DESCRIPTION
**Pull request by Konstantin8105**
* In according to our discussion later, I add version at the top of Go file
* Add file identification for warning
Example of result:
```go
/*
        Package main - transpiled by c2go version: v0.21.0 Zinc 2018-01-11

        If you have found any issues, please raise an issue at:
        https://github.com/elliotchance/c2go/
*/

// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 2323: Cannot resolve type 'void ( *(*)(sqlite3_vfs *, void *, char *))(void)' : function pointers are not supported [2] : 'void ( *(*)(sqlite3_vfs *, void *, char *))(void)'
// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 2338: Cannot resolve type 'int (*)(sqlite3_vfs *, char *, sqlite3_syscall_ptr)' : function pointers are not supported [1] : 'int (*)(sqlite3_vfs *, char *, sqlite3_syscall_ptr)'
// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 2339: Cannot resolve type 'sqlite3_syscall_ptr (*)(sqlite3_vfs *, char *)' : function pointers are not supported [1] : 'sqlite3_syscall_ptr (*)(sqlite3_vfs *, char *)'
// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 7100: Cannot resolve type 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)' : function pointers are not supported [1] : 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)'
// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 7103: Cannot resolve type 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)' : function pointers are not supported [1] : 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)'
// Warning (FieldDecl): file : ...3210000/sqlite3.c , line : 7106: Cannot resolve type 'int (*)(sqlite3_vtab *, sqlite3_index_info *)' : function pointers are not supported [1] : 'int (*)(sqlite3_vtab *, sqlite3_index_info *)'
```

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/559)

### CODE REVIEW

**Comment by elliotchance** [comment]
Nice!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[main.go, line 254 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vx9OJf5BwKVEkwfXY:-L2vx9OJf5BwKVEkwfXZ:b-hk20fb) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/main.go#L254)):*
> ```Go
> 	p.OutputAsTest = args.outputAsTest
> 	p.Comments = comments
> 	p.Version = Version
> ```

I understand this is required because the sub packages cannot reference the main package but I also see this as a bug (my fault). c2go could also be used as a library for other packages and they would need to be able to access this reliably as well.

To me it makes sense to create a `program/version.go` and move the constant in there so that all packages can access `program.Version` and you won't need to pass the version through the `Program` struct.

---

*[ast/position.go, line 24 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vwIRqRL3vGVraxmrv:-L2vwIRrOK6oZU7NDxky:b6z941g) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/ast/position.go#L24)):*
> ```Go
> // GetSimpleLocation - return a string like : "file : 1.c , line : 100" in
> // accoring to position
> func (p Position) GetSimpleLocation() (loc string) {
> ```

I think this is more verbose than it needs to be. It's pretty common in most languages to use "file:line" format, like:

```
// Warning (FieldDecl): /foo/bar/sqlite3.c:2323: ...
```

---

*[ast/position.go, line 27 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vwkS78lNNRsUj24lu:-L2vwkS78lNNRsUj24lv:b-ntgr0r) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/ast/position.go#L27)):*
> ```Go
> 	fs := len(p.File)
> 	if fs > 20 {
> 		loc += fmt.Sprintf("file : ...%s", p.File[fs-17:])
> ```

Do not truncate the file name. Maybe its better to resolve the absolute file name. This does not make it shorter but it does make it easier to do string replace on for build systems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/559#-:-L2vvorzZhPJftHLPpAm:b-83sjoh)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[main.go, line 254 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vx9OJf5BwKVEkwfXY:-L2y7hNP9eCLGnFezj85:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/main.go#L254)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I understand this is required because the sub packages cannot reference the main package but I also see this as a bug (my fault). c2go could also be used as a library for other packages and they would need to be able to access this reliably as well.

To me it makes sense to create a `program/version.go` and move the constant in there so that all packages can access `program.Version` and you won't need to pass the version through the `Program` struct.
</blockquote></details>

Done.

---

*[ast/position.go, line 24 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vwIRqRL3vGVraxmrv:-L2y7uBK1yQyPq3r7_Mt:b2nhll9) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/ast/position.go#L24)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I think this is more verbose than it needs to be. It's pretty common in most languages to use "file:line" format, like:

```
// Warning (FieldDecl): /foo/bar/sqlite3.c:2323: ...
```
</blockquote></details>

Ok.

---

*[ast/position.go, line 27 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/559#-L2vwkS78lNNRsUj24lu:-L2y8qPc9xTc_aaN0B1w:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/77c23df5629471eb6f6618fd10c902d6cb2dc5df/ast/position.go#L27)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Do not truncate the file name. Maybe its better to resolve the absolute file name. This does not make it shorter but it does make it easier to do string replace on for build systems.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/559)*

**Comment by Konstantin8105** [comment]
Example of result:
```go
/*
        Package main - transpiled by c2go version: v0.21.0 Zinc 2018-01-11

        If you have found any issues, please raise an issue at:
        https://github.com/elliotchance/c2go/
*/

// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:2323 : Cannot resolve type 'void ( *(*)(sqlite3_vfs *, void *, char *))(void)' : function pointers are not supported [2] : 'void ( *(*)(sqlite3_vfs *, void *, char *))(void)'
// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:2338 : Cannot resolve type 'int (*)(sqlite3_vfs *, char *, sqlite3_syscall_ptr)' : function pointers are not supported [1] : 'int (*)(sqlite3_vfs *, char *, sqlite3_syscall_ptr)'
// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:2339 : Cannot resolve type 'sqlite3_syscall_ptr (*)(sqlite3_vfs *, char *)' : function pointers are not supported [1] : 'sqlite3_syscall_ptr (*)(sqlite3_vfs *, char *)'
// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:7100 : Cannot resolve type 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)' : function pointers are not supported [1] : 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)'
// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:7103 : Cannot resolve type 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)' : function pointers are not supported [1] : 'int (*)(sqlite3 *, void *, int, char **, sqlite3_vtab **, char **)'
// Warning (FieldDecl):  /tmp/SQLITE/sqlite-amalgamation-3210000/sqlite3.c:7106 : Cannot resolve type 'int (*)(sqlite3_vtab *, sqlite3_index_info *)' : function pointers are not supported [1] : 'int (*)(sqlite3_vtab *, sqlite3_index_info *)'
```

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/559)*

**Comment by Konstantin8105** [comment]
Merged to #558

**Pull request closed without merging**
