### PR TITLE
Support switch label clauses. Fixes #693

### LINKED ISSUE #693: Cannot use labels as switch cases
In C we can use labels as switch cases:
```
switch(0) {
case 0:
    goto LABEL;
    break;
LABEL:
case 1:
    printf("hurray");
}
```
Go doesn't allow that and c2go doesn't handle that case.

### PR DESCRIPTION
**Pull request by kamphaus**
Fixes #693

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/694)

### CODE REVIEW

**Comment by elliotchance** [comment]
You have accidentally committed the `vendor` folder.

**Comment by kamphaus** [comment]
Vendor folder is removed.

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[transpiler/switch.go, line 13 at r5](https://reviewable.io/reviews/elliotchance/c2go/694#-LECVFOeBSe8ulrdqfxK:-LECVFOeBSe8ulrdqfxL:b-a6stf9) ([raw file](https://github.com/elliotchance/c2go/blob/0f6a60b9fd167654926aac166c383a6294a9cdcd/transpiler/switch.go#L13)):*
> ```Go
> 	"github.com/elliotchance/c2go/program"
> 	"github.com/elliotchance/c2go/util"
> 	"golang.org/x/tools/go/ast/astutil"
> ```

Is this bundled with go or do you need it add to `dep` requirements?

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/694)*

**Comment by kamphaus** [comment]
*[transpiler/switch.go, line 13 at r5](https://reviewable.io/reviews/elliotchance/c2go/694#-LECVFOeBSe8ulrdqfxK:-LEFrguAAfeIsVQZQolE:b2b25wb) ([raw file](https://github.com/elliotchance/c2go/blob/0f6a60b9fd167654926aac166c383a6294a9cdcd/transpiler/switch.go#L13)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this bundled with go or do you need it add to `dep` requirements?
</blockquote></details>

`astutil` is not bundled with go.

Installing/updating `c2go` with `go get -u github.com/elliotchance/c2go` will take care to download the latest version of `astutil` into the `$GOPATH`.

By needing to add it to `dep` requirements, did you mean add it to the documentation as a requirement, or did you mean to use the `dep` tool, which is a dependency management tool (https://golang.github.io/dep/docs/introduction.html)?

Since `astutil` is authored by Google, the chance of a breaking change should be minimal, so I don't see the need at the moment for a dependency management tool. (Maybe later, if there are other dependencies)

PS: see https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory on the pros/cons of committing the vendor folder.

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/694)*

**Comment by elliotchance** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @elliotchance)

---

*[transpiler/switch.go, line 13 at r5](https://reviewable.io/reviews/elliotchance/c2go/694#-LECVFOeBSe8ulrdqfxK:-LEl_onW2ugBMGzRK7g8:b6onxyn) ([raw file](https://github.com/elliotchance/c2go/blob/0f6a60b9fd167654926aac166c383a6294a9cdcd/transpiler/switch.go#L13)):*
<details><summary><i>Previously, kamphaus wrote…</i></summary><blockquote>

`astutil` is not bundled with go.

Installing/updating `c2go` with `go get -u github.com/elliotchance/c2go` will take care to download the latest version of `astutil` into the `$GOPATH`.

By needing to add it to `dep` requirements, did you mean add it to the documentation as a requirement, or did you mean to use the `dep` tool, which is a dependency management tool (https://golang.github.io/dep/docs/introduction.html)?

Since `astutil` is authored by Google, the chance of a breaking change should be minimal, so I don't see the need at the moment for a dependency management tool. (Maybe later, if there are other dependencies)

PS: see https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory on the pros/cons of committing the vendor folder.
</blockquote></details>

That's fair enough. c2go is still alpha enough that we can get away without locking versions.

As for committing the vendor folder, everything is a trade off. Unless your building extremely defensive software committing the vendor folder just bloats your codebase and opens the potential for people to tweak the vendor code.

I have only used `dep` for some projects at work, but have used package managers in other languages for years and I can't think of a single time in recently memory where a vendor has broken something that affected our builds or deploys.

---


*Comments from [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/694)*

**Pull request merged**
