### PR TITLE
CSTD stdlib qsort implementation. Fixes #222

### LINKED ISSUE #222: Implement qsort()

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #222 
Created for #67

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/518)

### CODE REVIEW

**Comment by elliotchance** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[transpiler/call.go, line 109 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1nso7PcpzTqtIetrWF:-L1nso7PcpzTqtIetrWG:bf8go3r) ([raw file](https://github.com/elliotchance/c2go/blob/0b76154818fa42db9bec96737db3bd0f5f35b4d7/transpiler/call.go#L109)):*
> ```Go
> 
> 	// function "qsort" from stdlib.h
> 	if functionName == "qsort" && len(n.Children()) == 5 {
> ```

Is it possible to implement `qsort` without modifying the transpiler? Implemented in pure Go like the other cstdlib functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by Konstantin8105** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[transpiler/call.go, line 109 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1nso7PcpzTqtIetrWF:-L1nw8uHSCAasZaZANSt:bgr8l9m) ([raw file](https://github.com/elliotchance/c2go/blob/0b76154818fa42db9bec96737db3bd0f5f35b4d7/transpiler/call.go#L109)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is it possible to implement `qsort` without modifying the transpiler? Implemented in pure Go like the other cstdlib functions.
</blockquote></details>

I try that way at the first, but without success. So, I implemented inside transpiler

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/call.go, line 109 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1nso7PcpzTqtIetrWF:-L1t67zr5ynIATqtfoct:bj8f16a) ([raw file](https://github.com/elliotchance/c2go/blob/2c56ba57feb4b7e0e19e9da2f28cc03ad254f3a8/transpiler/call.go#L109)):*
<details><summary><i>Previously, Konstantin8105 (Konstantin) wrote…</i></summary><blockquote>

I try that way at the first, but without success. So, I implemented inside transpiler
</blockquote></details>

I'll accept this change because it is better than having qsort not implemented at all, but I've created a ticket to be revisited later: https://github.com/elliotchance/c2go/issues/520

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/call.go, line 112 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1t7GqiR_EIvIT64iik:-L1t7GqiR_EIvIT64iil:b-lxz8i6) ([raw file](https://github.com/elliotchance/c2go/blob/2c56ba57feb4b7e0e19e9da2f28cc03ad254f3a8/transpiler/call.go#L112)):*
> ```Go
> 		defer func() {
> 			if err != nil {
> 				err = fmt.Errorf("Function: qsort. err = ", err)
> ```

CodeClimate caught this one, you are not appending the error message:

```go
err = fmt.Errorf("Function: qsort. err = %v", err)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/call.go, line 112 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1t7GqiR_EIvIT64iik:-L1xFYHYHcXdUJCEbitm:boyexbg) ([raw file](https://github.com/elliotchance/c2go/blob/2c56ba57feb4b7e0e19e9da2f28cc03ad254f3a8/transpiler/call.go#L112)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

CodeClimate caught this one, you are not appending the error message:

```go
err = fmt.Errorf("Function: qsort. err = %v", err)
```
</blockquote></details>

Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by Konstantin8105** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/call.go, line 109 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/518#-L1nso7PcpzTqtIetrWF:-L1xGHGKyk8erIzIlZAD:b-49fyr1) ([raw file](https://github.com/elliotchance/c2go/blob/2c56ba57feb4b7e0e19e9da2f28cc03ad254f3a8/transpiler/call.go#L109)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'll accept this change because it is better than having qsort not implemented at all, but I've created a ticket to be revisited later: https://github.com/elliotchance/c2go/issues/520
</blockquote></details>

Yes, In my pointer of view #520 is acceptable after #503 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/518)*

**Pull request merged**
