### PR TITLE
Fixed struct array initialization #264

### PR DESCRIPTION
**Pull request by yulvil**
Reverted code from newDeclStmt and moved the array initialization
logic to the transpileInitListExpr function

Ref: #264 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/283)

### CODE REVIEW

**Comment by yulvil** [comment]
@elliotchance Let me know if there is anything to change.

**Comment by elliotchance** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ast/init_list_expr_test.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/283#-KxeFSBW-NuBk6C4jff4:-KxeFSBW-NuBk6C4jff5:b-qy7mw6) ([raw file](https://github.com/elliotchance/c2go/blob/87fef2c0a659bcc2bad6f59070f11be2af7eabf5/ast/init_list_expr_test.go#L15)):*
> ```Go
> 			ChildNodes: []Node{},
> 		},
> 		`InitListExpr 0x32017f0 <col:24, col:41> 'struct node [2]'`: &InitListExpr{
> ```

I'm surprised this actually worked (matched the regex) with the `InitListExpr ` prefix. Please remove that prefix so it is the same as all the rest of our tests (and the one below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/283)*

**Comment by yulvil** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[ast/init_list_expr_test.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/283#-KxeFSBW-NuBk6C4jff4:-KxfX9qhxs2iJx1KtfT5:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/87fef2c0a659bcc2bad6f59070f11be2af7eabf5/ast/init_list_expr_test.go#L15)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm surprised this actually worked (matched the regex) with the `InitListExpr ` prefix. Please remove that prefix so it is the same as all the rest of our tests (and the one below).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/283)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/283)*

**Pull request merged**
