### PR TITLE
Concurrency for main.convertLinesToNodes. Fixes #290

### LINKED ISSUE #290: Performance
In according to tool `go tool trace` for transpiling file `shell.c` from `sqlite`:
screenshot at 2017-10-30 23 12 24

Now, `c2go` use only one core for transpiling.(on picture more core - it is GC working).

## Problem
Need to add concurrency if possible.

### PR DESCRIPTION
**Pull request by Konstantin8105**
See #290

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/298)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[main.go, line 106 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/298#-Kxtjf6cvciDlnJyzaUB:-Kxtjf6cvciDlnJyzaUC:b-u5rgwd) ([raw file](https://github.com/elliotchance/c2go/blob/f377212158b6480a5aa3d5c09e7906e4982afafe/main.go#L106)):*
> ```Go
> }
> 
> func convertLinesToNodesParallel(lines []string) []treeNode {
> ```

Awesome solution :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/298)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/298#-KxtmOWEUAVHkZNCo7G-:-KxtmOWFKyjprNuZOAci:b-3x7mrw) (no related file):*
I resolved the merge conflicts on this branch and another branch but Github makes you resolve it twice, even for squash. In the future i'll only let person that raises the PR resolve the conflicts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/298)*

**Comment by Konstantin8105** [comment]
Excuse me, I will learn about "git squash". Thank you for feedback.

**Comment by elliotchance** [comment]
@Konstantin8105 the two merges above was me testing if I could easily resolve the conflicts without having to push it back to the author to fix (which would take longer for the PR to be merged). However it look like GItHub is not very friendly with this. So to be safe in the future I will let the author handle the conflicts.

Separately to that there are three ways to merge in a PR in GitHub. One way is "Squash and Rebase". It squashes all of the commits in the PR into a single commit and rebases it onto the end.

I feel this works much better for a few reasons:

1. Often there are a lot of "Fix travis" or "lint cleanup" type commits (perfectly fine) which aren't useful to the general history. The whole PR is reduced into a single patch (commit) so viewing the commit history is a lot more readable and atomic.

2. I can choose the commit message at the time of merging, so I can make sure the commit message contains the appropriate Github issue numbers. This is super useful, see here: https://github.com/elliotchance/c2go/commits/master

3. Rebasing means that c2go will always have a clean, linear commit history (without all the messy branching)

I have been thinking about rebasing the existing commits to get rid of all the previous merges. Then c2go would have a single clean commit history going forward. Not sure what I am going to do about that right now though.

**Pull request merged**
