### PR TITLE
Comma problem for operator "FOR"

### PR DESCRIPTION
**Pull request by Konstantin8105**
In according to our discussion https://github.com/elliotchance/c2go/issues/154.
Now, Just solved COMMA problem for operator "FOR".
Tests are added.
Integration tests - will be OK )).
One pull request for one task.
Also, that patch solve issue in https://github.com/elliotchance/c2go/issues/133.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/181)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq7TIeY-_oAWFLq81n:-Knq7TIeY-_oAWFLq81o:bo19l5) (no related file):*
Great work @konstantin8105 !

---

*[tests/for.c, line 48 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq74gH9U0WhMh_32ww:-Knq74gH9U0WhMh_32wx:b-dupb5h) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/tests/for.c#L48)):*
> ```C
>     }
> 
> 	diag("big ininitialization");
> ```

Did you mean "initialization"?

---

*[tests/for.c, line 53 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq7BwInuPl_bktTynd:-Knq7BwInuPl_bktTyne:b-wiuu4k) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/tests/for.c#L53)):*
> ```C
> 	}
> 	
> 	diag("big ininitialization");
> ```

Please give this a different heading so it's easier to identify if the tests fails, like "big initialization 2"

---

*[transpiler/branch.go, line 138 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq6BefT55WYagbBRRM:-Knq6BefT55WYagbBRRN:bu8w9xq) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/transpiler/branch.go#L138)):*
> ```Go
> 	case *ast.BinaryOperator:
> 		c := children[0].(*ast.BinaryOperator)
> 		if c.Operator == "," {
> ```

There is a trick with Go when using type switching so that you don't have to use a temporary variable. You can assign a variable in the `switch` and it will always have the correct type from the `case`:

```go
switch c := children[0].(type) {
case *ast.BinaryOperator:
    if c.Operator == "," {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/181)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/for.c, line 48 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq74gH9U0WhMh_32ww:-Kns7A4ZL6FlEmTzTpek:b-7rl0jd) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/tests/for.c#L48)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Did you mean "initialization"?
</blockquote></details>

done.

---

*[tests/for.c, line 53 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq7BwInuPl_bktTynd:-Kns7F69gPBFv2sfDBoM:bb7f2mf) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/tests/for.c#L53)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please give this a different heading so it's easier to identify if the tests fails, like "big initialization 2"
</blockquote></details>

done

---

*[transpiler/branch.go, line 138 at r5](https://reviewable.io:443/reviews/elliotchance/c2go/181#-Knq6BefT55WYagbBRRM:-Kns8FLE5fh3VA4Bifhq:bb6un1j) ([raw file](https://github.com/elliotchance/c2go/blob/a1933539425c52aa4c0ad7af6efe4c8778d600ec/transpiler/branch.go#L138)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

There is a trick with Go when using type switching so that you don't have to use a temporary variable. You can assign a variable in the `switch` and it will always have the correct type from the `case`:

```go
switch c := children[0].(type) {
case *ast.BinaryOperator:
    if c.Operator == "," {
```
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/181)*

**Comment by Konstantin8105** [comment]
Thank you for review.
Just for information.
One source more is Ok, in according to my rating.
https://github.com/Konstantin8105/c2go-rating

Also, I will try to solve the COMMA problem for While, Do...While, IF, Function, but after that review.
Please don`t reject, that pull request - just because - it is not Absolute full solving.

Also, for your information - present test inside integration test is not full check. So, I test by hand on preliminary that code:
```c
#include <stdio.h>

int foo(int i)
{
	return i+i;
}

int main(void){
	int i,j,k = 8;
	for (i =0,j=1,printf("init\n"),k= 2;k+=5,printf("cond\n"),j++,j = foo(f),i<2000;i++,j+=2,printf("increment"),k+=3)
	{
		printf("%d %d %d\n",i,j,k);
	}
	return 0;
}
```
, but more more bigger.

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/181)*

**Comment by Konstantin8105** [comment]
Hello!
If all is Ok, then could you merge pull request.

**Comment by elliotchance** [comment]
Thanks @Konstantin8105 - https://github.com/elliotchance/c2go/releases/tag/v0.13.5

**Pull request merged**
