### PR TITLE
Refactored ast nodes into separate package

### PR DESCRIPTION
**Pull request by bongo227**
All the ast nodes seemed like a good candidate for separating out into a separate package so the root folder is cleaner.

I also merged `Render()` and `RenderLine()` into one `Render()` function since having both seemed redundant, this should also cover #38. This means we can get rid of all the slow reflection since all nodes now implement the `ast.Node` interface. 

TODO
- [x] Remove reflection code from buildTree
- [ ] Fix issue with the following variable declarations not working after the first test: `_LIB_VERSION, _IO_2_1_stdin_, _IO_2_1_stdout_, _IO_2_1_stderr_, stdin, stdout, stderr`
- [x] Fix incorrect coverage

If this is not how you want the project structured feel free to discard this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/45)

### CODE REVIEW

**Comment by elliotchance** [comment]
Hi @bongo227 - interestingly I did actually have all of these files in an `ast` package in earlier versions. I moved them out to the root package to get the code coverage working with the integration tests. I would much rather have several small packages that one massive `main` package.

For each TODO:

1. Nothing needs to be said on this, sounds good!
2. I ran in a similar issue on #30 . Global state is evil and now that the integration tests are working (thanks for that!) we should really refactor out the global state, or at least move all the initialisation to a single method that we can repeatedly call cleanly for now.
3. Either my laziness or haste I did not check if code coverage works across packages, but it looks like it can with the `-coverpkg`.

**Comment by elliotchance** [comment]
Reviewed 66 of 125 files at r1.
Review status: 36 of 66 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[main.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuAXZjBOxz-BD3jID1:-KhuAXZjBOxz-BD3jID2:brm7fg3) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/main.go#L15)):*
> ```Go
> 	"go/format"
> 
> 	"github.com/bongo227/c2go/ast"
> ```

Can we use a relative package name here?

---

*[ast/function_decl.go, line 57 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuE2pyY7VsbBcEjj26:-KhuE2pyY7VsbBcEjj27:b79u4j8) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/function_decl.go#L57)):*
> ```Go
> 	out := bytes.NewBuffer([]byte{})
> 
> 	ast.functionName = strings.TrimSpace(n.Name)
> ```

This trim is not necessary anymore. It was ported from the original Python.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by elliotchance** [comment]
Reviewed 59 of 125 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ast/common.go, line 51 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuR-expW5fCBFPIc4Y:-KhuR-expW5fCBFPIc4Z:b-scz0q4) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/common.go#L51)):*
> ```Go
> }
> 
> // func Render(out *bytes.Buffer, node interface{}, functionName string, indent int, returnType string) {
> ```

You can remove this now.

---

*[ast/compound_stmt.go, line 35 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuRAGvbKkQkHTgBj8_:-KhuRAGvbKkQkHTgBj8a:bj0lzzh) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/compound_stmt.go#L35)):*
> ```Go
> }
> 
> func (n *CompoundStmt) RenderLine(out *bytes.Buffer, functionName string, indent int, returnType string) {
> ```

Is this supposed to be here?

---

*[ast/resolve.go, line 77 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuPc1OVfGikPv1UJYX:-KhuPc1OVfGikPv1UJYY:bep1bhy) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/resolve.go#L77)):*
> ```Go
> }
> 
> func resolveType(ast *Ast, s string) string {
> ```

Not for this PR. But I would like to make the whole type resolving system a separate package (`resolve`?) with its own unit tests. This should also make it easier to handle more complex and state-oriented type resolutions like function pointers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by bongo227** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[main.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuAXZjBOxz-BD3jID1:-KhvQF1W4hmFe_PgXPP8:b-hdgmtc) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/main.go#L15)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Can we use a relative package name here?
</blockquote></details>

[Relative import paths are highly discouraged](https://golang.org/cmd/go/#hdr-Relative_import_paths), I was going to switch these out at the end with the correct path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[main.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuAXZjBOxz-BD3jID1:-KhvauuRrRQjVDODHvtU:bprid2y) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/main.go#L15)):*
<details><summary><i>Previously, bongo227 (Ben Sheffield) wrote…</i></summary><blockquote>

[Relative import paths are highly discouraged](https://golang.org/cmd/go/#hdr-Relative_import_paths), I was going to switch these out at the end with the correct path.
</blockquote></details>

That's fair enough. Or maybe it would be easier to rename your directory path to be the same when this pops up in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by elliotchance** [comment]
Reviewed 55 of 125 files at r1, 59 of 59 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ast/ast.go, line 52 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/45#-Khw8utl1-WfL8R_3eJt:-Khw8utl1-WfL8R_3eJu:b52ocwm) ([raw file](https://github.com/elliotchance/c2go/blob/802065dae604f21e6184303491e5d122673461b5/ast/ast.go#L52)):*
> ```Go
> type Node interface {
> 	render(ast *Ast) (string, string)
> 	AddChild(node Node)
> ```

It occurs to me that not all node types will have children, like a `StringLiteral`. For now it's easier to assume they all do, but maybe something like this?

```go
type NodeWithChildren interface {
    *Node
    AddChild(node Node)
}
```

However, this might be a bit too pedantic and maybe more appropriate for a separate PR where each node can be checked if it can indeed have children.

---

*[ast/common.go, line 51 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuR-expW5fCBFPIc4Y:-KhwA9dJOXhlmpY4a50j:b-muuedk) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/common.go#L51)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

You can remove this now.
</blockquote></details>

I'm not sure if you have used reviewable before or if you simply haven't responded to these yet. Discussions stay open until you respond (notice the handy "Done" button).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by bongo227** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[main.go, line 15 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuAXZjBOxz-BD3jID1:-KhwBVGTNFFvK8Gy219v:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/main.go#L15)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

That's fair enough. Or maybe it would be easier to rename your directory path to be the same when this pops up in the future.
</blockquote></details>

Done.

---

*[ast/ast.go, line 52 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/45#-Khw8utl1-WfL8R_3eJt:-KhwBYrwuJAtlGrF9dM8:byw949z) ([raw file](https://github.com/elliotchance/c2go/blob/802065dae604f21e6184303491e5d122673461b5/ast/ast.go#L52)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

It occurs to me that not all node types will have children, like a `StringLiteral`. For now it's easier to assume they all do, but maybe something like this?

```go
type NodeWithChildren interface {
    *Node
    AddChild(node Node)
}
```

However, this might be a bit too pedantic and maybe more appropriate for a separate PR where each node can be checked if it can indeed have children.
</blockquote></details>

Is their a spec for the clang AST anywhere? I haven't managed to find one. I agree that a separate PR is probably best for this one. 

---

*[ast/common.go, line 51 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuR-expW5fCBFPIc4Y:-KhwDQlaumLG3wgz0R_c:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/common.go#L51)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I'm not sure if you have used reviewable before or if you simply haven't responded to these yet. Discussions stay open until you respond (notice the handy "Done" button).
</blockquote></details>

Done.

---

*[ast/compound_stmt.go, line 35 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuRAGvbKkQkHTgBj8_:-KhwDWvMKF9AYu4Fr-hN:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/compound_stmt.go#L35)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Is this supposed to be here?
</blockquote></details>

Done.

---

*[ast/function_decl.go, line 57 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuE2pyY7VsbBcEjj26:-KhwDY1dbKUb7cmE0CYU:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/function_decl.go#L57)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This trim is not necessary anymore. It was ported from the original Python.
</blockquote></details>

Done.

---

*[ast/resolve.go, line 77 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/45#-KhuPc1OVfGikPv1UJYX:-KhwEDwVvUDjFRjKfz8k:bjb0gqo) ([raw file](https://github.com/elliotchance/c2go/blob/f4e30d31681db2f02cbe94568f95902719d31ade/ast/resolve.go#L77)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Not for this PR. But I would like to make the whole type resolving system a separate package (`resolve`?) with its own unit tests. This should also make it easier to handle more complex and state-oriented type resolutions like function pointers.
</blockquote></details>

Done. I created an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/45)*

**Comment by elliotchance** [comment]
@bongo227 this is a really great change. I'm happy to merge this in if your ready?

Codecov is failing because of the drop in coverage, that's understandable since all the new code. That will be cleaned up over time.

**Comment by bongo227** [comment]
Their is still a problem with those variable declarations (I just ignore them to parse the tests). This can probably be fixed when resolve is refactored out so I would say merging now would be fine.

**Comment by elliotchance** [comment]
Cheers: https://github.com/elliotchance/c2go/releases/tag/v0.8.7

**Pull request merged**
