### PR TITLE
Check function name with NewCallExpr

### PR DESCRIPTION
**Pull request by elliotchance**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/142)

### CODE REVIEW

**Comment by jorbs** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[program/program.go, line 169 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/142#-KlKNXaT_VSNnZzTZ6_M:-KlKNXaU3SffPqQkc842:b-k0rkim) ([raw file](https://github.com/elliotchance/c2go/blob/f542f0fa1a3e8eddad561386c2128c0a8e641c4b/program/program.go#L169)):*
> ```Go
> 		//     9190  .  .  .  .  .  .  .  .  .  Name: "noarch.[]intTo[]byte"
> 		//
> 		// These two lines are clearly the error becuase a name should not look
> ```

typo in "becuase"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/142)*

**Comment by jorbs** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/142)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[program/program.go, line 169 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/142#-KlKNXaT_VSNnZzTZ6_M:-KlKeVJgBr58H92lUDe6:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f542f0fa1a3e8eddad561386c2128c0a8e641c4b/program/program.go#L169)):*
<details><summary><i>Previously, jorbs (João Roberto) wrote…</i></summary><blockquote>

typo in "becuase"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/142)*

**Comment by jorbs** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/142)*

**Pull request merged**
