### PR TITLE
Typedef for union. Fixes #475, #496, #508, #522, #524 and #556

### LINKED ISSUE #475: typedef union
Example:
```c
	#include<stdio.h>
	int main()
	{

	    typedef union myunion
	    {
	  	    double PI;
		    int B;
	    }MYUNION;

		MYUNION numbers;
		numbers.PI = 3.14;
		numbers.B = 50;

	        return 0;
	}
```

### LINKED ISSUE #496: anonymous names
typical anonymous warnings
```
// Warning (FieldDecl): 69: I couldn't find an appropriate Go type for the C type '(anonymo
us struct at /usr/include/x86_64-linux-gnu/bits/waitstatus.h:69:5)'.
// Warning (FieldDecl): 84: I couldn't find an appropriate Go type for the C type '(anonymo
us struct at /usr/include/x86_64-linux-gnu/bits/waitstatus.h:84:5)'.
// Warning (FieldDecl): 141: I couldn't find an appropriate Go type for the C type '(anonym
ous struct at /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:141:3)'.
// Warning (FieldDecl): 177: I couldn't find an appropriate Go type for the C type '(anonym
ous struct at /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:177:3)'.
```
Solution:
> Rename from (anonymous struct at /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:177:3) to normal name

### LINKED ISSUE #508: simplification union transpiler
Simplification of file https://github.com/elliotchance/c2go/blob/master/transpiler/union.go
* Create a template
* Create a struct for template
* Create a generator of code
* Tranform from code to AST tree
* Inject to main AST tree

### LINKED ISSUE #522: Union inside struct
Warning:
```
// Error (VarDecl): 97713: Cannot resolve type '(anonymous union at /home/lepricon/go/bin/sqlite/s
qlite-amalgamation-3190300/sqlite3.c:14329:3)' : Cannot resolve type '(anonymous union at /home/lepri
con/go/bin/sqlite/sqlite-amalgamation-3190300/sqlite3.c:14329:3)' : probably an incorrect type transl
ation 3
```
In that code:
```c
struct FuncDef {
  i8 nArg;             /* Number of arguments.  -1 means unlimited */
  u16 funcFlags;       /* Some combination of SQLITE_FUNC_* */
  void *pUserData;     /* User data parameter */
  FuncDef *pNext;      /* Next function with same name */
  void (*xSFunc)(sqlite3_context*,int,sqlite3_value**); /* func or agg-step */
  void (*xFinalize)(sqlite3_context*);                  /* Agg finalizer */
  const char *zName;   /* SQL name of the function. */
  union {
    FuncDef *pHash;      /* Next with a different name but the same hash */
    FuncDestructor *pDestructor;   /* Reference counted destructor function */
  } u;
};
```

Minimaze c code for warning identification:
```c
typedef struct FuncDef FuncDef;
struct FuncDef {
  i8 nArg;
  union {
    FuncDef *pHash;
    FuncDestructor *pDestructor;
  } u;
};
```
Good name for inside union is not just `u`, - is `FuncDefUnionU`.
Also, we pointer of struct inside union inside itself struct.

### LINKED ISSUE #524: pointer on struct inside val function pointer of typedef struct
```c
typedef struct fts5_api fts5_api;
struct fts5_api {
  int iVersion; 
  int (*xCreateTokenizer)(
    fts5_api *pApi, /// <<--- THIS
    const char *zName
  );
};
```

### LINKED ISSUE #556: Crashes on enum with full comment
```c
/**
 * Comment
 */
typedef enum foo {
    bar = 1
} foo;

int main() {
}
```

Problematic piece of AST:

```
|-EnumDecl 0x5fd8be673708 <1.c:4:9, line:6:1> line:4:14 foo
| |-FullComment 0x5fd8be673ae0 <line:2:3, col:10>
| | `-ParagraphComment 0x5fd8be673ab0 <col:3, col:10>
| |   `-TextComment 0x5fd8be673a80 <col:3, col:10> Text=" Comment"
| `-EnumConstantDecl 0x5fd8be6737e0 <line:5:5, col:11> col:5 bar 'int'
|   `-IntegerLiteral 0x5fd8be6737c0 <col:11> 'int' 1
```

Error:
```
panic: interface conversion: ast.Node is *ast.FullComment, not *ast.EnumConstantDecl

goroutine 1 [running]:
github.com/elliotchance/c2go/transpiler.transpileEnumDecl(0xc4200fe000, 0xc4200da500, 0xc420043490, 0xc4200fe000, 0x6dd920, 0xc4200da500, 0x0)
	c2go/transpiler/enum.go:222 +0x20d8
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6dd920, 0xc4200da500, 0xc4200fe000, 0x0, 0x0, 0x0, 0x0, 0x0)
	c2go/transpiler/transpiler.go:487 +0x1fc
```

Fix:
```diff
diff --git a/transpiler/enum.go b/transpiler/enum.go
index 800182a..f812445 100644
--- a/transpiler/enum.go
+++ b/transpiler/enum.go
@@ -219,7 +219,11 @@ func transpileEnumDecl(p *program.Program, n *ast.EnumDecl) (decls []goast.Decl,
        // counter for replace iota
        var counter int
        for i, c := range n.Children() {
-               e, newPre, newPost := transpileEnumConstantDecl(p, c.(*ast.EnumConstantDecl))
+               cd, ok := c.(*ast.EnumConstantDecl)
+               if !ok {
+                       continue
+               }
+               e, newPre, newPost := transpileEnumConstantDecl(p, cd)
                preStmts, postStmts = combinePreAndPostStmts(preStmts, postStmts, newPre, newPost)
 
                e.Names[0].Obj = goast.NewObj(goast.Con, e.Names[0].Name)
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #475
Close #524 
Close #522 
Close #508 
Close #496 
Close #556 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/523)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
For success of that PR need #525

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/523)*

**Comment by Konstantin8105** [comment]
ready for review.

**Comment by elliotchance** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/binary.go, line 297 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/523#-L2XA4GHzZd7rMkcmD3T:-L2XA4GIcfYdhDFBHuQT:bc84eyq) ([raw file](https://github.com/elliotchance/c2go/blob/3afc91c8bfae3ee976dc65b6c6953719afa3288f/transpiler/binary.go#L297)):*
> ```Go
> 			var findUnion func(ast.Node)
> 			var UnionNode ast.Node
> 			findUnion = func(node ast.Node) {
> ```

Please avoid anonymous functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/523)*

**Comment by Konstantin8105** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/binary.go, line 297 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/523#-L2XA4GHzZd7rMkcmD3T:-L2Z0cOPmxc7Av5SV8wt:bb6un1j) ([raw file](https://github.com/elliotchance/c2go/blob/3afc91c8bfae3ee976dc65b6c6953719afa3288f/transpiler/binary.go#L297)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please avoid anonymous functions.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/523)*

**Comment by Konstantin8105** [comment]
Ready for review.

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/523)*

**Pull request merged**
