### PR TITLE
malloc implementation for VarDecl. Fix #515

### LINKED ISSUE #515: CSTD: malloc
C example code:
```c
    char *stringXPos = malloc(length * sizeof(char));
    char *stringYPos = malloc(length * sizeof(char));
```
In Go:
```go
        var stringXPos []byte = malloc(uint32(length) * 1).([]byte)
        var stringYPos []byte = malloc(uint32(length) * 1).([]byte)
```
Documentation: http://www.cplusplus.com/reference/cstdlib/malloc/
Need for #67 

Another C example:
```c
/* malloc example: random string generator*/
#include <stdio.h>      /* printf, scanf, NULL */
#include <stdlib.h>     /* malloc, free, rand */

int main ()
{
  int i,n;
  char * buffer;

  printf ("How long do you want the string? ");
  scanf ("%d", &i);

  buffer = (char*) malloc (i+1);
  if (buffer==NULL) exit (1);

  for (n=0; n<i; n++)
    buffer[n]=rand()%26+'a';
  buffer[i]='\0';

  printf ("Random string: %s\n",buffer);
  free (buffer);

  return 0;
}
```
Example:
```c
int *ptr = (int *) malloc(10 * sizeof (int));
```
```c
ptr=malloc(sizeof(int))
```
```c
p = (int **)malloc(m*sizeof(int*));
```
```c
int *ptr;
ptr = malloc(10 * sizeof (*ptr)); // Without a cast
ptr = (int*)malloc(10 * sizeof (int)); // With a cast
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #515 
Need for #67

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/535)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/binary.go, line 376 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/535#-L2HjSQ_6x5v4MinRHZN:-L2HjSQaRXvMnbedRmqJ:b-vuatvw) ([raw file](https://github.com/elliotchance/c2go/blob/f3d68f4719abb915a347269246ccf22576f2812f/transpiler/binary.go#L376)):*
> ```Go
> 	var expr *ast.CallExpr
> 
> 	foundCall = func(n ast.Node) {
> ```

Please avoid anonymous functions. Move it to a private function outside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/535)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/binary.go, line 418 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/535#-L2HjoJ6e6YQLiZ7ykQI:-L2HjoJ6e6YQLiZ7ykQJ:b-m9ngg1) ([raw file](https://github.com/elliotchance/c2go/blob/f3d68f4719abb915a347269246ccf22576f2812f/transpiler/binary.go#L418)):*
> ```Go
> }
> 
> func GenerateAlloc(p *program.Program, allocSize ast.Node, leftType string) (
> ```

Does this need to be in the public API? Otherwise use `generateAlloc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/535)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transpiler/binary.go, line 376 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/535#-L2HjSQ_6x5v4MinRHZN:-L2RcfWg6KH2J3S5xh1S:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f3d68f4719abb915a347269246ccf22576f2812f/transpiler/binary.go#L376)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please avoid anonymous functions. Move it to a private function outside.
</blockquote></details>

Done.

---

*[transpiler/binary.go, line 418 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/535#-L2HjoJ6e6YQLiZ7ykQI:-L2RchqLlcG5KxQVIiaj:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/f3d68f4719abb915a347269246ccf22576f2812f/transpiler/binary.go#L418)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Does this need to be in the public API? Otherwise use `generateAlloc`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/535)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/535)*

**Pull request merged**
