### PR TITLE
Refactoring: separate TranslationUnitDecl. Fixes #364

### LINKED ISSUE #364: Refactoring: separate TranslationUnitDecl
Create new function and move
https://github.com/elliotchance/c2go/blob/5ff3d07375980c13c11292976f9bfa63b40556e3/transpiler/transpiler.go#L324-L356
to function `translatileUnitDecl()`

### PR DESCRIPTION
**Pull request by Konstantin8105**
see #364

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/385)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
closes #364

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/transpationUnit.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/385#-L-TcXO1sMEwntHlrEKa:-L-TcXO1sMEwntHlrEKb:b-ungkej) ([raw file](https://github.com/elliotchance/c2go/blob/51a9af1790733d2b81fed2223100504c8765732a/transpiler/transpationUnit.go#L1)):*
> ```Go
> package transpiler
> ```

Please use snake case (https://en.wikipedia.org/wiki/Snake_case) for file names. Also there is a spelling mistake in the file name. It should be `transpiler/translation_unit.go`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/385)*

**Comment by Konstantin8105** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[transpiler/translation_unit.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/385#-L-TcXO1sMEwntHlrEKa:-L-Xq9QSIGrEkOXXKCfU:bb7f2mf) ([raw file](https://github.com/elliotchance/c2go/blob/51a9af1790733d2b81fed2223100504c8765732a/transpiler/translation_unit.go#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please use snake case (https://en.wikipedia.org/wiki/Snake_case) for file names. Also there is a spelling mistake in the file name. It should be `transpiler/translation_unit.go`
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/385)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/385)*

**Pull request merged**
