### PR TITLE
struct typedef without name

### PR DESCRIPTION
**Pull request by Konstantin8105**
For #265

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/270)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/declarations.go, line 58 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxAf96erjthCIVAm25b:-KxAf96erjthCIVAm25c:bhuozdm) ([raw file](https://github.com/elliotchance/c2go/blob/68590bf2cb8eddb2426e09c86a352488c516ff3d/transpiler/declarations.go#L58)):*
> ```Go
> 	// Name of RecordDecl is empty
> 	// So, we have to save all n.Children at the base of Address
> 	if name == "" && !p.IsTypeAlreadyDefined(name) {
> ```

There is no need to check if the name is not defined, you are already testing that it is blank. Another way to look at it that we never want an empty name registered:

```go
if name == "" {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[transpiler/declarations.go, line 58 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxAf96erjthCIVAm25b:-KxC2ziWIdKIAoFj8SpM:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/68590bf2cb8eddb2426e09c86a352488c516ff3d/transpiler/declarations.go#L58)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

There is no need to check if the name is not defined, you are already testing that it is blank. Another way to look at it that we never want an empty name registered:

```go
if name == "" {
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270)*

**Comment by Konstantin8105** [comment]
Not success only for Mac

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxFkHg9dZVGqwCkYvuL:-KxFkHg9dZVGqwCkYvuM:by8x1jj) (no related file):*
Once the build is passing this is ready to be merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270)*

**Comment by Konstantin8105** [comment]
May you clarify - How I can fix the bug for Mac build if I haven't Mac? What tool can I use?

**Comment by Konstantin8105** [comment]
Need help:
My Mac show
```
 2017-10-30 06:52:52 ⌚  Konstantins-iMac in ~/work/src/github.com/elliotchance/c2go
± |structTypedef → origin ✓| → go test -tags=integration 
PASS
ok  	github.com/elliotchance/c2go	87.020s
```
but in travis:
```
    --- FAIL: TestIntegrationScripts/tests/struct.c (1.84s)
    	main_test.go:159: Expected 
    		Got: # command-line-arguments
    		build/tests/struct/main_test.go:642:8: undefined: ts_c
    		build/tests/struct/main_test.go:644:13: undefined: noarch.ByteSliceToFloat64
```
Don't understood - How to solve?

**Comment by elliotchance** [comment]
These issues can be very painful to debug. It is likely caused by Travis having a different version of `clang`.

You can actually run a Travis build in debug more (this let you log into the instance and run commands): https://docs.travis-ci.com/user/running-build-in-debug-mode/

Keep in mind that `clang` and `clang++` are part of the same package, however `clang` is only for C which is what c2go uses.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270#-:-KxjPp-N7GnPKrAJ0EzZ:b6udvvd)*

**Comment by Konstantin8105** [comment]
Don't found - Please check - Is that feature is switch on?
https://docs.travis-ci.com/user/running-build-in-debug-mode/ :
`This feature is available for private repositories and those public repositories for which the feature is enabled.`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270#-:-KxlXy-M66FApN5WSpFE:bjc9eef)*

**Comment by elliotchance** [comment]
I see. I will try and debug it when I next get a chance.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270#-:-KxoZuRTK_Wuu_fgv3TW:be2nlp1)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[transpiler/declarations.go, line 165 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxyvOYP7Mk9AnOgsMuJ:-KxyvOYP7Mk9AnOgsMuK:b-z3yf6q) ([raw file](https://github.com/elliotchance/c2go/blob/75daf876711f2710162b4d94d6b214b23409937d/transpiler/declarations.go#L165)):*
> ```Go
> 				}
> 			}
> 			return nil, fmt.Errorf("Cannot found ast.Record")
> ```

"cannot find ast.Record"

---

*[transpiler/declarations.go, line 180 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxyvLGsS_KxQUhH18Te:-KxyvLGsS_KxQUhH18Tf:bgzgqls) ([raw file](https://github.com/elliotchance/c2go/blob/75daf876711f2710162b4d94d6b214b23409937d/transpiler/declarations.go#L180)):*
> ```Go
> 				}
> 				// removing from map, because now defined
> 				// delete(p.StructsEmptyName, n.Addr)
> ```

Remove or uncomment this.

---

*[transpiler/declarations.go, line 183 at r4](https://reviewable.io:443/reviews/elliotchance/c2go/270#-KxyvR5sTEaz6pXex5B0:-KxyvR5sTEaz6pXex5B1:bjuahsu) ([raw file](https://github.com/elliotchance/c2go/blob/75daf876711f2710162b4d94d6b214b23409937d/transpiler/declarations.go#L183)):*
> ```Go
> 				return nil
> 			} else {
> 				p.AddMessage(p.GenerateWarningMessage(fmt.Errorf("Cannot found address for struct without name"), n))
> ```

"cannot find address for struct without name"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/270)*

**Comment by Konstantin8105** [comment]
I have to close that PR, because I do somethink wrong with github and start a new branch

**Pull request closed without merging**
