### PR TITLE
Implements compound assignment operators

### PR DESCRIPTION
**Pull request by x-tyger**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/98)

### CODE REVIEW

**Comment by cristim** [comment]
@x-tyger please fix the codeclimate issues: https://codeclimate.com/github/elliotchance/c2go/pull/98

**Comment by elliotchance** [comment]
I have approved those two failures because we currently do not put any documentation on any of the `ast` items. Maybe we should find the original clang docs and copy the some docs for what each of them actually mean? That would be a seperate PR though.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ast/compound_assign_op.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/98#-Kjs2YcdK3yHjG2dBjco:-Kjs2YcdK3yHjG2dBjcp:b-zck0wo) ([raw file](https://github.com/elliotchance/c2go/blob/6adddd51d8b0e5b02fdd1d52127b29d42ff2f593/ast/compound_assign_op.go#L1)):*
> ```Go
> package ast
> ```

I know this sounds like a really minor thing, but please name this and the test file `compound_assign_operator` to stay consistent with all the other files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/98#-:-Kjs38zhaMPN4DNlXDae:b-y1i5wx)*

**Comment by x-tyger** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ast/compound_assign_operator.go, line 1 at r1](https://reviewable.io:443/reviews/elliotchance/c2go/98#-Kjs2YcdK3yHjG2dBjco:-KjsVKF-pe86UXLKDxpC:b-896fix) ([raw file](https://github.com/elliotchance/c2go/blob/6adddd51d8b0e5b02fdd1d52127b29d42ff2f593/ast/compound_assign_operator.go#L1)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

I know this sounds like a really minor thing, but please name this and the test file `compound_assign_operator` to stay consistent with all the other files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/98)*

**Comment by elliotchance** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/98)*

**Pull request merged**
