### PR TITLE
Added support for simple pointer arithmetic. Fixes #434

### LINKED ISSUE #434: simple pointer operations
C:
```c
#include <stdio.h>
#include <stdlib.h>

int main(){
        int *map;
        map = (int*)calloc(10,sizeof(int));
        *(map + 1) = 42;
        printf("value = %d",*(map+1));
        return 0;
}
```
AST:
```
`-FunctionDecl 0x2f46670 <1.c:4:1, line:10:1> line:4:5 main 'int ()'
  `-CompoundStmt 0x2f46cb8 <col:11, line:10:1>
    |-DeclStmt 0x2f46790 <line:5:2, col:10>
    | `-VarDecl 0x2f46730 <col:2, col:7> col:7 used map 'int *'
    |-BinaryOperator 0x2f46920 <line:6:2, col:35> 'int *' '='
    | |-DeclRefExpr 0x2f467a8 <col:2> 'int *' lvalue Var 0x2f46730 'map' 'int *'
    | `-CStyleCastExpr 0x2f468f8 <col:8, col:35> 'int *' <BitCast>
    |   `-CallExpr 0x2f46890 <col:14, col:35> 'void *'
    |     |-ImplicitCastExpr 0x2f46878 <col:14> 'void *(*)(unsigned long, unsigned long)' <FunctionToPointerDecay>
    |     | `-DeclRefExpr 0x2f467d0 <col:14> 'void *(unsigned long, unsigned long)' Function 0x2f3bb38 'calloc' 'void *(unsigned long, unsigned long)'
    |     |-ImplicitCastExpr 0x2f468c8 <col:21> 'unsigned long' <IntegralCast>
    |     | `-IntegerLiteral 0x2f467f8 <col:21> 'int' 10
    |     `-UnaryExprOrTypeTraitExpr 0x2f46828 <col:24, col:34> 'unsigned long' sizeof 'int'
    |-BinaryOperator 0x2f46a30 <line:7:2, col:15> 'int' '='
    | |-UnaryOperator 0x2f469f0 <col:2, col:11> 'int' lvalue prefix '*'
    | | `-ParenExpr 0x2f469d0 <col:3, col:11> 'int *'
    | |   `-BinaryOperator 0x2f469a8 <col:4, col:10> 'int *' '+'
    | |     |-ImplicitCastExpr 0x2f46990 <col:4> 'int *' <LValueToRValue>
    | |     | `-DeclRefExpr 0x2f46948 <col:4> 'int *' lvalue Var 0x2f46730 'map' 'int *'
    | |     `-IntegerLiteral 0x2f46970 <col:10> 'int' 1
    | `-IntegerLiteral 0x2f46a10 <col:15> 'int' 42
    |-CallExpr 0x2f46c00 <line:8:2, col:30> 'int'
    | |-ImplicitCastExpr 0x2f46be8 <col:2> 'int (*)(const char *, ...)' <FunctionToPointerDecay>
    | | `-DeclRefExpr 0x2f46a58 <col:2> 'int (const char *, ...)' Function 0x2f18f88 'printf' 'int (const char *, ...)'
    | |-ImplicitCastExpr 0x2f46c50 <col:9> 'const char *' <BitCast>
    | | `-ImplicitCastExpr 0x2f46c38 <col:9> 'char *' <ArrayToPointerDecay>
    | |   `-StringLiteral 0x2f46ab8 <col:9> 'char [11]' lvalue "value = %d"
    | `-ImplicitCastExpr 0x2f46c68 <col:22, col:29> 'int' <LValueToRValue>
    |   `-UnaryOperator 0x2f46b98 <col:22, col:29> 'int' lvalue prefix '*'
    |     `-ParenExpr 0x2f46b78 <col:23, col:29> 'int *'
    |       `-BinaryOperator 0x2f46b50 <col:24, col:28> 'int *' '+'
    |         |-ImplicitCastExpr 0x2f46b38 <col:24> 'int *' <LValueToRValue>
    |         | `-DeclRefExpr 0x2f46af0 <col:24> 'int *' lvalue Var 0x2f46730 'map' 'int *'
    |         `-IntegerLiteral 0x2f46b18 <col:28> 'int' 1
    `-ReturnStmt 0x2f46ca0 <line:9:2, col:9>
      `-IntegerLiteral 0x2f46c80 <col:9> 'int' 0
```

Go:
```go
func main() {
        __init()
        var map_ []int
        map_ = make([]int, 10*4/4)
        (map_ + 1)[0] = 42
        noarch.Printf([]byte("value = %d\x00"), (map_ + 1)[0])
        return
}
```

Run Go code:
```
○ → go run 1.go
# command-line-arguments
./1.go:403: invalid operation: map_ + 1 (mismatched types []int and int)
./1.go:404: invalid operation: map_ + 1 (mismatched types []int and int)
```

### PR DESCRIPTION
**Pull request by Konstantin8105**
Close #434
See #67 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/c2go/441)

### CODE REVIEW

**Comment by Konstantin8105** [comment]
Not ready for review

**Comment by Konstantin8105** [comment]
Ready for review if Ok in travis

**Comment by elliotchance** [comment]
Reviewed 4 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[transpiler/call.go, line 74 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L01XEkhwieVi2uIbD-z:-L01XEkhwieVi2uIbD0-:b-v64jts) ([raw file](https://github.com/elliotchance/c2go/blob/a8c1cfaa0450b9b2212613dbf06977ffd36572d5/transpiler/call.go#L74)):*
> ```Go
> 
> 	// function stdlib.c
> 	if functionName == "calloc" && len(n.Children()) == 3 {
> ```

Can you be sure that `len(n.Children()) == 3` means that there are 3 arguments? Maybe you should extract the arguments to be sure. I remember we had a function for returning a specific type of node, but I cannot remember where that code is now...

Something like this?

```go
children := GetNodesOfType(n.Children(), (*ast.Something)(nil))
if functionName == "calloc" && len(children) == 3 {
    // children is not reliable even when the AST has other child nodes
    // that are not arguments.
}
```

It will make the code more robust if there are any extra children that are not arguments. Also you rely on indexes like `0` and `1` below but the actual parameters may not be located there, use `children[0]` instead to know it's correct.

---

*[transpiler/unary.go, line 173 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L01ZlyUXCEQ5dJpeVQB:-L01ZlyVzsbJyReag09v:b-8hduxo) ([raw file](https://github.com/elliotchance/c2go/blob/a8c1cfaa0450b9b2212613dbf06977ffd36572d5/transpiler/unary.go#L173)):*
> ```Go
> // Example of using:
> // *(t + 1) = ...
> func transpilePointerArith(n *ast.UnaryOperator, p *program.Program) (
> ```

This is really awesome! Does this also work with decrementing pointer arithmetic? Like  the common loop: `while (p-- != NULL) { }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/441)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[transpiler/call.go, line 74 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L01XEkhwieVi2uIbD-z:-L01_zj-8F-RUI7IN6uC:b-audq93) ([raw file](https://github.com/elliotchance/c2go/blob/a8c1cfaa0450b9b2212613dbf06977ffd36572d5/transpiler/call.go#L74)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Can you be sure that `len(n.Children()) == 3` means that there are 3 arguments? Maybe you should extract the arguments to be sure. I remember we had a function for returning a specific type of node, but I cannot remember where that code is now...

Something like this?

```go
children := GetNodesOfType(n.Children(), (*ast.Something)(nil))
if functionName == "calloc" && len(children) == 3 {
    // children is not reliable even when the AST has other child nodes
    // that are not arguments.
}
```

It will make the code more robust if there are any extra children that are not arguments. Also you rely on indexes like `0` and `1` below but the actual parameters may not be located there, use `children[0]` instead to know it's correct.
</blockquote></details>

This is the method: https://github.com/elliotchance/c2go/blob/master/ast/traverse.go#L12

However, that is recursive. You may want to create a similar method that does not recursive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/441)*

**Comment by Konstantin8105** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[transpiler/call.go, line 74 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L01XEkhwieVi2uIbD-z:-L03Fq_v-oOAwhDWI9AX:b-n2lc3o) ([raw file](https://github.com/elliotchance/c2go/blob/a8c1cfaa0450b9b2212613dbf06977ffd36572d5/transpiler/call.go#L74)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is the method: https://github.com/elliotchance/c2go/blob/master/ast/traverse.go#L12

However, that is recursive. You may want to create a similar method that does not recursive.
</blockquote></details>

```
|   |   `-CallExpr 0x1dce580 <col:18, col:40> 'void *'
|   |     |-ImplicitCastExpr 0x1dce568 <col:18> 'void *(*)(unsigned long, unsigned long)' <FunctionToPointerDecay>
|   |     | `-DeclRefExpr 0x1dce4c8 <col:18> 'void *(unsigned long, unsigned long)' Function 0x1dce350 'calloc' 'void *(unsigned long, unsigned long)'
|   |     |-ImplicitCastExpr 0x1dce5b8 <col:25> 'unsigned long' <IntegralCast>
|   |     | `-IntegerLiteral 0x1dce4f0 <col:25> 'int' 5
|   |     `-UnaryExprOrTypeTraitExpr 0x1dce520 <col:27, col:39> 'unsigned long' sizeof 'float'
```
3 node:
1) for function identification
2) for amount of elements
3) for type size
I suppose it is like ForStmt - it has 5 children. 
I will add more test for that point.

---

*[transpiler/unary.go, line 173 at r2](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L01ZlyUXCEQ5dJpeVQB:-L03I2If1hEzi96eiFtP:bxdn4e4) ([raw file](https://github.com/elliotchance/c2go/blob/a8c1cfaa0450b9b2212613dbf06977ffd36572d5/transpiler/unary.go#L173)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

This is really awesome! Does this also work with decrementing pointer arithmetic? Like  the common loop: `while (p-- != NULL) { }`
</blockquote></details>

Now, it is not support

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/441)*

**Comment by elliotchance** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/array.c, line 232 at r3](https://reviewable.io:443/reviews/elliotchance/c2go/441#-L06lgEuJBN4AFsMhrD9:-L06lgEuJBN4AFsMhrDA:bccpe83) ([raw file](https://github.com/elliotchance/c2go/blob/4a241da562f27d8ea26bb6793f4db73ffd4da0d8/tests/array.c#L232)):*
> ```C
> 		is_true(arr != NULL);
> 		(void)(arr);
> 	}
> ```

Awesome!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/c2go/441)*

**Pull request merged**
